

api = {'acquisitions': [{'acquirerCode': 'HDFC', 'apps': [], 'bankIdentifier': 'A90167', 'categoryCode': '4112', 'middlewareCode': 'EzeTapDefault', 'offline': False, 'paymentGateway': 'DUMMY', 'priority': 0, 'requestTime': 1534677024107, 'selfSignUp': False, 'settingVer': 0, 'settlementCycleDays': 0, 'status': 'ACTIVE', 'terminals': [{'acquirerCode': 'HDFC', 'apps': [], 'billingType': 'FULL', 'emiOnly': False, 'ignoreProperty': False, 'initialized': True, 'keyRotationReqd': True, 'kxWithPg': True, 'location': 'Auto Test Location', 'loyaltyEnabled': False, 'mid': 'AUTOMID12345678', 'offline': False, 'paymentGateway': 'DUMMY', 'requestTime': 1534677024107, 'selfSignUp': False, 'sequenceId': 1, 'settingVer': 0, 'status': 'ACTIVE', 'tid': '12345678', 'tidPriority': 0, 'tleEnabled': True, 'upgrade': True}], 'upgrade': True}], 'addresses': [{'addressType': 'PRIMARY', 'apps': [], 'city': 'Auto Test City', 'country': 'India', 'offline': False, 'requestTime': 1534677024107, 'selfSignUp': False, 'settingVer': 0, 'state': 'Auto Test State', 'street1': 'Auto Test Street', 'upgrade': True, 'zip': '712136'}], 'applicationId': '', 'apps': [], 'categoryCode': '4112', 'currencyCode': 'INR', 'merchantCode': 'EzeAuto_Merchant_100', 'middlewareCode': 'EzeTapDefault', 'multiFactorAuthRequired': 'N', 'name': 'EzeAuto_Merchant_100', 'offline': False, 'orgType': 'MERCHANT', 'reportingOrgCategory': 'OTHER', 'reportingOrgCode': 'EzeAuto_Merchant_100', 'reportingOrgType': 'SMB', 'requestTime': 1534677024107, 'selfSignUp': False, 'settingTemplate': 'RETAIL_MPOS', 'settingVer': 0, 'status': 'ACTIVE', 'subscriptionPlan': 'BASIC', 'timeZone': 'Asia/Calcutta', 'upgrade': True, 'username': '9886191638', 'password': 'A000000', 'users': [{'applicationId': '', 'apps': [], 'defaultProcessCode': '_DEF_PROC', 'forceChangePasswd': False, 'kycApproved': False, 'locale': 'en', 'mobileNumber': '19283774903', 'name': 'EzeAuto_user_101', 'offline': False, 'requestTime': 1534677024107, 'roles': ['ROLE_CLSUPPORT', 'ROLE_CLADMIN', 'ROLE_CLAGENT', 'ROLE_CLAGENT_REFUND', 'ROLE_CLPROMO', 'ROLE_ORG_MANAGER', 'ROLE_CLAGENTPORTAL', 'ROLE_TAG_ADMIN', 'ROLE_CLAGENTVOID', 'ROLE_CLREFUND'], 'selfSignUp': False, 'selfSignedUser': False, 'settingVer': 0, 'status': 'ACTIVE', 'upgrade': True, 'userPassword': 'A123456', 'userToken': '19283774903'}, {'applicationId': '', 'apps': [], 'defaultProcessCode': '_DEF_PROC', 'forceChangePasswd': False, 'kycApproved': False, 'locale': 'en', 'mobileNumber': '19283774903', 'name': 'EzeAuto_user_101', 'offline': False, 'requestTime': 1534677024107, 'roles': ['ROLE_CLSUPPORT', 'ROLE_CLADMIN', 'ROLE_CLAGENT', 'ROLE_CLAGENT_REFUND', 'ROLE_CLPROMO', 'ROLE_ORG_MANAGER', 'ROLE_CLAGENTPORTAL', 'ROLE_TAG_ADMIN', 'ROLE_CLAGENTVOID', 'ROLE_CLREFUND'], 'selfSignUp': False, 'selfSignedUser': False, 'settingVer': 0, 'status': 'ACTIVE', 'upgrade': True, 'userPassword': 'A123456', 'userToken': '19283774903'}]}

lst_user = ["user1", "user2"]

for i in range(0,2):
    api["users"][i]["name"] = lst_user[i]

print(api["users"])
