[Stamp]
datestamp = 2022-05-17
timestamp = 17:37:13

[System]
automation_suite_path = /home/ezetap-10182/Downloads/EzeAuto

[ExcelFiles]
filepath_testcases_surfaceui = /home/ezetap-10182/Downloads/EzeAuto/DataProvider/TestCases_SurfaceUI.xlsx
filepath_testcasesdetail = /home/ezetap-10182/Downloads/EzeAuto/DataProvider/TestCasesDetail.xlsx

[Reports]
excelreportpath = /home/ezetap-10182/Downloads/EzeAuto/Reports/ExecutionDate_2022-05-17/ExecutionTime_17:37:13/ExcelReport
allurereportpath = /home/ezetap-10182/Downloads/EzeAuto/Reports/ExecutionDate_2022-05-17/ExecutionTime_17:37:13/AllureReport
pdfreportpath = /home/ezetap-10182/Downloads/EzeAuto/Reports/ExecutionDate_2022-05-17/ExecutionTime_17:37:13/PDFReport

[Logs]
executionlogpath = /home/ezetap-10182/Downloads/EzeAuto/Logs/ExecutionDate_2022-05-17/ExecutionTime_17:37:13/ExecutionLog
serverlogpath = /home/ezetap-10182/Downloads/EzeAuto/Logs/ExecutionDate_2022-05-17/ExecutionTime_17:37:13/ServerLog

