"""
rearch_locators_generated.py
----------------------------
AUTO-GENERATED by Tools/rearch_xpath_extractor.py
Generated : 2026-03-11 20:06
Source    : uiautomator XML dumps (NATIVE_APP context)
Package   : com.razorpay.pos

!! REVIEW BEFORE USE !!
- Rename / remove duplicates
- Confirm each locator by running a quick find_element test
- Merge reviewed entries into PageFactory/ReArch/rearch_locators.py
"""

from appium.webdriver.common.appiumby import AppiumBy

REARCH_PACKAGE = "com.razorpay.pos"



# ════════════════════════════════════════════════════════════════════════════
# payment_flow
# ════════════════════════════════════════════════════════════════════════════

class payment_flow:
    """Auto-generated from uiautomator dump — review and adjust as needed."""
    lbl_view                       = (AppiumBy.XPATH, "//android.view.View[@index='0']")  # View
    btn_button                     = (AppiumBy.XPATH, "//android.widget.Button[@index='0']")  # Button
    img_e91cc2003e6491b7f659       = (AppiumBy.XPATH, "//android.widget.Image[@text='e91cc2003e6491b7f659']")  # Image · "e91cc2003e6491b7f659"
    btn_button_2                   = (AppiumBy.XPATH, "//android.widget.Button[@index='2']")  # Button
    lbl_textview                   = (AppiumBy.XPATH, "//android.widget.TextView[@text='₹']")  # TextView · "₹"
    lbl_0                          = (AppiumBy.XPATH, "//android.widget.TextView[@text='0']")  # TextView · "0"
    btn_add_tip                    = (AppiumBy.XPATH, "//android.widget.Button[@text='Add Tip']")  # Button · "Add Tip"
    btn_card                       = (AppiumBy.XPATH, "//android.widget.Button[@text='Card']")  # Button · "Card"
    btn_upi                        = (AppiumBy.XPATH, "//android.widget.Button[@text='UPI']")  # Button · "UPI"
    btn_button_3                   = (AppiumBy.XPATH, "//android.widget.Button[@index='6']")  # Button
    btn_1                          = (AppiumBy.XPATH, "//android.widget.Button[@text='1']")  # Button · "1"
    btn_2                          = (AppiumBy.XPATH, "//android.widget.Button[@text='2']")  # Button · "2"
    btn_3                          = (AppiumBy.XPATH, "//android.widget.Button[@text='3']")  # Button · "3"
    btn_4                          = (AppiumBy.XPATH, "//android.widget.Button[@text='4']")  # Button · "4"
    btn_5                          = (AppiumBy.XPATH, "//android.widget.Button[@text='5']")  # Button · "5"
    btn_6                          = (AppiumBy.XPATH, "//android.widget.Button[@text='6']")  # Button · "6"
    btn_7                          = (AppiumBy.XPATH, "//android.widget.Button[@text='7']")  # Button · "7"
    btn_8                          = (AppiumBy.XPATH, "//android.widget.Button[@text='8']")  # Button · "8"
    btn_9                          = (AppiumBy.XPATH, "//android.widget.Button[@text='9']")  # Button · "9"
    btn_button_4                   = (AppiumBy.XPATH, "//android.widget.Button[@text='•']")  # Button · "•"
    btn_0                          = (AppiumBy.XPATH, "//android.widget.Button[@text='0']")  # Button · "0"
    btn_button_5                   = (AppiumBy.XPATH, "//android.widget.Button[@index='18']")  # Button


# ════════════════════════════════════════════════════════════════════════════
# payment_flow
# ════════════════════════════════════════════════════════════════════════════

class payment_flow:
    """Auto-generated from uiautomator dump — review and adjust as needed."""
    lbl_view                       = (AppiumBy.XPATH, "//android.view.View[@index='0']")  # View
    btn_button                     = (AppiumBy.XPATH, "//android.widget.Button[@index='0']")  # Button
    img_e91cc2003e6491b7f659       = (AppiumBy.XPATH, "//android.widget.Image[@text='e91cc2003e6491b7f659']")  # Image · "e91cc2003e6491b7f659"
    btn_button_2                   = (AppiumBy.XPATH, "//android.widget.Button[@index='2']")  # Button
    lbl_textview                   = (AppiumBy.XPATH, "//android.widget.TextView[@text='₹']")  # TextView · "₹"
    lbl_0                          = (AppiumBy.XPATH, "//android.widget.TextView[@text='0']")  # TextView · "0"
    btn_add_tip                    = (AppiumBy.XPATH, "//android.widget.Button[@text='Add Tip']")  # Button · "Add Tip"
    btn_card                       = (AppiumBy.XPATH, "//android.widget.Button[@text='Card']")  # Button · "Card"
    btn_upi                        = (AppiumBy.XPATH, "//android.widget.Button[@text='UPI']")  # Button · "UPI"
    btn_button_3                   = (AppiumBy.XPATH, "//android.widget.Button[@index='6']")  # Button
    btn_1                          = (AppiumBy.XPATH, "//android.widget.Button[@text='1']")  # Button · "1"
    btn_2                          = (AppiumBy.XPATH, "//android.widget.Button[@text='2']")  # Button · "2"
    btn_3                          = (AppiumBy.XPATH, "//android.widget.Button[@text='3']")  # Button · "3"
    btn_4                          = (AppiumBy.XPATH, "//android.widget.Button[@text='4']")  # Button · "4"
    btn_5                          = (AppiumBy.XPATH, "//android.widget.Button[@text='5']")  # Button · "5"
    btn_6                          = (AppiumBy.XPATH, "//android.widget.Button[@text='6']")  # Button · "6"
    btn_7                          = (AppiumBy.XPATH, "//android.widget.Button[@text='7']")  # Button · "7"
    btn_8                          = (AppiumBy.XPATH, "//android.widget.Button[@text='8']")  # Button · "8"
    btn_9                          = (AppiumBy.XPATH, "//android.widget.Button[@text='9']")  # Button · "9"
    btn_button_4                   = (AppiumBy.XPATH, "//android.widget.Button[@text='•']")  # Button · "•"
    btn_0                          = (AppiumBy.XPATH, "//android.widget.Button[@text='0']")  # Button · "0"
    btn_button_5                   = (AppiumBy.XPATH, "//android.widget.Button[@index='18']")  # Button
    btn_close_overlay              = (AppiumBy.XPATH, "//android.widget.Button[@text='Close overlay']")  # Button · "Close overlay"
    btn_button_6                   = (AppiumBy.XPATH, "//android.widget.Button[@index='0']")  # Button
    lbl_order_details              = (AppiumBy.XPATH, "//android.widget.TextView[@text='Order Details']")  # TextView · "Order Details"
    lbl_order_id                   = (AppiumBy.XPATH, "//android.view.View[@text='Order ID']")  # View · "Order ID"
    txt_ordernumberinput           = (AppiumBy.ID, "order-number-input")  # EditText · [order-number-input]
    lbl_device_serial              = (AppiumBy.XPATH, "//android.view.View[@text='Device Serial']")  # View · "Device Serial"
    txt_additionalfieldinput       = (AppiumBy.ID, "additional-field-input")  # EditText · [additional-field-input]
    btn_cancel                     = (AppiumBy.XPATH, "//android.widget.Button[@text='Cancel']")  # Button · "Cancel"
    btn_proceed                    = (AppiumBy.XPATH, "//android.widget.Button[@text='Proceed']")  # Button · "Proceed"


# ════════════════════════════════════════════════════════════════════════════
# payment_flow
# ════════════════════════════════════════════════════════════════════════════

class payment_flow:
    """Auto-generated from uiautomator dump — review and adjust as needed."""
    lbl_view                       = (AppiumBy.XPATH, "//android.view.View[@index='0']")  # View
    lbl_page                       = (AppiumBy.ID, "page")  # View · [page]
    btn_button                     = (AppiumBy.XPATH, "//android.widget.Button[@index='0']")  # Button
    lbl_payment_amount             = (AppiumBy.XPATH, "//android.widget.TextView[@text='Payment Amount']")  # TextView · "Payment Amount"
    lbl_textview                   = (AppiumBy.XPATH, "//android.widget.TextView[@text='₹']")  # TextView · "₹"
    lbl_96                         = (AppiumBy.XPATH, "//android.widget.TextView[@text='96']")  # TextView · "96"
    lbl_order_id_ez202603112011465827 = (AppiumBy.XPATH, "//android.widget.TextView[@text='Order ID: EZ202603112011465827']")  # TextView · "Order ID: EZ202603112011465827"
    btn_upi                        = (AppiumBy.XPATH, "//android.widget.Button[@text='UPI']")  # Button · "UPI"
    btn_card                       = (AppiumBy.XPATH, "//android.widget.Button[@text='Card']")  # Button · "Card"
    btn_payment_link               = (AppiumBy.XPATH, "//android.widget.Button[@text='Payment link']")  # Button · "Payment link"
    btn_pre_auth                   = (AppiumBy.XPATH, "//android.widget.Button[@text='Pre Auth']")  # Button · "Pre Auth"
    btn_bharat_qr                  = (AppiumBy.XPATH, "//android.widget.Button[@text='Bharat QR']")  # Button · "Bharat QR"
    btn_cash                       = (AppiumBy.XPATH, "//android.widget.Button[@text='Cash']")  # Button · "Cash"
    btn_cheque                     = (AppiumBy.XPATH, "//android.widget.Button[@text='Cheque']")  # Button · "Cheque"
    btn_demand_draft               = (AppiumBy.XPATH, "//android.widget.Button[@text='Demand Draft']")  # Button · "Demand Draft"
    lbl_secured_by                 = (AppiumBy.XPATH, "//android.widget.TextView[@text='Secured by']")  # TextView · "Secured by"
    img_e91cc2003e6491b7f659       = (AppiumBy.XPATH, "//android.widget.Image[@text='e91cc2003e6491b7f659']")  # Image · "e91cc2003e6491b7f659"


# ════════════════════════════════════════════════════════════════════════════
# class payment_flow:
# ════════════════════════════════════════════════════════════════════════════

class payment_flow:
    """Auto-generated from uiautomator dump — review and adjust as needed."""
    lbl_view                       = (AppiumBy.XPATH, "//android.view.View[@index='0']")  # View
    lbl_page                       = (AppiumBy.ID, "page")  # View · [page]
    btn_button                     = (AppiumBy.XPATH, "//android.widget.Button[@index='0']")  # Button
    lbl_payment_amount             = (AppiumBy.XPATH, "//android.widget.TextView[@text='Payment Amount']")  # TextView · "Payment Amount"
    lbl_textview                   = (AppiumBy.XPATH, "//android.widget.TextView[@text='₹']")  # TextView · "₹"
    lbl_96                         = (AppiumBy.XPATH, "//android.widget.TextView[@text='96']")  # TextView · "96"
    lbl_tap_confirm_to_record_this_payment_in_th = (AppiumBy.XPATH, "//android.widget.TextView[@text='Tap confirm to record this payment in the daily summary']")  # TextView · "Tap confirm to record this payment in the daily summary"
    btn_confirm_payment            = (AppiumBy.XPATH, "//android.widget.Button[@text='Confirm Payment']")  # Button · "Confirm Payment"


# ════════════════════════════════════════════════════════════════════════════
# payment_flow
# ════════════════════════════════════════════════════════════════════════════

class payment_flow:
    """Auto-generated from uiautomator dump — review and adjust as needed."""
    lbl_view                       = (AppiumBy.XPATH, "//android.view.View[@index='0']")  # View
    lbl_txnpage                    = (AppiumBy.ID, "txn-page")  # View · [txn-page]
    lbl_txnpagegradient            = (AppiumBy.ID, "txn-page-gradient")  # TextView · [txn-page-gradient]
    img_3f4a4d6f93384d93d938       = (AppiumBy.XPATH, "//android.widget.Image[@text='3f4a4d6f93384d93d938']")  # Image · "3f4a4d6f93384d93d938"
    lbl_thank_you                  = (AppiumBy.XPATH, "//android.widget.TextView[@text='Thank you!']")  # TextView · "Thank you!"
    lbl_payment_successful         = (AppiumBy.XPATH, "//android.widget.TextView[@text='Payment Successful']")  # TextView · "Payment Successful"
    lbl_amount_received            = (AppiumBy.XPATH, "//android.widget.TextView[@text='Amount received']")  # TextView · "Amount received"
    lbl_textview                   = (AppiumBy.XPATH, "//android.widget.TextView[@text='₹']")  # TextView · "₹"
    lbl_96                         = (AppiumBy.XPATH, "//android.widget.TextView[@text='96']")  # TextView · "96"
    btn_view_details               = (AppiumBy.XPATH, "//android.widget.Button[@text='View Details']")  # Button · "View Details"
    btn_print_receipt              = (AppiumBy.XPATH, "//android.widget.Button[@text='Print Receipt']")  # Button · "Print Receipt"
    btn_send_ereceipt              = (AppiumBy.XPATH, "//android.widget.Button[@text='Send E-Receipt']")  # Button · "Send E-Receipt"
    btn_accept_more_payments       = (AppiumBy.XPATH, "//android.widget.Button[@text='Accept more payments']")  # Button · "Accept more payments"


# ════════════════════════════════════════════════════════════════════════════
# transaction_details
# ════════════════════════════════════════════════════════════════════════════

class transaction_details:
    """Auto-generated from uiautomator dump — review and adjust as needed."""
    lbl_view                       = (AppiumBy.XPATH, "//android.view.View[@index='0']")  # View
    lbl_page                       = (AppiumBy.ID, "page")  # View · [page]
    btn_button                     = (AppiumBy.XPATH, "//android.widget.Button[@index='0']")  # Button
    lbl_payments                   = (AppiumBy.XPATH, "//android.widget.TextView[@text='Payments']")  # TextView · "Payments"
    btn_button_2                   = (AppiumBy.XPATH, "//android.widget.Button[@index='2']")  # Button
    btn_button_3                   = (AppiumBy.XPATH, "//android.widget.Button[@index='3']")  # Button
    lbl_todays_sale_11_mar         = (AppiumBy.XPATH, "//android.widget.TextView[@text='Today's Sale, 11 Mar']")  # TextView · "Today's Sale, 11 Mar"
    lbl_textview                   = (AppiumBy.XPATH, "//android.widget.TextView[@text='₹']")  # TextView · "₹"
    lbl_96                         = (AppiumBy.XPATH, "//android.widget.TextView[@text='96']")  # TextView · "96"
    btn_my_dashboard               = (AppiumBy.XPATH, "//android.widget.Button[@text='My Dashboard']")  # Button · "My Dashboard"
    btn_date                       = (AppiumBy.XPATH, "//android.widget.Button[@text='Date']")  # Button · "Date"
    btn_method                     = (AppiumBy.XPATH, "//android.widget.Button[@text='Method']")  # Button · "Method"
    btn_status                     = (AppiumBy.XPATH, "//android.widget.Button[@text='Status']")  # Button · "Status"
    lbl_today_11_mar               = (AppiumBy.XPATH, "//android.view.View[@text='Today, 11 Mar']")  # View · "Today, 11 Mar"
    btn_transaction_logo_cash_813_pm_96_settled = (AppiumBy.XPATH, "//android.widget.Button[@text='transaction logo Cash 8:13 PM ₹96 Settled']")  # Button · "transaction logo Cash 8:13 PM ₹96 Settled"
    btn_transaction_logo_upi_407_pm_389_refunded = (AppiumBy.XPATH, "//android.widget.Button[@text='transaction logo UPI 4:07 PM ₹389 Refunded']")  # Button · "transaction logo UPI 4:07 PM ₹389 Refunded"
    btn_transaction_logo_upi_358_pm_389_refunded = (AppiumBy.XPATH, "//android.widget.Button[@text='transaction logo UPI 3:58 PM ₹389 Refunded']")  # Button · "transaction logo UPI 3:58 PM ₹389 Refunded"
    btn_transaction_logo_upi_223_pm_1_expired = (AppiumBy.XPATH, "//android.widget.Button[@text='transaction logo UPI 2:23 PM ₹1 Expired']")  # Button · "transaction logo UPI 2:23 PM ₹1 Expired"


# ════════════════════════════════════════════════════════════════════════════
# transaction_details
# ════════════════════════════════════════════════════════════════════════════

class transaction_details:
    """Auto-generated from uiautomator dump — review and adjust as needed."""
    lbl_view                       = (AppiumBy.XPATH, "//android.view.View[@index='0']")  # View
    lbl_page                       = (AppiumBy.ID, "page")  # View · [page]
    btn_button                     = (AppiumBy.XPATH, "//android.widget.Button[@index='0']")  # Button
    lbl_search                     = (AppiumBy.XPATH, "//android.widget.TextView[@text='Search']")  # TextView · "Search"
    btn_payment_id                 = (AppiumBy.XPATH, "//android.widget.Button[@text='Payment ID']")  # Button · "Payment ID"
    btn_rrn_number                 = (AppiumBy.XPATH, "//android.widget.Button[@text='RRN Number']")  # Button · "RRN Number"
    btn_amount                     = (AppiumBy.XPATH, "//android.widget.Button[@text='Amount']")  # Button · "Amount"
    btn_auth_code                  = (AppiumBy.XPATH, "//android.widget.Button[@text='Auth Code']")  # Button · "Auth Code"
    txt_edittext                   = (AppiumBy.XPATH, "//android.widget.EditText[@index='3']")  # EditText
