"""
rearch_locators_generated.py
----------------------------
AUTO-GENERATED by Tools/rearch_xpath_extractor.py
Generated : 2026-04-15 11:35
Source    : uiautomator XML dumps (NATIVE_APP context)
Package   : com.razorpay.pos

!! REVIEW BEFORE USE !!
- Rename / remove duplicates
- Confirm each locator by running a quick find_element test
- Merge reviewed entries into PageFactory/ReArch/rearch_native_locators.py
"""

from appium.webdriver.common.appiumby import AppiumBy

REARCH_PACKAGE = "com.razorpay.pos"



# ════════════════════════════════════════════════════════════════════════════
# otherApps
# ════════════════════════════════════════════════════════════════════════════

class otherApps:
    """Auto-generated from uiautomator dump — review and adjust as needed."""
    # TODO: lbl_view — needs stable locator (no resource-id or text; class=android.view.View index=0)
    lbl_page                       = (AppiumBy.ID, "page")  # View · [page]
    # TODO: btn_button — needs stable locator (no resource-id or text; class=android.widget.Button index=0)
    lbl_other_apps                 = (AppiumBy.XPATH, "//android.widget.TextView[@text='Other Apps']")  # TextView · "Other Apps"
    btn_settings_settings          = (AppiumBy.XPATH, "//android.widget.Button[@text='Settings Settings']")  # Button · "Settings Settings"
    btn_calculator_calculator      = (AppiumBy.XPATH, "//android.widget.Button[@text='Calculator Calculator']")  # Button · "Calculator Calculator"
    btn_maxstore_maxstore          = (AppiumBy.XPATH, "//android.widget.Button[@text='MAXSTORE MAXSTORE']")  # Button · "MAXSTORE MAXSTORE"
    btn_appium_settings_appium_settings = (AppiumBy.XPATH, "//android.widget.Button[@text='Appium Settings Appium Settings']")  # Button · "Appium Settings Appium Settings"


# ════════════════════════════════════════════════════════════════════════════
# calcualator
# ════════════════════════════════════════════════════════════════════════════

class calcualator:
    """Auto-generated from uiautomator dump — review and adjust as needed."""
    # TODO: txt_edittext — needs stable locator (no resource-id or text; class=android.widget.EditText index=0)
    # TODO: txt_edittext_2 — needs stable locator (no resource-id or text; class=android.widget.EditText index=1)
    # TODO: el_viewpager — needs stable locator (no resource-id or text; class=android.support.v4.view.ViewPager index=1)
    btn_7                          = (AppiumBy.XPATH, "//android.widget.Button[@text='7']")  # Button · "7"
    btn_8                          = (AppiumBy.XPATH, "//android.widget.Button[@text='8']")  # Button · "8"
    btn_9                          = (AppiumBy.XPATH, "//android.widget.Button[@text='9']")  # Button · "9"
    btn_4                          = (AppiumBy.XPATH, "//android.widget.Button[@text='4']")  # Button · "4"
    btn_5                          = (AppiumBy.XPATH, "//android.widget.Button[@text='5']")  # Button · "5"
    btn_6                          = (AppiumBy.XPATH, "//android.widget.Button[@text='6']")  # Button · "6"
    btn_1                          = (AppiumBy.XPATH, "//android.widget.Button[@text='1']")  # Button · "1"
    btn_2                          = (AppiumBy.XPATH, "//android.widget.Button[@text='2']")  # Button · "2"
    btn_3                          = (AppiumBy.XPATH, "//android.widget.Button[@text='3']")  # Button · "3"
    btn_button                     = (AppiumBy.XPATH, "//android.widget.Button[@text='.']")  # Button · "."
    btn_0                          = (AppiumBy.XPATH, "//android.widget.Button[@text='0']")  # Button · "0"
    btn_button_2                   = (AppiumBy.XPATH, "//android.widget.Button[@text='=']")  # Button · "="
    btn_del                        = (AppiumBy.XPATH, "//android.widget.Button[@text='DEL']")  # Button · "DEL"
    btn_button_3                   = (AppiumBy.XPATH, "//android.widget.Button[@text='÷']")  # Button · "÷"
    btn_button_4                   = (AppiumBy.XPATH, "//android.widget.Button[@text='×']")  # Button · "×"
    btn_button_5                   = (AppiumBy.XPATH, "//android.widget.Button[@text='−']")  # Button · "−"
    btn_button_6                   = (AppiumBy.XPATH, "//android.widget.Button[@text='+']")  # Button · "+"


# ════════════════════════════════════════════════════════════════════════════
# panDetails
# ════════════════════════════════════════════════════════════════════════════

class panDetails:
    """Auto-generated from uiautomator dump — review and adjust as needed."""
    # TODO: lbl_view — needs stable locator (no resource-id or text; class=android.view.View index=0)
    lbl_page                       = (AppiumBy.ID, "page")  # View · [page]
    # TODO: btn_button — needs stable locator (no resource-id or text; class=android.widget.Button index=0)
    lbl_payment_amount             = (AppiumBy.XPATH, "//android.widget.TextView[@text='Payment Amount']")  # TextView · "Payment Amount"
    lbl_textview                   = (AppiumBy.XPATH, "//android.widget.TextView[@text='₹']")  # TextView · "₹"
    lbl_56559                      = (AppiumBy.XPATH, "//android.widget.TextView[@text='56,559']")  # TextView · "56,559"
    btn_pan                        = (AppiumBy.XPATH, "//android.widget.Button[@text='PAN']")  # Button · "PAN"
    btn_form_60                    = (AppiumBy.XPATH, "//android.widget.Button[@text='Form 60']")  # Button · "Form 60"
    lbl_pan_number                 = (AppiumBy.XPATH, "//android.view.View[@text='PAN Number *']")
    pan_text_field =  (AppiumBy.XPATH, "//android.widget.EditText[@index='5']")                # View · "PAN Number *"
    btn_confirm_payment            = (AppiumBy.XPATH, "//android.widget.Button[@text='Confirm Payment']")  # Button · "Confirm Payment"
