"""
rearch_locators_generated.py
----------------------------
AUTO-GENERATED by Tools/rearch_xpath_extractor.py
Generated : 2026-03-12 18:56
Source    : uiautomator XML dumps (NATIVE_APP context)
Package   : com.razorpay.pos

!! REVIEW BEFORE USE !!
- Rename / remove duplicates
- Confirm each locator by running a quick find_element test
- Merge reviewed entries into PageFactory/ReArch/rearch_native_locators.py
"""

from appium.webdriver.common.appiumby import AppiumBy

REARCH_PACKAGE = "com.razorpay.pos"



# ════════════════════════════════════════════════════════════════════════════
# catalog
# ════════════════════════════════════════════════════════════════════════════

class catalog:
    """Auto-generated from uiautomator dump — review and adjust as needed."""
    lbl_view                       = (AppiumBy.XPATH, "//android.view.View[@index='0']")  # View
    lbl_page                       = (AppiumBy.ID, "page")  # View · [page]
    btn_button                     = (AppiumBy.XPATH, "//android.widget.Button[@index='0']")  # Button
    lbl_catalog                    = (AppiumBy.XPATH, "//android.widget.TextView[@text='Catalog']")  # TextView · "Catalog"
    btn_search_for_products        = (AppiumBy.XPATH, "//android.widget.Button[@text='Search for products...']")  # Button · "Search for products..."
    lbl_brands                     = (AppiumBy.XPATH, "//android.widget.TextView[@text='Brands']")  # TextView · "Brands"
    btn_brandui_brandui            = (AppiumBy.XPATH, "//android.widget.Button[@text='BRAND_UI BRAND_UI']")  # Button · "BRAND_UI BRAND_UI"
