import sys
import random
import time

import pytest
from datetime import datetime

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_order_details_page import ReArchOrderDetailsPage
from PageFactory.ReArch.rearch_payment_method_page import ReArchPaymentMethodPage
from PageFactory.ReArch.rearch_card_type_page import ReArchCardTypePage
from PageFactory.ReArch.rearch_complete_page import ReArchCompletePage
from PageFactory.ReArch.rearch_txn_history_page import ReArchTxnHistoryPage
from PageFactory.ReArch.rearch_txn_detail_page import ReArchTxnDetailPage
from PageFactory.ReArch.rearch_native_locators import TxnHistoryLocators, ReleasePreAuthLocators
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
    Validator, date_time_converter, receipt_validator,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.apiVal
@pytest.mark.appVal
def test_common_rearch_0046():
    """
    Sub Feature Code: UI_ReArch_PM_Card_PreAuth_Release_HDFC_DUMMY
    Sub Feature Description:
        Launch ReArch app, enter amount (90-150), select Pre Auth via overlay,
        proceed through Order Details, select Visa Credit (EMV), verify success,
        navigate to txn details, click Release Pre-Auth → Yes, Release → Done,
        then search for same txn and validate status as "Payment Released Pre-Auth".

    NL Source Steps:
      Preconditions:
        - Apply org_settings (cardPaymentEnabled, preAuthOption=1, etc.)
        - Do NOT revert settings on cleanup

      Test Steps:
        1.  launch rearch app and login if present
        2.  apply preconditions settings (refresh via Payment History)
        3.  wait for home page
        4.  enter amount from 90 to 150
        5.  click on overlay button (⋯)
        6.  click on proceed (Order Details)
        7.  click on Pre Auth
        8.  click on Visa Credit (EMV)
        9.  click on Accept more payment
        10. navigate to latest txn
        11. click on "Release Pre-Auth" button
        12. click on "Yes, Release"
        13. wait until Done button is visible
        14. click on Done button
        15. use same txn id and navigate to txn and do app validation
            status should be "Payment Released Pre-Auth"
        16. do api validation

    Generated by: test_generator.md, action_registry.yaml
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # ══════════════════════════════════════════════════════════════
        # SETUP
        # ══════════════════════════════════════════════════════════════
        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        # ── Preconditions (DO NOT REVERT) ─────────────────────────────────
        logger.info(f"Starting Precondition setup for the test case: {testcase_id}")

        api_details = DBProcessor.get_api_details('org_settings_update', request_body={
            "username": portal_username,
            "password": portal_password,
            "entityName": "org",
            "settingForOrgCode": org_code,
        })
        settings = api_details["RequestBody"]["settings"]
        settings["autoLoginByTokenEnabled"] = "true"
        settings["enableDemandDraftDD"] = "true"
        settings["preAuthOption"] = "1"
        settings["cardPaymentEnabled"] = "true"
        settings["enableWebAppRevamp"] = "true"
        settings["p2pEnabled"] = "true"
        settings["mqttEnabled"] = "true"
        settings["cashPaymentEnabled"] = "true"
        settings["addlAuthReqdForCash"] = "false"
        settings["orderNumberInputEnabled"] = "true"
        settings["customerAuthDataCaptureEnabled"] = "true"
        settings["chequePaymentEnabled"] = "true"
        settings["amountCutOffForCustomerAuth"] = "10000"
        settings["eSignatureForNonCardEnabled"] = "false"
        settings["brandingInfo"] = ""
        logger.debug(f"Precondition API details: {api_details}")
        response = APIProcessor.send_request(api_details=api_details)
        logger.debug(f"Precondition response: {response}")

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed Precondition setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=True, portalLog=False, cnpwareLog=False,
            middlewareLog=True, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # ══════════════════════════════════════════════════════════════
        # EXECUTION
        # ══════════════════════════════════════════════════════════════
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            amount = str(random.randint(90, 150))
            order_id = f"{datetime.now().strftime('%m%d%H%M%S')}{testcase_id[-4:]}"
            logger.debug(f"amount={amount}, order_id={order_id}")

            # Step 1: Launch ReArch app and login if present
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login flow handled")

            # Step 2-3: Initial home screen → Collect Payment → amount screen
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_collect_payment()
            home_page.wait_for_home_page_load()

            # Settings refresh: navigate to Payment History, wait for Dashboard, then back
            home_page.click_txn_history()
            txn_history_page = ReArchTxnHistoryPage(app_driver)
            txn_history_page.wait_for_txn_list()
            assert home_page.is_element_visible(TxnHistoryLocators.btn_my_dashboard, time=10), \
                "My Dashboard button should be visible on Payment History"
            logger.debug("Payment History loaded with Dashboard visible — settings refreshed")
            home_page.go_back()
            home_page.wait_for_home_page_load()
            logger.debug("Navigated back from Payment History")

            # Step 4: Enter amount
            home_page.enter_amount(amount)
            logger.debug(f"Amount {amount} entered")

            # Step 5: Click overlay button (⋯)
            home_page.click_more_payment_options()
            logger.debug("More Payment Options (⋯) tapped")

            # Step 6: Click Proceed on Order Details overlay
            order_details_page = ReArchOrderDetailsPage(app_driver)
            order_details_page.wait_for_order_details_screen()
            order_details_page.click_proceed()
            logger.debug("Order Details: clicked Proceed")

            # Step 7: Click Pre Auth from Payment Methods
            payment_method_page = ReArchPaymentMethodPage(app_driver)
            payment_method_page.wait_for_payment_methods()
            payment_method_page.click_pre_auth()
            logger.debug("Pre Auth selected from payment methods")

            # Step 8: Select Visa Credit (EMV)
            card_type_page = ReArchCardTypePage(app_driver)
            card_type_page.wait_for_card_type_screen()
            card_type_page.select_card_type("Visa Credit (EMV)")
            logger.debug("Selected Visa Credit (EMV)")

            # Wait for payment success screen
            complete_page = ReArchCompletePage(app_driver)
            complete_page.wait_for_success_screen()
            logger.info("Payment Successful screen confirmed")

            # Resolve txn from DB
            query = (
                f"select id, created_time, posting_date, rr_number, auth_code "
                f"from txn "
                f"where org_code='{org_code}' AND username='{app_username}' "
                f"AND payment_mode='CARD' "
                f"order by created_time desc limit 1;"
            )
            logger.debug(f"Query to resolve txn_id: {query}")
            result = DBProcessor.getValueFromDB(query)
            txn_id       = result["id"].values[0]
            created_time = result["created_time"].values[0]
            posting_date = result["posting_date"].values[0]
            rrn          = str(result["rr_number"].values[0])
            auth_code    = str(result["auth_code"].values[0])
            logger.debug(
                f"Resolved txn_id={txn_id}, created_time={created_time}, "
                f"posting_date={posting_date}, rrn={rrn}, auth_code={auth_code}"
            )

            # Step 9: Click Accept more payments → navigate to txn details
            complete_page.click_proceed_to_home()
            home_page.wait_for_home_page_load()
            home_page.click_txn_history()
            txn_history_page.wait_for_txn_list()

            # Step 10: Navigate to latest txn
            txn_history_page.click_on_transaction_by_txn_id(txn_id=txn_id)
            logger.debug("Navigated to txn detail page")

            # Step 11: Click Release Pre-Auth button
            txn_detail_page = ReArchTxnDetailPage(app_driver)
            txn_detail_page.click_release_pre_auth()
            logger.debug("Clicked Release Pre-Auth button")

            # Step 12: Click "Yes, Release"
            txn_detail_page.perform_click(ReleasePreAuthLocators.btn_yes_release)
            logger.debug("Clicked Yes, Release")

            # Step 13-14: Wait for Done button and click
            txn_detail_page.wait_for_element(ReleasePreAuthLocators.btn_done)
            txn_detail_page.perform_click(ReleasePreAuthLocators.btn_done)
            logger.debug("Clicked Done — Release Pre-Auth completed")

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in try block of testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # ══════════════════════════════════════════════════════════════
        # VALIDATION
        # ══════════════════════════════════════════════════════════════
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # ── App Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                date_and_time = date_time_converter.to_rearch_app_format(created_time)
                expected_app_values = {
                    "txn_status": "Payment Released Pre-Auth",
                    "txn_id":     txn_id,
                    "date":       date_and_time,
                    "amount":     amount,
                }
                logger.debug(f"expected_app_values: {expected_app_values}")

                # Step 15: Navigate to txn history → search for same txn
                # home_page.wait_for_home_page_load()
                # home_page.click_txn_history()
                # txn_history_page.wait_for_txn_list()
                txn_history_page.click_on_transaction_by_txn_id(txn_id=txn_id)

                txn_detail_page = ReArchTxnDetailPage(app_driver)

                # Fetch and assert transaction fields
                time.sleep(2)
                app_txn_id     = txn_detail_page.fetch_payment_id()
                app_txn_status = txn_detail_page.fetch_status(amount)
                app_date_time  = txn_detail_page.fetch_date_time()
                app_amount     = txn_detail_page.fetch_amount(amount)
                logger.info(
                    f"App txn_id={app_txn_id}, date_time={app_date_time}, "
                    f"app_txn_status={app_txn_status}, app_amount={app_amount}"
                )

                actual_app_values = {
                    "txn_status": app_txn_status,
                    "txn_id":     app_txn_id,
                    "date":       app_date_time,
                    "amount":     app_amount,
                }
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

                assert app_txn_id, "Payment ID should not be empty"
                assert app_date_time, "Date & Time should not be empty"

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        # ── API Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "api_validation") == "True":
            logger.info(f"Started API validation for the test case: {testcase_id}")
            try:
                date = date_time_converter.db_datetime(created_time)
                expected_api_values = {
                    "pmt_status":    "REL_PRE_AUTH",  # TODO: verify on first run — may be VOIDED or RELEASED
                    "txn_amt":       float(amount),
                    "pmt_mode":      "CARD",
                    "pmt_state":     "VOIDED",  # TODO: verify on first run
                    "txn_type":      "PRE_AUTH",  # TODO: verify on first run
                    "acquirer_code": "HDFC",      # TODO: verify for DUMMY
                    "issuer_code":   "HDFC",      # TODO: verify for DUMMY
                    "org_code":      org_code,
                    "rrn":           rrn,
                    "date":          date,
                    "pmt_card_brand": "VISA",
                    "pmt_card_type":  "CREDIT",
                    "card_txn_type":  "EMV",
                }
                logger.debug(f"expected_api_values: {expected_api_values}")

                api_details = DBProcessor.get_api_details(
                    "txnlist",
                    request_body={"username": app_username, "password": app_password},
                )
                response = APIProcessor.send_request(api_details)
                logger.debug("txnlist API response received")

                txn_data = next(
                    (x for x in response["txns"] if x["txnId"] == txn_id), None
                )
                if txn_data is None:
                    raise ValueError(f"txn_id '{txn_id}' not found in txnlist API response")
                logger.debug(f"Filtered txn entry from txnlist: {txn_data}")

                actual_api_values = {
                    "pmt_status":    txn_data["status"],
                    "txn_amt":       float(txn_data["amount"]),
                    "pmt_mode":      txn_data["paymentMode"],
                    "pmt_state":     txn_data["states"][0],
                    "txn_type":      txn_data["txnType"],
                    "acquirer_code": txn_data["acquirerCode"],
                    "issuer_code":   txn_data["issuerCode"],
                    "org_code":      txn_data["orgCode"],
                    "rrn":           str(txn_data["rrNumber"]),
                    "date":          date_time_converter.from_api_to_datetime_format(
                                         txn_data["createdTime"]
                                     ),
                    "pmt_card_brand": txn_data["paymentCardBrand"],
                    "pmt_card_type":  txn_data["paymentCardType"],
                    "card_txn_type":  txn_data["cardTxnTypeDesc"],
                }
                logger.debug(f"actual_api_values: {actual_api_values}")
                Validator.validationAgainstAPI(
                    expectedAPI=expected_api_values, actualAPI=actual_api_values
                )

            except Exception as e:
                Configuration.perform_api_val_exception(testcase_id, e)
            logger.info(f"Completed API validation for the test case: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        # No settings revert — as per user instruction
        Configuration.executeFinallyBlock(testcase_id)
