import sys
import random
import time

import pytest
from datetime import datetime

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_order_details_page import ReArchOrderDetailsPage
from PageFactory.ReArch.rearch_payment_method_page import ReArchPaymentMethodPage
from PageFactory.ReArch.rearch_demand_draft_page import ReArchDemandDraftPage
from PageFactory.ReArch.rearch_complete_page import ReArchCompletePage
from PageFactory.ReArch.rearch_txn_history_page import ReArchTxnHistoryPage
from PageFactory.ReArch.rearch_txn_detail_page import ReArchTxnDetailPage
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
    Validator, date_time_converter, receipt_validator,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.apiVal
@pytest.mark.appVal
@pytest.mark.chargeSlipVal
def test_common_rearch_0022():
    """
    Sub Feature Code: UI_ReArch_PM_DD_Success_HDFC
    Sub Feature Description:
        Launch ReArch app, handle login if required, enter a random amount (500-600),
        navigate via ⋯ → Order Details → Proceed → Payment Methods overlay →
        scroll down → Demand Draft → fill DD form (DD number, bank, branch name, date) →
        Confirm Payment → verify Payment Successful screen, then validate via
        App (TxnHistory → TxnDetail), API (txnlist), and Charge Slip.

    NL Source Steps:
      Preconditions:
        1. update org_settings with multiple keys (see preconditions block)
        NOTE: preconditions are NOT reverted in the finally block

      Test Steps:
        1.  launch rearch app and login if present
        2.  click on collect payment
        3.  enter any amount between 500 to 600
        4.  click on overlay button (⋯ More Payment Options)
        5.  click on proceed button on order details screen
        6.  scroll down and click on Demand Draft button
        7.  click on Enter DD Number field and enter random 6 digit number
        8.  click on Select Bank → select Pallavan Gramma Bank → click Apply
        9.  click on Enter Branch Name and enter Branch_1
        10. click on dd/mm/yyyy date button → click Apply
        11. click on Confirm Payment
        12. do app, api and chargeslip validation

    Generated by: test_generator.md
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # ── Setup ──────────────────────────────────────────────────────────────
        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        # ── PreConditions ──────────────────────────────────────────────────────
        logger.info(f"Starting Precondition setup for the test case: {testcase_id}")

        api_details = DBProcessor.get_api_details('org_settings_update', request_body={
            "username": portal_username,
            "password": portal_password,
            "entityName": "org",
            "settingForOrgCode": org_code,
        })
        settings = api_details["RequestBody"]["settings"]
        settings["autoLoginByTokenEnabled"] = "true"
        settings["enableDemandDraftDD"] = "true"
        settings["preAuthOption"] = "1"
        settings["cardPaymentEnabled"] = "true"
        settings["enableWebAppRevamp"] = "true"
        settings["p2pEnabled"] = "true"
        settings["mqttEnabled"] = "true"
        settings["cashPaymentEnabled"] = "true"
        settings["addlAuthReqdForCash"] = "false"
        settings["orderNumberInputEnabled"] = "true"
        settings["customerAuthDataCaptureEnabled"] = "true"
        settings["chequePaymentEnabled"] = "true"
        settings["amountCutOffForCustomerAuth"] = "10000"
        settings["eSignatureForNonCardEnabled"] = "false"
        settings["brandingInfo"] = ""
        logger.debug(f"Precondition API details: {api_details}")
        response = APIProcessor.send_request(api_details=api_details)
        logger.debug(f"Precondition response: {response}")

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed Precondition setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=True, portalLog=False, cnpwareLog=False,
            middlewareLog=True, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # ── Test Execution ─────────────────────────────────────────────────────
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            amount = str(random.randint(500, 600))
            display_amount = f"{int(amount):,}.00"
            dd_number = str(random.randint(100000, 999999))
            logger.debug(f"amount={amount}, dd_number={dd_number}")

            # Step 1: Launch ReArch app and handle login if required
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login flow handled")

            # Step 2: Wait for initial home screen and tap Collect Payment
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_collect_payment()
            logger.debug("Collect Payment tapped")

            # Step 3: Wait for amount screen and enter amount
            home_page.wait_for_home_page_load()
            home_page.enter_amount(amount)
            logger.debug(f"Amount {amount} entered")

            # Step 4: Tap ⋯ (More Payment Options / overlay button)
            home_page.click_more_payment_options()
            logger.debug("More Payment Options (⋯) tapped")

            # Step 5: Wait for Order Details overlay → click Proceed
            order_details_page = ReArchOrderDetailsPage(app_driver)
            order_details_page.wait_for_order_details_screen()
            order_details_page.click_proceed()
            logger.debug("Order Details: clicked Proceed")

            # Step 6: Wait for Payment Method overlay → scroll down → click Demand Draft
            payment_method_page = ReArchPaymentMethodPage(app_driver)
            payment_method_page.wait_for_payment_methods()
            payment_method_page.scroll_to_text("Demand Draft")
            payment_method_page.click_demand_draft()
            logger.debug("Demand Draft selected from payment methods")

            # Step 7: Enter DD number
            dd_page = ReArchDemandDraftPage(app_driver)
            dd_page.wait_for_dd_form()
            dd_page.enter_dd_number(dd_number)
            logger.debug(f"DD number {dd_number} entered")
            home_page.go_back()

            # Step 8: Select Bank → Pallavan Gramma Bank → Apply
            dd_page.click_select_bank()
            dd_page.select_bank("Pallavan Gramma Bank")
            dd_page.click_apply()
            logger.debug("Bank selected: Pallavan Gramma Bank")

            # Step 9: Enter Branch Name
            dd_page.enter_branch_name("Branch_1")
            logger.debug("Branch name entered: Branch_1")
            home_page.go_back()

            # Step 10: Click date picker (dd/mm/yyyy) → Apply (accepts default/today)
            dd_page.click_date_picker()
            dd_page.click_apply()
            logger.debug("DD date selected (default)")

            # Step 11: Click Confirm Payment
            dd_page.click_confirm_payment()
            logger.debug("Demand Draft payment confirmed")

            # Verify payment success screen
            complete_page = ReArchCompletePage(app_driver)
            complete_page.wait_for_success_screen()
            logger.info("Payment Successful screen confirmed")

            # Accept more payments → back to home screen
            complete_page.click_proceed_to_home()
            logger.debug("Clicked Accept More Payments")

            # Resolve txn from DB
            query = (
                f"select id, created_time, posting_date "
                f"from txn "
                f"where org_code='{org_code}' AND username='{app_username}' "
                f"AND payment_mode='DD' "  # TODO: verify payment_mode value on first run (DD or DEMAND_DRAFT)
                f"order by created_time desc limit 1;"
            )
            logger.debug(f"Query to resolve txn_id: {query}")
            result = DBProcessor.getValueFromDB(query)
            txn_id       = result["id"].values[0]
            created_time = result["created_time"].values[0]
            posting_date = result["posting_date"].values[0]
            logger.debug(
                f"Resolved txn_id={txn_id}, created_time={created_time}, "
                f"posting_date={posting_date}"
            )

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # ── Validation ─────────────────────────────────────────────────────────
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # ── App Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                date_and_time = date_time_converter.to_rearch_app_format(created_time)
                expected_app_values = {
                    "txn_status": "Payment Authorized",  # TODO: verify exact label for DD on first run
                    "txn_id":     txn_id,
                    "date":       date_and_time,
                    "amount":     display_amount,
                }
                logger.debug(f"expected_app_values: {expected_app_values}")

                # Navigate to TxnDetail via txn_id search
                home_page.wait_for_home_page_load()
                home_page.click_txn_history()

                txn_history_page = ReArchTxnHistoryPage(app_driver)
                txn_history_page.wait_for_txn_list()
                txn_history_page.click_on_transaction_by_txn_id(txn_id=txn_id)

                txn_detail_page = ReArchTxnDetailPage(app_driver)

                # Fetch and assert transaction fields
                time.sleep(2)
                app_txn_id     = txn_detail_page.fetch_payment_id()
                app_txn_status = txn_detail_page.fetch_status(display_amount)
                app_date_time  = txn_detail_page.fetch_date_time()
                app_amount     = txn_detail_page.fetch_amount(display_amount)
                logger.info(
                    f"App txn_id={app_txn_id}, date_time={app_date_time}, "
                    f"app_txn_status={app_txn_status}, app_amount={app_amount}"
                )

                actual_app_values = {
                    "txn_status": app_txn_status,
                    "txn_id":     app_txn_id,
                    "date":       app_date_time,
                    "amount":     app_amount,
                }
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

                assert app_txn_id, "Payment ID should not be empty"
                assert app_date_time, "Date & Time should not be empty"

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        # ── API Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "api_validation") == "True":
            logger.info(f"Started API validation for the test case: {testcase_id}")
            try:
                date = date_time_converter.db_datetime(created_time)
                expected_api_values = {
                    "pmt_status":    "AUTHORIZED",    # TODO: verify on first run
                    "txn_amt":       float(amount),
                    "pmt_mode":      "DD",             # TODO: verify on first run (DD or DEMAND_DRAFT)
                    "txn_type":      "CHARGE",
                    "acquirer_code": "NONE",           # TODO: verify on first run
                    "org_code":      org_code,
                    "date":          date,
                }
                logger.debug(f"expected_api_values: {expected_api_values}")

                api_details = DBProcessor.get_api_details(
                    "txnlist",
                    request_body={"username": app_username, "password": app_password},
                )
                response = APIProcessor.send_request(api_details)
                logger.debug("txnlist API response received")

                txn_data = next(
                    (x for x in response["txns"] if x["txnId"] == txn_id), None
                )
                if txn_data is None:
                    raise ValueError(f"txn_id '{txn_id}' not found in txnlist API response")
                logger.debug(f"Filtered txn entry from txnlist: {txn_data}")

                actual_api_values = {
                    "pmt_status":    txn_data["status"],
                    "txn_amt":       float(txn_data["amount"]),
                    "pmt_mode":      txn_data["paymentMode"],
                    "txn_type":      txn_data["txnType"],
                    "acquirer_code": txn_data["acquirerCode"],
                    "org_code":      txn_data["orgCode"],
                    "date":          date_time_converter.from_api_to_datetime_format(
                                         txn_data["createdTime"]
                                     ),
                }
                logger.debug(f"actual_api_values: {actual_api_values}")
                Validator.validationAgainstAPI(
                    expectedAPI=expected_api_values, actualAPI=actual_api_values
                )

            except Exception as e:
                Configuration.perform_api_val_exception(testcase_id, e)
            logger.info(f"Completed API validation for the test case: {testcase_id}")

        # ── Charge Slip Validation ────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "charge_slip_validation") == "True":
            logger.info(f"Started ChargeSlip validation for the test case: {testcase_id}")
            try:
                txn_date, txn_time = date_time_converter.to_chargeslip_format(posting_date_db=created_time)
                expected_charge_slip_values = {
                    "PAID BY:":     "DD",              # TODO: verify on first run (DD or DEMAND DRAFT)
                    "BASE AMOUNT:": f"Rs.{int(amount):,}.00",
                    "date":         txn_date,
                    "time":         txn_time,
                }
                logger.debug(f"expected_charge_slip_values: {expected_charge_slip_values}")
                receipt_validator.perform_charge_slip_validations(
                    txn_id=txn_id,
                    credentials={"username": app_username, "password": app_password},
                    expected_details=expected_charge_slip_values,
                )

            except Exception as e:
                Configuration.perform_charge_slip_val_exception(testcase_id, e)
            logger.info(f"Completed ChargeSlip validation for the test case: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        # NOTE: Preconditions are intentionally NOT reverted here
        Configuration.executeFinallyBlock(testcase_id)
