import sys
import time
import random

import pytest
from appium.webdriver.common.appiumby import AppiumBy
from datetime import datetime

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_order_details_page import ReArchOrderDetailsPage
from PageFactory.ReArch.rearch_payment_method_page import ReArchPaymentMethodPage
from PageFactory.ReArch.rearch_emi_page import ReArchEMIPage
from PageFactory.ReArch.rearch_card_type_page import ReArchCardTypePage
from PageFactory.ReArch.rearch_complete_page import ReArchCompletePage
from PageFactory.ReArch.rearch_txn_history_page import ReArchTxnHistoryPage
from PageFactory.ReArch.rearch_txn_detail_page import ReArchTxnDetailPage
from PageFactory.ReArch.rearch_native_locators import TxnHistoryLocators
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
    Validator, date_time_converter, receipt_validator,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.apiVal
@pytest.mark.appVal
@pytest.mark.chargeSlipVal
def test_common_rearch_0052():
    """
    Sub Feature Code: UI_ReArch_PM_BrandEMI_Credit_Success_BOB
    Sub Feature Description:
        Launch ReArch app, login, refresh settings via Payment History,
        navigate to Catalog, select BRAND_UI brand and Product1 (₹6,000),
        proceed to EMI via BOB Bank Credit Card, select 3-month tenure,
        verify breakup (Order Total ₹6,000, Interest +₹120.39,
        Total ₹6,120.39), enter random 6-digit IMEI, proceed through
        card type selection (Visa Credit EMV), verify success, then
        validate via App, API, and Charge Slip.

    NL Source Steps:
      Preconditions:
        1.  update org_settings: autoLoginByTokenEnabled = false
        2.  update org_settings: enableDemandDraftDD = true
        3.  update org_settings: preAuthOption = 1
        4.  update org_settings: cardPaymentEnabled = true
        5.  update org_settings: enableWebAppRevamp = true
        6.  update org_settings: p2pEnabled = true
        7.  update org_settings: mqttEnabled = true
        8.  update org_settings: cashPaymentEnabled = true
        9.  update org_settings: addlAuthReqdForCash = false
        10. update org_settings: orderNumberInputEnabled = true
        11. update org_settings: customerAuthDataCaptureEnabled = true
        12. update org_settings: chequePaymentEnabled = true
        13. update org_settings: amountCutOffForCustomerAuth = 10000
        14. update org_settings: eSignatureForNonCardEnabled = false
        15. update org_settings: brandingInfo = ""
        16. update org_settings: businessDiscountEnabled = true
        17. update org_settings: boProductsEnabled = true
        18. update org_settings: boCashbackEnabled = true
        19. update org_settings: boInstantDiscountEnabled = true

      Test Steps:
        1.  launch rearch app and login if present
        2.  apply preconditions settings (refresh via Payment History)
        3.  wait for home page
        4.  click on back button
        5.  click on catalog
        6.  click on brand_ui
        7.  click on product_1 (₹6,000)
        8.  click on proceed button
        9.  wait until bank button is visible
        10. click on btn_bob_bank_credit_card
        11. click on 3 month tenure
        12. click on view breakup
        13. verify Order Total = ₹6,000, Interest = +₹120.39, Total = ₹6,120.39
        14. click on back button
        15. click on Proceed button
        16. tap and enter random 6 digit IMEI number
        17. click on proceed button
        18. click on proceed button
        19. select Visa Credit(EMV)
        20. click on Accept more payment
        21. validate app, api and chargeslip

    Generated by: test_generator.md, action_registry.yaml
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # -- Setup --
        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        # -- PreConditions --
        logger.info(f"Starting Precondition setup for the test case: {testcase_id}")

        api_details = DBProcessor.get_api_details('org_settings_update', request_body={
            "username": portal_username,
            "password": portal_password,
            "entityName": "org",
            "settingForOrgCode": org_code,
        })
        settings = api_details["RequestBody"]["settings"]
        settings["autoLoginByTokenEnabled"] = "true"
        settings["enableDemandDraftDD"] = "true"
        settings["preAuthOption"] = "1"
        settings["cardPaymentEnabled"] = "true"
        settings["enableWebAppRevamp"] = "true"
        settings["p2pEnabled"] = "true"
        settings["mqttEnabled"] = "true"
        settings["cashPaymentEnabled"] = "true"
        settings["addlAuthReqdForCash"] = "false"
        settings["orderNumberInputEnabled"] = "true"
        settings["customerAuthDataCaptureEnabled"] = "true"
        settings["chequePaymentEnabled"] = "true"
        settings["amountCutOffForCustomerAuth"] = "10000"
        settings["eSignatureForNonCardEnabled"] = "false"
        settings["brandingInfo"] = ""
        settings["businessDiscountEnabled"] = "true"
        settings["boProductsEnabled"] = "true"
        settings["boCashbackEnabled"] = "true"
        settings["boInstantDiscountEnabled"] = "true"
        logger.debug(f"Precondition API details: {api_details}")
        response = APIProcessor.send_request(api_details=api_details)
        logger.debug(f"Precondition response: {response}")

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed Precondition setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=True, portalLog=False, cnpwareLog=False,
            middlewareLog=True, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # -- Test Execution --
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")
            amount = "6000"
            amount_formatted = "\u20b96,000"
            logger.debug(f"amount={amount}, amount_formatted={amount_formatted}")

            # Step 1: Launch ReArch app and handle login
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login flow handled")

            # Step 2: Navigate to home, then refresh settings via Payment History
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_collect_payment()
            home_page.wait_for_home_page_load()

            # Refresh settings
            home_page.click_txn_history()
            txn_history_page = ReArchTxnHistoryPage(app_driver)
            txn_history_page.wait_for_txn_list()
            home_page.wait_for_element(TxnHistoryLocators.btn_my_dashboard, time=10)
            home_page.go_back()
            logger.debug("Settings refreshed via Payment History navigation")

            # Step 3: Wait for home page
            home_page.wait_for_home_page_load()
            logger.debug("Home page ready after settings refresh")

            # Step 4: Click back button to go to initial home screen
            home_page.go_back()
            home_page.wait_for_initial_home_screen()
            logger.debug("Back to initial home screen")

            # Step 5: Click on Catalog
            login_page.perform_click(
                (AppiumBy.XPATH, "//android.widget.Button[@text='Catalog']")  # TODO: verify exact text on first run
            )
            logger.debug("Clicked Catalog")

            # Step 6: Click on BRAND_UI brand
            time.sleep(2)  # TODO: adjust wait for catalog page load
            login_page.perform_click(
                (AppiumBy.XPATH, "//android.widget.Button[@text='BRAND_UI BRAND_UI']")
            )
            logger.debug("Clicked BRAND_UI brand")

            # Step 7: Click on Product1 (₹6,000)
            time.sleep(2)  # TODO: adjust wait for product list load
            login_page.perform_click(
                (AppiumBy.XPATH, "//android.widget.Button[@text='BRAND_UI Brand_UI_Product1 738749 \u20b96,000']")
            )
            logger.debug("Clicked Product1 (₹6,000)")

            # Step 8: Click Proceed on Order Details
            order_details_page = ReArchOrderDetailsPage(app_driver)
            # order_details_page.wait_for_order_details_screen()
            order_details_page.click_proceed()
            logger.debug("Order Details: clicked Proceed")

            # Step 9: Wait until Bank button is visible
            emi_page = ReArchEMIPage(app_driver)
            emi_page.wait_for_bank_button()
            logger.debug("Bank button visible on EMI screen")

            # Step 10: Click BOB Bank Credit Card
            emi_page.click_bob_bank_credit_card()
            logger.debug("BOB Bank Credit Card selected")

            # Step 11: Click 3-month tenure (BOB)
            emi_page.click_bob_3m_plan()
            logger.debug("BOB 3-month EMI plan selected")

            # Step 12: Click View Breakup
            emi_page.click_view_breakup()
            logger.debug("View Breakup opened")

            # Step 13: Fetch breakup values for validation (no asserts here)
            actual_order_total = emi_page.fetch_order_total()
            actual_interest = emi_page.fetch_interest_charged()
            actual_total_amount = emi_page.fetch_total_amount()
            logger.info(f"Breakup — Order Total: {actual_order_total}, "
                        f"Interest: {actual_interest}, "
                        f"Total Amount: {actual_total_amount}")

            # Step 14: Click back button (close breakup sheet)
            emi_page.go_back()
            logger.debug("Back from breakup sheet")

            # Step 15: Click Proceed on EMI screen
            emi_page.click_proceed()
            logger.debug("EMI: clicked Proceed")

            # Step 16: Enter random 6-digit IMEI number
            imei_number = str(random.randint(100000, 999999))
            order_details_page.enter_device_serial(imei_number)
            logger.debug(f"IMEI entered: {imei_number}")

            # Step 17: Click Proceed on Order Details
            order_details_page.click_proceed()
            logger.debug("Order Details: clicked Proceed (with IMEI)")

            # Step 18: Click Proceed (second proceed)
            # order_details_page.wait_for_order_details_screen()
            order_details_page.click_proceed()
            logger.debug("Order Details: clicked Proceed (second)")

            # Step 19: Select Visa Credit (EMV)
            card_type_page = ReArchCardTypePage(app_driver)
            card_type_page.wait_for_card_type_screen()
            card_type_page.select_card_type("Visa Credit (EMV)")
            logger.debug("Selected Visa Credit (EMV)")

            # Verify payment success
            complete_page = ReArchCompletePage(app_driver)
            complete_page.wait_for_success_screen()
            logger.info("Payment Successful screen confirmed")

            # Resolve txn from DB
            query = (
                f"select id, created_time, posting_date, rr_number, auth_code "
                f"from txn "
                f"where org_code='{org_code}' AND username='{app_username}' "
                f"AND payment_mode='CARD' "  # TODO: verify if EMI has separate payment_mode
                f"order by created_time desc limit 1;"
            )
            logger.debug(f"Query to resolve txn_id: {query}")
            result = DBProcessor.getValueFromDB(query)
            txn_id       = result["id"].values[0]
            created_time = result["created_time"].values[0]
            posting_date = result["posting_date"].values[0]
            rrn          = str(result["rr_number"].values[0])
            auth_code    = str(result["auth_code"].values[0])
            logger.debug(
                f"Resolved txn_id={txn_id}, created_time={created_time}, "
                f"posting_date={posting_date}, rrn={rrn}, auth_code={auth_code}"
            )

            # Step 20: Click Accept More Payments
            complete_page.click_proceed_to_home()
            logger.debug("Clicked Accept More Payments")

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # -- Validation --
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # -- App Validation (EMI breakup + TxnDetail) --
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                # EMI Breakup verification
                expected_breakup_values = {
                    "order_total": "\u20b96,000",
                    "interest_charged": "+\u20b9120.39",
                    "total_amount": "\u20b96,120.39",
                }
                actual_breakup_values = {
                    "order_total": actual_order_total,
                    "interest_charged": actual_interest,
                    "total_amount": actual_total_amount,
                }
                logger.debug(f"expected_breakup_values: {expected_breakup_values}")
                logger.debug(f"actual_breakup_values: {actual_breakup_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_breakup_values, actualApp=actual_breakup_values
                )

                # TxnDetail validation via Payment History
                date_and_time = date_time_converter.to_rearch_app_format(created_time)
                expected_app_values = {
                    "txn_status": "Payment Authorized",  # TODO: verify exact label for EMI on first run
                    "txn_id":     txn_id,
                    "date":       date_and_time,
                    "amount":     f"{int(amount):,}",
                }
                logger.debug(f"expected_app_values: {expected_app_values}")

                # Navigate to Payment History from Collect Payment page
                home_page.wait_for_initial_home_screen()
                home_page.click_collect_payment()
                home_page.wait_for_home_page_load()
                home_page.click_txn_history()

                txn_history_page.wait_for_txn_list()
                txn_history_page.click_on_transaction_by_txn_id(txn_id=txn_id)

                txn_detail_page = ReArchTxnDetailPage(app_driver)
                app_txn_id     = txn_detail_page.fetch_payment_id()
                app_txn_status = txn_detail_page.fetch_status("6,000")
                app_date_time  = txn_detail_page.fetch_date_time()
                app_amount     = txn_detail_page.fetch_amount("6,000")
                logger.info(
                    f"App txn_id={app_txn_id}, date_time={app_date_time}, "
                    f"app_txn_status={app_txn_status}, app_amount={app_amount}"
                )

                actual_app_values = {
                    "txn_status": app_txn_status,
                    "txn_id":     app_txn_id,
                    "date":       app_date_time,
                    "amount":     app_amount,
                }
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        # -- API Validation --
        if ConfigReader.read_config("Validations", "api_validation") == "True":
            logger.info(f"Started API validation for the test case: {testcase_id}")
            try:
                date = date_time_converter.db_datetime(created_time)
                expected_api_values = {
                    "pmt_status":    "AUTHORIZED",
                    "txn_amt":       float(amount),
                    "pmt_mode":      "CARD",             # TODO: verify if EMI uses CARD or EMI
                    "txn_type":      "CHARGE",
                    "acquirer_code": "HDFC",              # TODO: verify acquirer_code for BOB EMI
                    "org_code":      org_code,
                    "rrn":           rrn,
                    "date":          date,
                    "pmt_card_brand": "VISA",
                    "pmt_card_type":  "CREDIT",
                    "card_txn_type":  "EMV",
                }
                logger.debug(f"expected_api_values: {expected_api_values}")

                api_details = DBProcessor.get_api_details(
                    "txnlist",
                    request_body={"username": app_username, "password": app_password},
                )
                response = APIProcessor.send_request(api_details)
                logger.debug("txnlist API response received")

                txn_data = next(
                    (x for x in response["txns"] if x["txnId"] == txn_id), None
                )
                if txn_data is None:
                    raise ValueError(f"txn_id '{txn_id}' not found in txnlist API response")
                logger.debug(f"Filtered txn entry from txnlist: {txn_data}")

                actual_api_values = {
                    "pmt_status":    txn_data["status"],
                    "txn_amt":       float(txn_data["amount"]),
                    "pmt_mode":      txn_data["paymentMode"],
                    "txn_type":      txn_data["txnType"],
                    "acquirer_code": txn_data["acquirerCode"],
                    "org_code":      txn_data["orgCode"],
                    "rrn":           str(txn_data["rrNumber"]),
                    "date":          date_time_converter.from_api_to_datetime_format(
                                         txn_data["createdTime"]
                                     ),
                    "pmt_card_brand": txn_data["paymentCardBrand"],
                    "pmt_card_type":  txn_data["paymentCardType"],
                    "card_txn_type":  txn_data["cardTxnTypeDesc"],
                }
                logger.debug(f"actual_api_values: {actual_api_values}")
                Validator.validationAgainstAPI(
                    expectedAPI=expected_api_values, actualAPI=actual_api_values
                )

            except Exception as e:
                Configuration.perform_api_val_exception(testcase_id, e)
            logger.info(f"Completed API validation for the test case: {testcase_id}")

        # -- Charge Slip Validation --
        if ConfigReader.read_config("Validations", "charge_slip_validation") == "True":
            logger.info(f"Started ChargeSlip validation for the test case: {testcase_id}")
            try:
                txn_date, txn_time = date_time_converter.to_chargeslip_format(posting_date_db=posting_date)
                expected_charge_slip_values = {
                    "RRN":          rrn,
                    "AUTH CODE":    auth_code,
                    "BASE AMOUNT:": "Rs." + f"{int(amount):,}" + ".00",
                    "date":         txn_date,
                    "time":         txn_time,
                }
                logger.debug(f"expected_charge_slip_values: {expected_charge_slip_values}")
                receipt_validator.perform_charge_slip_validations(
                    txn_id=txn_id,
                    credentials={"username": app_username, "password": app_password},
                    expected_details=expected_charge_slip_values,
                )

            except Exception as e:
                Configuration.perform_charge_slip_val_exception(testcase_id, e)
            logger.info(f"Completed ChargeSlip validation for the test case: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        # NOTE: Preconditions are intentionally NOT reverted here
        Configuration.executeFinallyBlock(testcase_id)
