import sys

import pytest

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_account_details_page import ReArchAccountDetailsPage
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
    Validator,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.appVal
def test_common_rearch_0033():
    """
    Sub Feature Code: UI_ReArch_Home_Verify_AccountDetails_HDFC
    Sub Feature Description:
        Launch ReArch app, handle login if required, navigate to Settings,
        click on org_code, and verify that MID, TID and app_username texts
        are present on the account details screen.

    NL Source Steps:
      Preconditions:
        1. update org_settings with multiple keys (see preconditions block)
        NOTE: preconditions are NOT reverted in the finally block

      Test Steps:
        1. launch rearch app and login if present
        2. click on settings
        3. click on org_code
        4. verify texts: MID, TID and app_username are present

    Generated by: test_generator.md
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # -- Setup --
        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        # -- PreConditions --
        logger.info(f"Starting Precondition setup for the test case: {testcase_id}")

        api_details = DBProcessor.get_api_details('org_settings_update', request_body={
            "username": portal_username,
            "password": portal_password,
            "entityName": "org",
            "settingForOrgCode": org_code,
        })
        settings = api_details["RequestBody"]["settings"]
        settings["autoLoginByTokenEnabled"] = "true"
        settings["enableDemandDraftDD"] = "true"
        settings["preAuthOption"] = "1"
        settings["cardPaymentEnabled"] = "true"
        settings["enableWebAppRevamp"] = "true"
        settings["p2pEnabled"] = "true"
        settings["mqttEnabled"] = "true"
        settings["cashPaymentEnabled"] = "true"
        settings["addlAuthReqdForCash"] = "false"
        settings["orderNumberInputEnabled"] = "true"
        settings["customerAuthDataCaptureEnabled"] = "true"
        settings["chequePaymentEnabled"] = "true"
        settings["amountCutOffForCustomerAuth"] = "10000"
        settings["eSignatureForNonCardEnabled"] = "false"
        settings["brandingInfo"] = ""
        settings["tipPercentage"] = "15"
        settings["multiTipPercentage"] = "6, 11, 16"
        logger.debug(f"Precondition API details: {api_details}")
        response = APIProcessor.send_request(api_details=api_details)
        logger.debug(f"Precondition response: {response}")

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed Precondition setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=True, portalLog=False, cnpwareLog=False,
            middlewareLog=True, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # -- Test Execution --
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            # Step 1: Launch ReArch app and handle login if required
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login flow handled")

            # Step 2: Wait for initial home screen and click Settings
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_settings()
            logger.debug("Settings tapped")

            # Step 3: Wait for account screen and click on org_code
            account_page = ReArchAccountDetailsPage(app_driver)
            # account_page.wait_for_account_screen()
            account_page.click_org_code(org_code)
            logger.debug(f"Clicked org_code: {org_code}")

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # -- Validation --
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # -- App Validation --
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                # Step 4: Verify MID, TID and app_username are present
                expected_app_values = {
                    "mid_label": "MID",
                    "tid_label": "TID",
                    "app_username": app_username,
                }
                logger.debug(f"expected_app_values: {expected_app_values}")

                mid_visible = str(account_page.is_mid_displayed())
                tid_visible = str(account_page.is_tid_displayed())
                username_visible = str(account_page.is_text_displayed(app_username))

                actual_app_values = {
                    "mid_label": "MID" if mid_visible == "True" else "NOT DISPLAYED",
                    "tid_label": "TID" if tid_visible == "True" else "NOT DISPLAYED",
                    "app_username": app_username if username_visible == "True" else "NOT DISPLAYED",
                }
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        # NOTE: Preconditions are intentionally NOT reverted here
        Configuration.executeFinallyBlock(testcase_id)
