import sys
import time
import pytest

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_order_details_page import ReArchOrderDetailsPage
from PageFactory.ReArch.rearch_payment_method_page import ReArchPaymentMethodPage
from PageFactory.ReArch.rearch_qr_page import ReArchQRPage
from PageFactory.ReArch.rearch_complete_page import ReArchCompletePage
from PageFactory.ReArch.rearch_txn_history_page import ReArchTxnHistoryPage
from PageFactory.ReArch.rearch_txn_detail_page import ReArchTxnDetailPage
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
    Validator, date_time_converter,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.apiVal
@pytest.mark.appVal
def test_common_rearch_0008():
    """
    Sub Feature Code: UI_ReArch_PM_BharatQR_Expiry_HDFC
    Sub Feature Description:
        Launch ReArch app, enter magic-number amount (51) that triggers a Bharat QR
        expiry callback from the HDFC PG simulator. Navigate via ⋯ → Order Details →
        Proceed → Payment Method overlay → Bharat QR → QR screen. Wait 10s for QR to
        register, cancel via back button; HDFC simulator sends expiry callback. Verify
        completion screen, then validate via App (TxnHistory → TxnDetail) and API
        (txnlist).
    TC naming code description:
        100: Payment Method, 103: BharatQR, 003: TC003

    NL Source Steps:
      Preconditions: (none — no org_settings_update needed for Bharat QR)

      Test Steps:
        1.  launch rearch app
        2.  login with credentials (already logged in — skipped)
        3.  wait for initial home screen
        4.  click collect payment
        5.  wait for home page
        6.  enter amount (51 — magic number for HDFC expiry simulator)
        7.  click on overlay button (⋯ beside UPI)
        8.  wait for order details screen
        9.  click proceed
        10. wait for payment methods
        11. click on BharatQR button
        12. wait for qr screen
        13. cancel payment (back → "Yes, Cancel" — HDFC simulator expiry callback)
        14. verify success screen
        15. click accept more payments

      App Validation:
        16. go to transaction history
        17. wait for transaction list
        18. click first transaction
        19. validate payment id is not empty
        20. validate txn status
        21. validate amount

      API Validation:
        23. txnlist API — pmt_status=EXPIRED, txn_amt, pmt_mode=BharatQR,
            txn_type=CHARGE, org_code, rrn, date
            (TODO: verify exact pmt_mode and whether rrn is populated for expiry in API response)

    Generated by: test_generator.md, action_registry.yaml
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed: {testcase_id}")

        # ── Reset Settings to Default ──────────────────────────────────────────
        logger.info(f"Reverting settings to default: {testcase_id}")

        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        # No org_settings_update preconditions needed for Bharat QR

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Setup complete: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=True, portalLog=False, cnpwareLog=False,
            middlewareLog=True, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended: {testcase_id}")

        # ── Test Execution ─────────────────────────────────────────────────────
        try:
            logger.info(f"Starting execution: {testcase_id}")
            GlobalVariables.time_calc.execution.start()

            amount = "51"  # Magic number for HDFC PG simulator expiry callback
            logger.debug(f"amount={amount}")

            # Steps 1-2: Launch ReArch app (already logged in — login skipped)
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)

            # Steps 3-4: Wait for initial home screen and tap Collect Payment
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_collect_payment()
            logger.debug("Collect Payment tapped")

            # Steps 5-6: Wait for amount screen and enter amount
            home_page.wait_for_home_page_load()
            home_page.enter_amount(amount)
            logger.debug(f"Amount {amount} entered")

            # Step 7: Tap ⋯ (more payment options) beside UPI
            home_page.click_more_payment_options()
            logger.debug("More Payment Options (⋯) tapped")

            # Steps 8-9: Order Details overlay → Proceed
            order_details_page = ReArchOrderDetailsPage(app_driver)
            order_details_page.wait_for_order_details_screen()
            order_details_page.click_proceed()
            logger.debug("Order Details: clicked Proceed")

            # Steps 10-11: Payment method overlay — scroll down → Bharat QR
            payment_method_page = ReArchPaymentMethodPage(app_driver)
            payment_method_page.wait_for_payment_methods()
            payment_method_page.click_bharat_qr()
            logger.debug("Bharat QR selected from payment methods")

            # Step 12: Wait for QR screen
            qr_page = ReArchQRPage(app_driver)
            qr_page.wait_for_qr_screen()
            logger.debug("QR screen confirmed")

            # Step 13: Wait for QR to register in backend, then trigger expiry via cancel
            # HDFC PG simulator sends expiry callback on "Yes, Cancel" for amount 51
            time.sleep(7)
            qr_page.cancel_payment()
            logger.debug("Cancel triggered — HDFC PG simulator expiry callback expected")

            # Step 14: Verify completion screen after expiry callback
            # TODO: verify actual screen shown for expiry flow on first run
            complete_page = ReArchCompletePage(app_driver)

            # Resolve txn from DB — no order_id used; fetch latest txn for this org
            # TODO: add AND payment_mode='<BQR_MODE>' filter once verified on first run
            query = (
                f"select id, created_time, rr_number "
                f"from txn "
                f"where org_code='{org_code}' AND username='{app_username}' "
                f"order by created_time desc limit 1;"
            )
            logger.debug(f"Query to resolve txn_id: {query}")
            result = DBProcessor.getValueFromDB(query)
            txn_id       = result["id"].values[0]
            created_time = result["created_time"].values[0]
            rrn          = str(result["rr_number"].values[0])
            logger.debug(f"Resolved txn_id={txn_id}, created_time={created_time}, rrn={rrn}")

            # Step 15: Accept more payments → back to amount screen
            complete_page.click_proceed_to_home()
            logger.debug("Clicked Accept More Payments")

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.info(f"Execution complete: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # ── Validation ─────────────────────────────────────────────────────────
        logger.info(f"Starting Validation: {testcase_id}")
        GlobalVariables.time_calc.validation.start()

        # ── App Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation: {testcase_id}")
            try:
                date_and_time = date_time_converter.to_rearch_app_format(created_time)
                expected_app_values = {
                    "txn_status": "Payment Expired",  # TODO: verify exact status label for expiry on first run
                    "txn_id":     txn_id,
                    "date":       date_and_time,
                    "amount":     amount,
                }
                logger.debug(f"expected_app_values: {expected_app_values}")

                # Navigate to TxnDetail
                home_page.wait_for_home_page_load()
                home_page.click_txn_history()

                txn_history_page = ReArchTxnHistoryPage(app_driver)
                txn_history_page.wait_for_txn_list()
                txn_history_page.click_on_transaction_by_txn_id(txn_id)

                txn_detail_page = ReArchTxnDetailPage(app_driver)

                # Fetch transaction fields
                # Expiry is a non-success flow: use fetch_date_time_failure (sibling index 1)
                # TODO: verify sibling index is correct for expiry status on first run
                app_txn_id     = txn_detail_page.fetch_payment_id()
                app_txn_status = txn_detail_page.fetch_status(amount)
                app_date_time  = txn_detail_page.fetch_date_time_failure()
                app_amount     = txn_detail_page.fetch_amount(amount)
                logger.info(
                    f"App txn_id={app_txn_id}, status={app_txn_status}, "
                    f"date_time={app_date_time}, amount={app_amount}"
                )

                actual_app_values = {
                    "txn_status": app_txn_status,
                    "txn_id":     app_txn_id,
                    "date":       app_date_time,
                    "amount":     app_amount,
                }
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

                assert app_txn_id, "Payment ID should not be empty"

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation: {testcase_id}")

        # ── API Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "api_validation") == "True":
            logger.info(f"Started API validation: {testcase_id}")
            try:
                date = date_time_converter.db_datetime(created_time)
                expected_api_values = {
                    "pmt_status": "EXPIRED",
                    "txn_amt":    float(amount),
                    "pmt_mode":   "BHARATQR",  # TODO: verify exact paymentMode in txnlist API
                    "txn_type":   "CHARGE",
                    "org_code":   org_code,         # TODO: verify rrn is populated for expiry txns
                    "date":       date,
                }
                logger.debug(f"expected_api_values: {expected_api_values}")

                api_details = DBProcessor.get_api_details(
                    "txnlist",
                    request_body={"username": app_username, "password": app_password},
                )
                response = APIProcessor.send_request(api_details)
                logger.debug("txnlist API response received")

                txn_data = next(
                    (x for x in response["txns"] if x["txnId"] == txn_id), None
                )
                if txn_data is None:
                    raise ValueError(f"txn_id '{txn_id}' not found in txnlist API response")
                logger.debug(f"Filtered txn entry from txnlist: {txn_data}")

                actual_api_values = {
                    "pmt_status": txn_data["status"],
                    "txn_amt":    float(txn_data["amount"]),
                    "pmt_mode":   txn_data["paymentMode"],
                    "txn_type":   txn_data["txnType"],
                    "org_code":   txn_data["orgCode"],
                    "date":       date_time_converter.from_api_to_datetime_format(
                                      txn_data["createdTime"]
                                  ),
                }
                logger.debug(f"actual_api_values: {actual_api_values}")
                Validator.validationAgainstAPI(
                    expectedAPI=expected_api_values, actualAPI=actual_api_values
                )

            except Exception as e:
                Configuration.perform_api_val_exception(testcase_id, e)
            logger.info(f"Completed API validation: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.info(f"Completed all validations: {testcase_id}")

    finally:
        # No precondition revert needed (no org_settings_update was applied)
        Configuration.executeFinallyBlock(testcase_id)
