import sys
import time

import pytest

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_account_details_page import ReArchAccountDetailsPage
from PageFactory.ReArch.rearch_txn_history_page import ReArchTxnHistoryPage
from PageFactory.ReArch.rearch_native_locators import TxnHistoryLocators, HomeScreen
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
    Validator,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.appVal
def test_common_rearch_0044():
    """
    Sub Feature Code: UI_ReArch_Home_Verify_RelaunchAfterCacheDelete_HDFC
    Sub Feature Description:
        Launch ReArch app, apply preconditions (refresh via Payment History),
        navigate back to initial home screen, open Settings, delete cache &
        relaunch, handle login (select env screen), click Settings again,
        scroll down and click Relaunch App, then verify Collect Payment
        button is visible.

    NL Source Steps:
      Preconditions:
        - Apply org_settings (autoLoginByTokenEnabled=false, etc.)
        - Revert autoLoginByTokenEnabled=true on cleanup

      Test Steps:
        1.  launch rearch app and login if present
        2.  apply preconditions settings (refresh via Payment History)
        3.  wait for home page
        4.  click on back button
        5.  click on settings
        6.  scroll down and click on "Delete Cache & Relaunch App"
        7.  tap on "Yes, Delete & Relaunch"
        9.  handle login (it will land on select env screen)
        10. click on settings button
        11. scroll down and click on "Relaunch App"
        12. wait until collect payment button is visible

      App Validation:
        13. Verify collect payment button is visible

    Generated by: test_generator.md, action_registry.yaml
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # ══════════════════════════════════════════════════════════════
        # SETUP
        # ══════════════════════════════════════════════════════════════
        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        # ── Preconditions (org_settings_update) ───────────────────────────
        logger.info(f"Starting Precondition setup for the test case: {testcase_id}")

        api_details = DBProcessor.get_api_details('org_settings_update', request_body={
            "username": portal_username,
            "password": portal_password,
            "entityName": "org",
            "settingForOrgCode": org_code,
        })
        settings = api_details["RequestBody"]["settings"]
        settings["autoLoginByTokenEnabled"] = "false"
        settings["enableDemandDraftDD"] = "true"
        settings["preAuthOption"] = "1"
        settings["cardPaymentEnabled"] = "true"
        settings["enableWebAppRevamp"] = "true"
        settings["p2pEnabled"] = "true"
        settings["mqttEnabled"] = "true"
        settings["cashPaymentEnabled"] = "true"
        settings["addlAuthReqdForCash"] = "false"
        settings["orderNumberInputEnabled"] = "true"
        settings["customerAuthDataCaptureEnabled"] = "true"
        settings["chequePaymentEnabled"] = "true"
        settings["amountCutOffForCustomerAuth"] = "10000"
        settings["eSignatureForNonCardEnabled"] = "false"
        settings["brandingInfo"] = ""
        settings["businessDiscountEnabled"] = "true"
        settings["boProductsEnabled"] = "true"
        settings["boCashbackEnabled"] = "true"
        settings["boInstantDiscountEnabled"] = "true"
        logger.debug(f"Precondition API details: {api_details}")
        response = APIProcessor.send_request(api_details=api_details)
        logger.debug(f"Precondition response: {response}")

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed Precondition setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=True, portalLog=False, cnpwareLog=False,
            middlewareLog=True, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # ══════════════════════════════════════════════════════════════
        # EXECUTION
        # ══════════════════════════════════════════════════════════════
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            # Step 1: Launch ReArch app and login if present
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login flow handled")

            # Step 2-3: Initial home screen → Collect Payment → amount screen
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_collect_payment()
            home_page.wait_for_home_page_load()

            # Settings refresh: navigate to Payment History, wait for Dashboard, then back
            home_page.click_txn_history()
            txn_history_page = ReArchTxnHistoryPage(app_driver)
            txn_history_page.wait_for_txn_list()
            assert home_page.is_element_visible(TxnHistoryLocators.btn_my_dashboard, time=10), \
                "My Dashboard button should be visible on Payment History"
            logger.debug("Payment History loaded with Dashboard visible — settings refreshed")
            home_page.go_back()
            home_page.wait_for_home_page_load()
            logger.debug("Navigated back from Payment History")

            # Step 4: Click back button to return to initial home screen
            home_page.go_back()
            home_page.wait_for_initial_home_screen()
            logger.debug("Navigated back to initial home screen")

            # Step 5: Click on Settings
            home_page.click_settings()
            logger.debug("Settings tapped")

            # Step 6: Scroll down and click "Delete Cache & Relaunch App"
            account_page = ReArchAccountDetailsPage(app_driver)
            account_page.click_delete_cache_and_relaunch()
            logger.debug("Delete Cache & Relaunch App tapped")

            # Step 7: Tap "Yes, Delete & Relaunch"
            account_page.click_confirm_delete_relaunch()
            logger.debug("Confirmed Delete & Relaunch")

            # Step 9: Handle login (app will land on select env screen after cache delete)
            time.sleep(10)  # Wait for app restart after cache deletion
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login after cache delete handled")

            # Step 10: Click on Settings button
            home_page.wait_for_initial_home_screen()
            home_page.click_settings()
            logger.debug("Settings tapped")

            # Step 11: Scroll down and click "Relaunch App"
            account_page.click_relaunch_app()
            logger.debug("Relaunch App tapped")

            # Step 12: Wait until Collect Payment button is visible
            time.sleep(5)  # Wait for app relaunch
            home_page.wait_for_initial_home_screen()
            logger.debug("Collect Payment button is visible after relaunch")

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # ══════════════════════════════════════════════════════════════
        # VALIDATION
        # ══════════════════════════════════════════════════════════════
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # ── App Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                # Step 13: Verify Collect Payment button is visible
                collect_payment_visible = home_page.is_element_visible(HomeScreen.btn_collect_payment, time=45)

                expected_app_values = {
                    "collect_payment_button": "Collect Payment",
                }
                actual_app_values = {
                    "collect_payment_button": "Collect Payment" if collect_payment_visible else "NOT DISPLAYED",
                }
                logger.debug(f"expected_app_values: {expected_app_values}")
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        # Revert autoLoginByTokenEnabled back to true
        try:
            api_details = DBProcessor.get_api_details('org_settings_update', request_body={
                "username": portal_username,
                "password": portal_password,
                "entityName": "org",
                "settingForOrgCode": org_code,
            })
            api_details["RequestBody"]["settings"]["autoLoginByTokenEnabled"] = "True"
            APIProcessor.send_request(api_details=api_details)
        except Exception as e:
            logger.exception(f"Setting revert failed: {e}")
        Configuration.executeFinallyBlock(testcase_id)
