import sys
import time

import pytest

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_account_details_page import ReArchAccountDetailsPage
from appium.webdriver.common.appiumby import AppiumBy
from PageFactory.ReArch.rearch_native_locators import HomeScreen, OnboardingLocators
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
    Validator,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.appVal
def test_common_rearch_0035():
    """
    Sub Feature Code: UI_ReArch_Home_Verify_DeleteCacheRelaunch_HDFC
    Sub Feature Description:
        Launch ReArch app, handle login if required, navigate to Settings,
        scroll down and click Delete Cache & Relaunch App, confirm the dialog,
        complete onboarding (select env, dismiss popup, start), then verify
        the app relaunches by checking that "Collect Payment" is present.

    NL Source Steps:
      Preconditions:
        1. update org_settings with multiple keys (see preconditions block)
        NOTE: preconditions are NOT reverted in the finally block

      Test Steps:
        1. launch rearch app and login if present
        2. click on settings
        3. scroll down and click on Delete Cache & Relaunch App
        4. Click on "Yes, Delete & Relaunch"
        5. scroll down and select env
        6. tap on "I dont want to see this again"
        7. click on start button
        8. Verify collect payment is present

    Generated by: test_generator.md
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # -- Setup --
        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        # -- PreConditions --
        logger.info(f"Starting Precondition setup for the test case: {testcase_id}")

        api_details = DBProcessor.get_api_details('org_settings_update', request_body={
            "username": portal_username,
            "password": portal_password,
            "entityName": "org",
            "settingForOrgCode": org_code,
        })
        settings = api_details["RequestBody"]["settings"]
        settings["autoLoginByTokenEnabled"] = "true"
        settings["enableDemandDraftDD"] = "true"
        settings["preAuthOption"] = "1"
        settings["cardPaymentEnabled"] = "true"
        settings["enableWebAppRevamp"] = "true"
        settings["p2pEnabled"] = "true"
        settings["mqttEnabled"] = "true"
        settings["cashPaymentEnabled"] = "true"
        settings["addlAuthReqdForCash"] = "false"
        settings["orderNumberInputEnabled"] = "true"
        settings["customerAuthDataCaptureEnabled"] = "true"
        settings["chequePaymentEnabled"] = "true"
        settings["amountCutOffForCustomerAuth"] = "10000"
        settings["eSignatureForNonCardEnabled"] = "false"
        settings["brandingInfo"] = ""
        logger.debug(f"Precondition API details: {api_details}")
        response = APIProcessor.send_request(api_details=api_details)
        logger.debug(f"Precondition response: {response}")

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed Precondition setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=True, portalLog=False, cnpwareLog=False,
            middlewareLog=True, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # -- Test Execution --
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            # Step 1: Launch ReArch app and handle login if required
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login flow handled")

            # Step 2: Wait for initial home screen and click Settings
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_settings()
            logger.debug("Settings tapped")

            # Step 3: Scroll down and click Delete Cache & Relaunch App
            account_page = ReArchAccountDetailsPage(app_driver)
            account_page.click_delete_cache_and_relaunch()
            logger.debug("Delete Cache & Relaunch App tapped")

            # Step 4: Click "Yes, Delete & Relaunch" confirmation
            account_page.click_confirm_delete_relaunch()
            logger.debug("Confirmed Delete & Relaunch")

            # Wait for the app to restart after cache deletion
            time.sleep(10)  # TODO: adjust wait time based on actual app restart duration

            # Step 5: Scroll down and select env
            env_name = ConfigReader.read_config("environment", "str_exe_env")
            logger.debug(f"Environment from config: {env_name}")
            login_page.wait_for_element(OnboardingLocators.lbl_select_environment, time=60)
            env_element = login_page.scroll_to_text(env_name)
            if env_element:
                env_element.click()
            else:
                login_page.perform_click(
                    (AppiumBy.XPATH, f"//android.widget.Button[contains(@text,'{env_name}')]")  # TODO: verify locator on first run
                )
            logger.debug(f"Environment '{env_name}' selected")

            # Step 6: Tap "I dont want to see this again"
            login_page.perform_click(OnboardingLocators.chk_dont_show_again)
            logger.debug("Checked 'I dont want to see this again'")

            # Step 7: Click on start button
            login_page.perform_click(OnboardingLocators.btn_start)
            logger.debug("Start button tapped")

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # -- Validation --
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # -- App Validation --
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                # Step 8: Verify collect payment is present
                home_page.wait_for_initial_home_screen()
                collect_payment_visible = str(home_page.is_element_visible(HomeScreen.btn_collect_payment, time=45))

                expected_app_values = {
                    "collect_payment_button": "Collect Payment",
                }
                actual_app_values = {
                    "collect_payment_button": "Collect Payment" if collect_payment_visible == "True" else "NOT DISPLAYED",
                }
                logger.debug(f"expected_app_values: {expected_app_values}")
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        # NOTE: Preconditions are intentionally NOT reverted here
        Configuration.executeFinallyBlock(testcase_id)
