import sys
import random
import pytest

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_order_details_page import ReArchOrderDetailsPage
from PageFactory.ReArch.rearch_qr_page import ReArchQRPage
from PageFactory.ReArch.rearch_complete_page import ReArchCompletePage
from PageFactory.ReArch.rearch_txn_history_page import ReArchTxnHistoryPage
from PageFactory.ReArch.rearch_txn_detail_page import ReArchTxnDetailPage
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
    Validator, date_time_converter,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.apiVal
@pytest.mark.appVal
def test_UI_ReArch_PM_UPI_Success_HDFC_01():
    """
    Sub Feature Code: UI_ReArch_PM_UPI_Success_HDFC
    Sub Feature Description:
        Launch ReArch app, enter a random amount (100-200), select UPI, proceed
        through Order Details overlay (no order ID), wait for QR screen, trigger
        HDFC PG simulator success via cancel_payment() flow (back + confirm
        "Yes, Cancel"), verify Payment Successful screen, then validate via
        App (TxnHistory → TxnDetail) and API (txnlist).
    TC naming code description:
        100: Payment Method, 101: UPI, 001: TC001

    NL Source Steps:
      Preconditions:
        1. update org_settings: upiEnabled = true

      Test Steps:
        1.  launch rearch app
        2.  login with credentials (already logged in — skipped)
        3.  wait for initial home screen
        4.  click collect payment
        5.  wait for home page
        6.  enter amount (random 100-200)
        7.  click upi
        8.  wait for order details screen
        9.  click proceed
        10. wait for qr screen
        11. cancel payment (back → "Yes, Cancel" → HDFC PG simulator success callback)
        12. verify success screen
        13. click accept more payments

      App Validation:
        14. navigate to transaction history → txn detail (via txn_id search)
        15. validate payment id is not empty
        16. validate txn status
        17. validate amount
        18. validate date time is not empty

      API Validation:
        pmt_status=AUTHORIZED, txn_amt, pmt_mode=UPI, txn_type=CHARGE,
        acquirer_code=HDFC, issuer_code=HDFC, org_code, rrn, date

    Generated by: test_generator.md, action_registry.yaml
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # ── Reset Settings to default ──────────────────────────────────────────
        logger.info(f"Reverting back all the settings that were done as preconditions: {testcase_id}")

        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        logger.info(f"Reverted back all the settings that were done as preconditions: {testcase_id}")

        # ── PreConditions ──────────────────────────────────────────────────────
        logger.info(f"Starting Precondition setup for the test case: {testcase_id}")

        api_details = DBProcessor.get_api_details('org_settings_update', request_body={
            "username": portal_username,
            "password": portal_password,
            "entityName": "org",
            "settingForOrgCode": org_code,
        })
        api_details["RequestBody"]["settings"]["upiEnabled"] = "true"
        logger.debug(f"Precondition API details: {api_details}")
        response = APIProcessor.send_request(api_details=api_details)
        logger.debug(f"Precondition response: {response}")

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed Precondition setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=True, portalLog=False, cnpwareLog=False,
            middlewareLog=True, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # ── Test Execution ─────────────────────────────────────────────────────
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            amount = str(random.randint(100, 200))
            logger.debug(f"amount={amount}")

            # Steps 1-2: Launch ReArch app (already logged in — login skipped)
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            # login_page = ReArchLoginPage(app_driver)
            # login_page.perform_login(app_username, app_password)
            # logger.debug("Login completed")

            # Steps 3-4: Wait for initial home screen and tap Collect Payment
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_collect_payment()
            logger.debug("Collect Payment tapped")

            # Steps 5-6: Wait for amount screen and enter amount
            home_page.wait_for_home_page_load()
            home_page.enter_amount(amount)
            logger.debug(f"Amount {amount} entered")

            # Step 7: Tap UPI
            home_page.click_pay_by_upi()
            logger.debug("UPI payment method selected")

            # Steps 8-9: Order Details overlay → Proceed (no order ID entered)
            order_details_page = ReArchOrderDetailsPage(app_driver)
            order_details_page.wait_for_order_details_screen()
            order_details_page.click_proceed()
            logger.debug("Order Details: clicked Proceed")

            # Step 10: Wait for QR screen
            qr_page = ReArchQRPage(app_driver)
            qr_page.wait_for_qr_screen()
            logger.debug("QR screen confirmed")

            # Step 11: Trigger HDFC PG simulator success via cancel flow
            # back → "Yes, Cancel" dialog → simulator sends success callback
            qr_page.cancel_payment()
            logger.debug("Cancel payment triggered — HDFC PG simulator success callback expected")

            # Step 12: Verify payment success screen
            complete_page = ReArchCompletePage(app_driver)
            complete_page.wait_for_success_screen()
            logger.info("Payment Successful screen confirmed")

            # Resolve txn from DB — no order_id used; fetch latest UPI txn for this org
            query = (
                f"select id, created_time, rr_number "
                f"from txn "
                f"where org_code='{org_code}' "
                f"AND payment_mode='UPI' "
                f"order by created_time desc limit 1;"
            )
            logger.debug(f"Query to resolve txn_id: {query}")
            result = DBProcessor.getValueFromDB(query)
            txn_id       = result["id"].values[0]
            created_time = result["created_time"].values[0]
            rrn          = str(result["rr_number"].values[0])
            logger.debug(f"Resolved txn_id={txn_id}, created_time={created_time}, rrn={rrn}")

            # Step 13: Accept more payments → back to amount screen
            complete_page.click_proceed_to_home()
            logger.debug("Clicked Accept More Payments")

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # ── Validation ─────────────────────────────────────────────────────────
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # ── App Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                date_and_time = date_time_converter.to_app_format(created_time)
                expected_app_values = {
                    "txn_status": "Payment Authorized",   # TODO: verify exact status label on first run
                    "txn_id":     txn_id,
                    "date":       date_and_time,
                    "amount":     amount,
                }
                logger.debug(f"expected_app_values: {expected_app_values}")

                # Navigate to TxnDetail via txn_id search
                home_page.wait_for_home_page_load()
                home_page.click_txn_history()

                txn_history_page = ReArchTxnHistoryPage(app_driver)
                txn_history_page.wait_for_txn_list()
                txn_history_page.click_on_transaction_by_txn_id(txn_id=txn_id)

                txn_detail_page = ReArchTxnDetailPage(app_driver)

                # Fetch and assert transaction fields
                app_txn_id     = txn_detail_page.fetch_payment_id()
                app_txn_status = txn_detail_page.fetch_status(amount)
                app_date_time  = txn_detail_page.fetch_date_time()
                app_amount     = txn_detail_page.fetch_amount(amount)
                logger.info(
                    f"App txn_id={app_txn_id}, date_time={app_date_time}, "
                    f"txn_status={app_txn_status}, amount={app_amount}"
                )

                actual_app_values = {
                    "txn_status": app_txn_status,
                    "txn_id":     app_txn_id,
                    "date":       app_date_time,
                    "amount":     app_amount,
                }
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

                assert app_txn_id, "Payment ID should not be empty"
                assert app_date_time, "Date & Time should not be empty"

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        # ── API Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "api_validation") == "True":
            logger.info(f"Started API validation for the test case: {testcase_id}")
            try:
                date = date_time_converter.db_datetime(created_time)
                expected_api_values = {
                    "pmt_status":    "AUTHORIZED",
                    "txn_amt":       float(amount),
                    "pmt_mode":      "UPI",
                    "txn_type":      "CHARGE",
                    "acquirer_code": "HDFC",   #
                    # st run
                    "issuer_code":   "HDFC",   # TODO: verify on first run
                    "org_code":      org_code,
                    "rrn":           rrn,
                    "date":          date,
                }
                logger.debug(f"expected_api_values: {expected_api_values}")

                api_details = DBProcessor.get_api_details(
                    "txnlist",
                    request_body={"username": app_username, "password": app_password},
                )
                response = APIProcessor.send_request(api_details)
                logger.debug("txnlist API response received")

                txn_data = next(
                    (x for x in response["txns"] if x["txnId"] == txn_id), None
                )
                if txn_data is None:
                    raise ValueError(f"txn_id '{txn_id}' not found in txnlist API response")
                logger.debug(f"Filtered txn entry from txnlist: {txn_data}")

                actual_api_values = {
                    "pmt_status":    txn_data["status"],
                    "txn_amt":       float(txn_data["amount"]),
                    "pmt_mode":      txn_data["paymentMode"],
                    "txn_type":      txn_data["txnType"],
                    "acquirer_code": txn_data["acquirerCode"],
                    "issuer_code":   txn_data["issuerCode"],
                    "org_code":      txn_data["orgCode"],
                    "rrn":           str(txn_data["rrNumber"]),
                    "date":          date_time_converter.from_api_to_datetime_format(
                                         txn_data["createdTime"]
                                     ),
                }
                logger.debug(f"actual_api_values: {actual_api_values}")
                Validator.validationAgainstAPI(
                    expectedAPI=expected_api_values, actualAPI=actual_api_values
                )

            except Exception as e:
                Configuration.perform_api_val_exception(testcase_id, e)
            logger.info(f"Completed API validation for the test case: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        try:
            api_details = DBProcessor.get_api_details('org_settings_update', request_body={
                "username": portal_username,
                "password": portal_password,
                "entityName": "org",
                "settingForOrgCode": org_code,
            })
            api_details["RequestBody"]["settings"]["upiEnabled"] = "false"
            APIProcessor.send_request(api_details=api_details)
        except Exception as e:
            logger.exception(f"Precondition revert failed: {e}")
        Configuration.executeFinallyBlock(testcase_id)