import sys
import random
import pytest
import allure
from datetime import datetime

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_order_details_page import ReArchOrderDetailsPage
from PageFactory.ReArch.rearch_card_type_page import ReArchCardTypePage
from PageFactory.ReArch.rearch_complete_page import ReArchCompletePage
from PageFactory.ReArch.rearch_txn_history_page import ReArchTxnHistoryPage
from PageFactory.ReArch.rearch_txn_detail_page import ReArchTxnDetailPage
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
    Validator, date_time_converter, receipt_validator,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.apiVal
@pytest.mark.appVal
@pytest.mark.chargeSlipVal
def test_common_rearch_0017():
    """
    Sub Feature Code: UI_ReArch_PM_Card_Debit_Success_HDFC_DUMMY
    Sub Feature Description:
        Launch ReArch app (handle login only if Select Environment screen
        appears), enter a random amount between 600 and 700, select Card,
        proceed through the Order Details overlay, select RuPay Debit (EMV)
        on the DUMMY card type selection screen, verify Payment Successful
        screen, then navigate to transaction history from the collect payment
        screen, search the transaction by RRN Number (not txn_id), click it
        and verify amount and Payment Authorized status.

    NL Source Steps:
      Preconditions:
        1. update org_settings: cardEnabled = true

      Test Steps:
        1.  launch rearch app and login if present
        2.  click on collect payment
        3.  enter any amount between 600 to 700
        4.  select card
        5.  click on proceed on the next screen (order details overlay)
        6.  select RuPay Debit (EMV)
        7.  validate if payment successful message is displayed on the screen
        8.  click on history button on the collect payment screen
        9.  search transaction using RRN Number (not txn_id)
        10. do app, api and chargeslip validation

      App Validation:
        8-10. navigate to history from collect payment screen → search transaction
              by RRN Number → click transaction → verify amount matches and status
              is "Payment Authorized"

      API Validation:
        pmt_status=AUTHORIZED, txn_amt, pmt_mode=CARD, txn_type=CHARGE,
        acquirer_code=HDFC, issuer_code=HDFC, org_code, rrn, date,
        pmt_card_brand=RUPAY, pmt_card_type=DEBIT, card_txn_type=EMV
        # TODO: verify exact pmt_card_brand and issuer_code for RuPay on first run

      Charge Slip Validation:
        RRN=rrn, AUTH CODE=auth_code, BASE AMOUNT=amount, date, time

    Generated by: test_generator.md, action_registry.yaml
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # ── Reset Settings to default ──────────────────────────────────────────
        logger.info(f"Reverting back all the settings that were done as preconditions: {testcase_id}")

        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        logger.info(f"Reverted back all the settings that were done as preconditions: {testcase_id}")

        # ── PreConditions ──────────────────────────────────────────────────────
        logger.info(f"Starting Precondition setup for the test case: {testcase_id}")

        api_details = DBProcessor.get_api_details('org_settings_update', request_body={
            "username": portal_username,
            "password": portal_password,
            "entityName": "org",
            "settingForOrgCode": org_code,
        })
        api_details["RequestBody"]["settings"]["cardEnabled"] = "true"
        logger.debug(f"Precondition API details: {api_details}")
        response = APIProcessor.send_request(api_details=api_details)
        logger.debug(f"Precondition response: {response}")

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed Precondition setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=True, portalLog=False, cnpwareLog=False,
            middlewareLog=True, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # ── Test Execution ─────────────────────────────────────────────────────
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            amount = str(random.randint(600, 700))
            display_amount = str(amount) + ".00"
            logger.debug(f"amount={amount}")

            # Step 1: Launch ReArch app and login if required
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login flow handled")

            # Step 2: Wait for initial home screen and tap Collect Payment
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_collect_payment()
            logger.debug("Collect Payment tapped")

            # Step 3: Wait for amount screen and enter amount (600-700)
            home_page.wait_for_home_page_load()
            home_page.enter_amount(amount)
            logger.debug(f"Amount {amount} entered")

            # Step 4: Select Card
            home_page.click_pay_by_card()
            logger.debug("Card payment method selected")

            # Step 5: Order Details overlay -> click Proceed
            order_details_page = ReArchOrderDetailsPage(app_driver)
            order_details_page.wait_for_order_details_screen()
            order_details_page.click_proceed()
            logger.debug("Order Details: clicked Proceed")

            # Step 6: Card type selection -> RuPay Debit (EMV)
            card_type_page = ReArchCardTypePage(app_driver)
            card_type_page.wait_for_card_type_screen()
            card_type_page.click_rupay_debit_emv()
            logger.debug("Selected RuPay Debit (EMV)")

            # Step 7: Validate Payment Successful message is displayed
            complete_page = ReArchCompletePage(app_driver)
            complete_page.wait_for_success_screen()
            logger.info("Payment Successful screen confirmed")

            # Resolve txn from DB (while still on success screen)
            query = (
                f"select id, created_time, posting_date, rr_number, auth_code "
                f"from txn "
                f"where org_code='{org_code}' AND username='{app_username}' "
                f"AND payment_mode='CARD' "
                f"order by created_time desc limit 1;"
            )
            logger.debug(f"Query to resolve txn: {query}")
            result = DBProcessor.getValueFromDB(query)
            txn_id       = result["id"].values[0]
            created_time = result["created_time"].values[0]
            posting_date = result["posting_date"].values[0]
            rrn          = str(result["rr_number"].values[0])
            auth_code    = str(result["auth_code"].values[0])
            logger.debug(
                f"Resolved txn_id={txn_id}, created_time={created_time}, "
                f"posting_date={posting_date}, rrn={rrn}, auth_code={auth_code}"
            )

            # Step 8: Navigate back to the collect payment screen
            complete_page.click_proceed_to_home()
            logger.debug("Clicked Accept More Payments — back to collect payment screen")

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # ── Validation ─────────────────────────────────────────────────────────
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # ── App Validation ────────────────────────────────────────────────────
        # Steps 8-10: Click history → search by RRN → click transaction → verify
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                date_and_time = date_time_converter.to_rearch_app_format(created_time)
                expected_app_values = {
                    "txn_status": "Payment Authorized",
                    "txn_id":     txn_id,
                    "date":       date_and_time,
                    "amount":     display_amount,
                }
                logger.debug(f"expected_app_values: {expected_app_values}")

                # Step 8: Click history button on the collect payment screen
                home_page.wait_for_home_page_load()
                home_page.click_txn_history()

                # Step 9: Search transaction by RRN Number (not txn_id)
                txn_history_page = ReArchTxnHistoryPage(app_driver)
                txn_history_page.wait_for_txn_list()
                txn_history_page.click_on_transaction_by_rrn(rrn=rrn)

                txn_detail_page = ReArchTxnDetailPage(app_driver)

                # Step 10: Verify amount is correct and "Payment Authorized" is seen
                app_txn_id     = txn_detail_page.fetch_payment_id()
                app_txn_status = txn_detail_page.fetch_status(display_amount)
                app_date_time  = txn_detail_page.fetch_date_time()
                app_amount     = txn_detail_page.fetch_amount(display_amount)
                logger.info(
                    f"App txn_id={app_txn_id}, date_time={app_date_time}, "
                    f"app_txn_status={app_txn_status}, app_amount={app_amount}"
                )

                actual_app_values = {
                    "txn_status": app_txn_status,
                    "txn_id":     app_txn_id,
                    "date":       app_date_time,
                    "amount":     app_amount,
                }
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

                assert app_txn_id, "Payment ID should not be empty"
                assert app_date_time, "Date & Time should not be empty"

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        # ── API Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "api_validation") == "True":
            logger.info(f"Started API validation for the test case: {testcase_id}")
            try:
                date = date_time_converter.db_datetime(created_time)
                expected_api_values = {
                    "pmt_status":    "AUTHORIZED",
                    "txn_amt":       float(amount),
                    "pmt_mode":      "CARD",
                    "txn_type":      "CHARGE",
                    "acquirer_code": "HDFC",
                    "issuer_code":   "HDFC",       # TODO: verify issuer_code for RuPay on first run
                    "org_code":      org_code,
                    "rrn":           rrn,
                    "date":          date,
                    "pmt_card_brand": "RUPAY",     # TODO: verify exact brand string on first run
                    "pmt_card_type":  "DEBIT",
                    "card_txn_type":  "EMV",
                }
                logger.debug(f"expected_api_values: {expected_api_values}")

                api_details = DBProcessor.get_api_details(
                    "txnlist",
                    request_body={"username": app_username, "password": app_password},
                )
                response = APIProcessor.send_request(api_details)
                logger.debug("txnlist API response received")

                txn_data = next(
                    (x for x in response["txns"] if x["txnId"] == txn_id), None
                )
                if txn_data is None:
                    raise ValueError(f"txn_id '{txn_id}' not found in txnlist API response")
                logger.debug(f"Filtered txn entry from txnlist: {txn_data}")

                actual_api_values = {
                    "pmt_status":    txn_data["status"],
                    "txn_amt":       float(txn_data["amount"]),
                    "pmt_mode":      txn_data["paymentMode"],
                    "txn_type":      txn_data["txnType"],
                    "acquirer_code": txn_data["acquirerCode"],
                    "issuer_code":   txn_data["issuerCode"],
                    "org_code":      txn_data["orgCode"],
                    "rrn":           str(txn_data["rrNumber"]),
                    "date":          date_time_converter.from_api_to_datetime_format(
                                         txn_data["createdTime"]
                                     ),
                    "pmt_card_brand": txn_data["paymentCardBrand"],
                    "pmt_card_type":  txn_data["paymentCardType"],
                    "card_txn_type":  txn_data["cardTxnTypeDesc"],
                }
                logger.debug(f"actual_api_values: {actual_api_values}")
                Validator.validationAgainstAPI(
                    expectedAPI=expected_api_values, actualAPI=actual_api_values
                )

            except Exception as e:
                Configuration.perform_api_val_exception(testcase_id, e)
            logger.info(f"Completed API validation for the test case: {testcase_id}")

        # ── Charge Slip Validation ────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "charge_slip_validation") == "True":
            logger.info(f"Started ChargeSlip validation for the test case: {testcase_id}")
            try:
                txn_date, txn_time = date_time_converter.to_chargeslip_format(posting_date_db=posting_date)
                expected_charge_slip_values = {
                    "RRN":          rrn,
                    "AUTH CODE":    auth_code,
                    "SALE AMOUNT:": "Rs." + str(amount) + ".00",
                    "date":         txn_date,
                    "time":         txn_time,
                }
                logger.debug(f"expected_charge_slip_values: {expected_charge_slip_values}")
                receipt_validator.perform_charge_slip_validations(
                    txn_id=txn_id,
                    credentials={"username": app_username, "password": app_password},
                    expected_details=expected_charge_slip_values,
                )

            except Exception as e:
                Configuration.perform_charge_slip_val_exception(testcase_id, e)
            logger.info(f"Completed ChargeSlip validation for the test case: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        Configuration.executeFinallyBlock(testcase_id)
