import sys
import random
import pytest
import allure
from datetime import datetime

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_order_details_page import ReArchOrderDetailsPage
from PageFactory.ReArch.rearch_card_type_page import ReArchCardTypePage
from PageFactory.ReArch.rearch_complete_page import ReArchCompletePage
from PageFactory.ReArch.rearch_native_locators import TxnDetailLocators
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)

AVAILABLE_CARD_TYPES = [
    "Visa Debit (EMV)",
    "Visa Debit (Contactless)",
    "Visa Debit with PIN (EMV)",
    "Visa Debit with PIN (Contactless)",
    "Visa Credit (EMV)",
    "MasterCard Debit (EMV)",
    "MasterCard Debit (Contactless)",
    "RuPay Debit (EMV)",
]


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.appVal
def test_common_rearch_0014():
    """
    Sub Feature Code: UI_ReArch_PM_Card_Success_ViewDetails_HDFC_DUMMY
    Sub Feature Description:
        Launch ReArch app (handle login only if Select Environment screen
        appears), enter a random amount between 550 and 600, select Card,
        proceed through the Order Details overlay, select any random card
        type on the DUMMY card type selection screen, verify Payment
        Successful screen, tap View Details, verify status is Authorized
        and txn id is present, tap back, then accept more payments.

    NL Source Steps:
      Preconditions:
        1. update org_settings: cardEnabled = true

      Test Steps:
        1.  launch rearch app and login if present
        2.  click on collect payment
        3.  enter any amount between 550 to 600
        4.  select card
        5.  click on proceed on the next screen (order details overlay)
        6.  click on any card
        7.  validate if payment successful message is displayed on the screen
        8.  click on View Details button
        9.  verify status is Authorized and txn id is present
        10. tap on back button
        11. click on accept more payment

    Generated by: test_generator.md, action_registry.yaml
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # ── Setup ──────────────────────────────────────────────────────────────
        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        # ── PreConditions ──────────────────────────────────────────────────────
        logger.info(f"Starting Precondition setup for the test case: {testcase_id}")

        api_details = DBProcessor.get_api_details('org_settings_update', request_body={
            "username": portal_username,
            "password": portal_password,
            "entityName": "org",
            "settingForOrgCode": org_code,
        })
        api_details["RequestBody"]["settings"]["cardEnabled"] = "true"
        logger.debug(f"Precondition API details: {api_details}")
        response = APIProcessor.send_request(api_details=api_details)
        logger.debug(f"Precondition response: {response}")

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed Precondition setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=False, portalLog=False, cnpwareLog=False,
            middlewareLog=False, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # ── Test Execution ─────────────────────────────────────────────────────
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            amount = str(random.randint(550, 600))
            selected_card = random.choice(AVAILABLE_CARD_TYPES)
            logger.debug(f"amount={amount}, selected_card={selected_card}")

            # Step 1: Launch ReArch app and login if required
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login flow handled")

            # Step 2: Wait for initial home screen and tap Collect Payment
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_collect_payment()
            logger.debug("Collect Payment tapped")

            # Step 3: Wait for amount screen and enter amount (550–600)
            home_page.wait_for_home_page_load()
            home_page.enter_amount(amount)
            logger.debug(f"Amount {amount} entered")

            # Step 4: Select Card
            home_page.click_pay_by_card()
            logger.debug("Card payment method selected")

            # Step 5: Order Details overlay → click Proceed
            order_details_page = ReArchOrderDetailsPage(app_driver)
            order_details_page.wait_for_order_details_screen()
            order_details_page.click_proceed()
            logger.debug("Order Details: clicked Proceed")

            # Step 6: Card type selection → random card
            card_type_page = ReArchCardTypePage(app_driver)
            card_type_page.wait_for_card_type_screen()
            card_type_page.select_card_type(selected_card)
            logger.debug(f"Selected card: {selected_card}")

            # Step 7: Validate Payment Successful message is displayed
            complete_page = ReArchCompletePage(app_driver)
            complete_page.wait_for_success_screen()
            logger.info("Payment Successful screen confirmed")

            # Step 8: Click View Details
            complete_page.open_view_details()
            logger.debug("View Details opened")

            # Step 9: Verify status is Authorized and txn id is present
            status_locator = TxnDetailLocators.field_value_after("Status")
            payment_id_locator = TxnDetailLocators.field_value_after("Payment ID")

            status_value = complete_page.fetch_text(status_locator, time=10)
            payment_id_value = complete_page.fetch_text(payment_id_locator, time=10)
            logger.info(f"View Details — Status: {status_value}, Payment ID: {payment_id_value}")

            assert "Authorized" in status_value, (
                f"Expected status to contain 'Authorized', got '{status_value}'"
            )
            assert payment_id_value, "Payment ID should not be empty"

            # Step 10: Tap back button
            complete_page.go_back()
            logger.debug("Tapped back from View Details")

            # Step 11: Click Accept More Payments
            complete_page.click_proceed_to_home()
            logger.debug("Clicked Accept More Payments")

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

    finally:
        Configuration.executeFinallyBlock(testcase_id)
