import sys
import time
import pytest
import allure
from datetime import datetime

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_order_details_page import ReArchOrderDetailsPage
from PageFactory.ReArch.rearch_card_type_page import ReArchCardTypePage
from PageFactory.ReArch.rearch_complete_page import ReArchCompletePage
from PageFactory.ReArch.rearch_txn_history_page import ReArchTxnHistoryPage
from PageFactory.ReArch.rearch_txn_detail_page import ReArchTxnDetailPage
from PageFactory.ReArch.rearch_native_locators import TxnHistoryLocators
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
    Validator, date_time_converter,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.apiVal
@pytest.mark.appVal
@allure.sub_suite("UI_ReArch_PM_Card_Debit_Failure")
def test_common_rearch_0041():
    """
    Sub Feature Code: UI_ReArch_PM_Card_Debit_Failure_HDFC_DUMMY
    Sub Feature Description:
        Launch ReArch app, apply preconditions (settings refresh via Payment
        History), enter amount 401, select Card, proceed through Order Details
        overlay, select RuPay Debit (EMV) on the DUMMY card type selection
        screen. Payment fails. Navigate back to home, then to transaction
        history, click the transaction and perform app + API validation for
        the failed transaction.

    NL Source Steps:
      Preconditions:
        1.  update org_settings: autoLoginByTokenEnabled = true
        2.  update org_settings: enableDemandDraftDD = true
        3.  update org_settings: preAuthOption = 1
        4.  update org_settings: cardPaymentEnabled = true
        5.  update org_settings: enableWebAppRevamp = true
        6.  update org_settings: p2pEnabled = true
        7.  update org_settings: mqttEnabled = true
        8.  update org_settings: cashPaymentEnabled = true
        9.  update org_settings: addlAuthReqdForCash = false
        10. update org_settings: orderNumberInputEnabled = true
        11. update org_settings: customerAuthDataCaptureEnabled = true
        12. update org_settings: chequePaymentEnabled = true
        13. update org_settings: amountCutOffForCustomerAuth = 10000
        14. update org_settings: eSignatureForNonCardEnabled = false
        15. update org_settings: brandingInfo = ""
        16. update org_settings: businessDiscountEnabled = true
        17. update org_settings: boProductsEnabled = true
        18. update org_settings: boCashbackEnabled = true
        19. update org_settings: boInstantDiscountEnabled = true

      Test Steps:
        1.  launch rearch app and login if present
        2.  apply preconditions settings (refresh via Payment History)
        3.  wait for home page
        3.  enter amount as 401
        4.  select card
        5.  click on proceed on the next screen (order details overlay)
        6.  select RuPay Debit (EMV)
            (payment fails)
        8.  click on history button on the collect payment screen
        9.  click on the transaction for the amount entered in step 3
        10. do app and api validation

      Note: This is a FAILED scenario — no charge slip validation.

      App Validation:
        8-10. navigate to history → click transaction by txn_id
              → verify amount matches and status is "Payment Failed"

      API Validation:
        pmt_status=FAILED, txn_amt=401, pmt_mode=CARD, txn_type=CHARGE,
        org_code, date,
        pmt_card_brand=RUPAY, pmt_card_type=DEBIT, card_txn_type=EMV
        # TODO: verify pmt_status and acquirer_code for failed RuPay on first run

    Generated by: test_generator.md, action_registry.yaml
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # ── Setup ──────────────────────────────────────────────────────────────
        logger.info(f"Reverting back all the settings that were done as preconditions: {testcase_id}")

        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        logger.info(f"Reverted back all the settings that were done as preconditions: {testcase_id}")

        # ── PreConditions ──────────────────────────────────────────────────────
        logger.info(f"Starting Precondition setup for the test case: {testcase_id}")

        api_details = DBProcessor.get_api_details('org_settings_update', request_body={
            "username": portal_username,
            "password": portal_password,
            "entityName": "org",
            "settingForOrgCode": org_code,
        })
        api_details["RequestBody"]["settings"]["autoLoginByTokenEnabled"] = "true"
        api_details["RequestBody"]["settings"]["enableDemandDraftDD"] = "true"
        api_details["RequestBody"]["settings"]["preAuthOption"] = "1"
        api_details["RequestBody"]["settings"]["cardPaymentEnabled"] = "true"
        api_details["RequestBody"]["settings"]["enableWebAppRevamp"] = "true"
        api_details["RequestBody"]["settings"]["p2pEnabled"] = "true"
        api_details["RequestBody"]["settings"]["mqttEnabled"] = "true"
        api_details["RequestBody"]["settings"]["cashPaymentEnabled"] = "true"
        api_details["RequestBody"]["settings"]["addlAuthReqdForCash"] = "false"
        api_details["RequestBody"]["settings"]["orderNumberInputEnabled"] = "true"
        api_details["RequestBody"]["settings"]["customerAuthDataCaptureEnabled"] = "true"
        api_details["RequestBody"]["settings"]["chequePaymentEnabled"] = "true"
        api_details["RequestBody"]["settings"]["amountCutOffForCustomerAuth"] = "10000"
        api_details["RequestBody"]["settings"]["eSignatureForNonCardEnabled"] = "false"
        api_details["RequestBody"]["settings"]["brandingInfo"] = ""
        api_details["RequestBody"]["settings"]["businessDiscountEnabled"] = "true"
        api_details["RequestBody"]["settings"]["boProductsEnabled"] = "true"
        api_details["RequestBody"]["settings"]["boCashbackEnabled"] = "true"
        api_details["RequestBody"]["settings"]["boInstantDiscountEnabled"] = "true"
        logger.debug(f"Precondition API details: {api_details}")
        response = APIProcessor.send_request(api_details=api_details)
        logger.debug(f"Precondition response: {response}")

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed Precondition setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=True, portalLog=False, cnpwareLog=False,
            middlewareLog=True, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # ── Test Execution ─────────────────────────────────────────────────────
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            amount = "401"
            logger.debug(f"amount={amount}")

            # Step 1: Launch ReArch app and login if required
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login flow handled")

            # Step 2: Apply preconditions — settings refresh via Payment History
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_collect_payment()
            logger.debug("Collect Payment tapped")

            # Refresh settings: navigate to Payment History, wait for Dashboard, then back
            # (auto-login bypasses fresh login, so preconditions aren't picked up without this)
            home_page.wait_for_home_page_load()
            home_page.click_txn_history()
            txn_history_page = ReArchTxnHistoryPage(app_driver)
            txn_history_page.wait_for_txn_list()
            home_page.wait_for_element(TxnHistoryLocators.btn_my_dashboard, time=10)
            logger.debug("Payment History loaded with Dashboard visible — settings refreshed")
            home_page.go_back()
            logger.debug("Navigated back from Payment History")

            # Step 3: Wait for home page and enter amount 401
            home_page.wait_for_home_page_load()
            home_page.enter_amount(amount)
            logger.debug(f"Amount {amount} entered")

            # Step 4: Select Card
            home_page.click_pay_by_card()
            logger.debug("Card payment method selected")

            # Step 5: Order Details overlay → click Proceed
            order_details_page = ReArchOrderDetailsPage(app_driver)
            order_details_page.wait_for_order_details_screen()
            order_details_page.click_proceed()
            logger.debug("Order Details: clicked Proceed")

            # Step 6: Card type selection → RuPay Debit (EMV)
            card_type_page = ReArchCardTypePage(app_driver)
            card_type_page.wait_for_card_type_screen()
            card_type_page.click_rupay_debit_emv()
            logger.debug("Selected RuPay Debit (EMV)")

            # Payment fails — wait for failure screen
            complete_page = ReArchCompletePage(app_driver)
            complete_page.wait_for_failure_screen()
            logger.info("Payment Failed screen confirmed")

            # Navigate back from failure screen
            complete_page.click_proceed_to_home()
            logger.debug("Navigated back from failure screen")

            # Resolve txn from DB
            query = (
                f"select id, created_time "
                f"from txn "
                f"where org_code='{org_code}' AND username='{app_username}' "
                f"AND payment_mode='CARD' "
                f"order by created_time desc limit 1;"
            )
            logger.debug(f"Query to resolve txn: {query}")
            result = DBProcessor.getValueFromDB(query)
            txn_id       = result["id"].values[0]
            created_time = result["created_time"].values[0]
            logger.debug(f"Resolved txn_id={txn_id}, created_time={created_time}")

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # ── Validation ─────────────────────────────────────────────────────────
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # ── App Validation ────────────────────────────────────────────────────
        # Steps 8-10: Click history → click transaction → verify amount + "Payment Failed"
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                date_and_time = date_time_converter.to_rearch_app_format(created_time)
                expected_app_values = {
                    "txn_status": "Payment Failed",  # TODO: verify exact label on first run
                    "txn_id":     txn_id,
                    "date":       date_and_time,
                    "amount":     amount,
                }
                logger.debug(f"expected_app_values: {expected_app_values}")

                # Step 8: Navigate to history from the collect payment screen
                # TODO: on first run, verify if failure "Back to Home" lands on
                #       initial home screen or amount screen. Adjust navigation if needed.
                home_page.wait_for_initial_home_screen()
                home_page.click_collect_payment()
                home_page.wait_for_home_page_load()
                home_page.click_txn_history()

                # Step 9: Click on the transaction for the amount entered
                txn_history_page = ReArchTxnHistoryPage(app_driver)
                txn_history_page.wait_for_txn_list()
                txn_history_page.click_on_transaction_by_txn_id(txn_id=txn_id)

                txn_detail_page = ReArchTxnDetailPage(app_driver)

                # Step 10: Verify amount and payment failed status
                time.sleep(2)
                app_txn_id     = txn_detail_page.fetch_payment_id()
                app_txn_status = txn_detail_page.fetch_status(amount)
                app_date_time  = txn_detail_page.fetch_date_time_failure()  # failure uses sibling index 1
                app_amount     = txn_detail_page.fetch_amount(amount)
                logger.info(
                    f"App txn_id={app_txn_id}, date_time={app_date_time}, "
                    f"app_txn_status={app_txn_status}, app_amount={app_amount}"
                )

                actual_app_values = {
                    "txn_status": app_txn_status,
                    "txn_id":     app_txn_id,
                    "date":       app_date_time,
                    "amount":     app_amount,
                }
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

                assert app_txn_id, "Payment ID should not be empty"
                assert app_date_time, "Date & Time should not be empty"

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        # ── API Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "api_validation") == "True":
            logger.info(f"Started API validation for the test case: {testcase_id}")
            try:
                date = date_time_converter.db_datetime(created_time)
                expected_api_values = {
                    "pmt_status":     "FAILED",  # TODO: verify exact status on first run (FAILED / DECLINED / etc.)
                    "txn_amt":        float(amount),
                    "pmt_mode":       "CARD",
                    "txn_type":       "CHARGE",
                    "org_code":       org_code,
                    "date":           date,
                    "pmt_card_brand": "RUPAY",   # TODO: verify exact brand string on first run
                    "pmt_card_type":  "DEBIT",
                    "card_txn_type":  "EMV",
                }
                logger.debug(f"expected_api_values: {expected_api_values}")

                api_details = DBProcessor.get_api_details(
                    "txnlist",
                    request_body={"username": app_username, "password": app_password},
                )
                response = APIProcessor.send_request(api_details)
                logger.debug("txnlist API response received")

                txn_data = next(
                    (x for x in response["txns"] if x["txnId"] == txn_id), None
                )
                if txn_data is None:
                    raise ValueError(f"txn_id '{txn_id}' not found in txnlist API response")
                logger.debug(f"Filtered txn entry from txnlist: {txn_data}")

                actual_api_values = {
                    "pmt_status":     txn_data["status"],
                    "txn_amt":        float(txn_data["amount"]),
                    "pmt_mode":       txn_data["paymentMode"],
                    "txn_type":       txn_data["txnType"],
                    "org_code":       txn_data["orgCode"],
                    "date":           date_time_converter.from_api_to_datetime_format(
                                          txn_data["createdTime"]
                                      ),
                    "pmt_card_brand": txn_data["paymentCardBrand"],
                    "pmt_card_type":  txn_data["paymentCardType"],
                    "card_txn_type":  txn_data["cardTxnTypeDesc"],
                }
                logger.debug(f"actual_api_values: {actual_api_values}")
                Validator.validationAgainstAPI(
                    expectedAPI=expected_api_values, actualAPI=actual_api_values
                )

            except Exception as e:
                Configuration.perform_api_val_exception(testcase_id, e)
            logger.info(f"Completed API validation for the test case: {testcase_id}")

        # NOTE: No Charge Slip validation — failure scenario has no RRN/auth code

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        Configuration.executeFinallyBlock(testcase_id)
