import sys

import pytest

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_txn_history_page import ReArchTxnHistoryPage
from PageFactory.ReArch.rearch_native_locators import HomeAmountLocators, TxnHistoryLocators
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
    Validator,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)

HDFC_BRANDING_INFO = (
    '{"options":['
    '{"field":"themeName","value":"HDFC"},'
    '{"field":"primaryColor","value":"#0D4C8F"},'
    '{"field":"secondaryColor","value":"#ED232A"},'
    '{"field":"titlebarColor","value":"#0D4C8F"},'
    '{"field":"homeTitlebarColor","value":"#0D4C8F"},'
    '{"field":"customBrandColor","value":"#0D4C8F"},'
    '{"field":"customStatusBarColor","value":"#0D4C8F"},'
    '{"field":"customBrandTextColor","value":"#FFFFFF"},'
    '{"field":"titlebarTheme","value":"dark"},'
    '{"field":"titlebarButtonColor","value":"#ED232A"},'
    '{"field":"titlebarButtonTextColor","value":"light"},'
    '{"field":"bankIcon","value":"hdfc"},'
    '{"field":"customBrandColor","value":"#0D4C8F"},'
    '{"field":"customTextColor","value":"light"},'
    '{"field":"detailsButtonColor","value":"#ED232A"},'
    '{"field":"detailsButtonTextColor","value":"light"},'
    '{"field":"merchantLogo","value":"hdfc"},'
    '{"field":"customLogo","value":"light"}'
    ']}'
)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.appVal
def test_common_rearch_0049():
    """
    Sub Feature Code: UI_ReArch_Home_Verify_BrandingLogo_HDFC
    Sub Feature Description:
        Launch ReArch app, apply HDFC brandingInfo, refresh settings via
        Payment History, verify branding logo is displayed on the amount
        screen and on the initial home screen after pressing back.
        Revert brandingInfo to empty on cleanup.

    NL Source Steps:
      Preconditions:
        - Apply org_settings with HDFC brandingInfo JSON
        - Revert brandingInfo to "" on cleanup

      Test Steps:
        1. launch rearch app and login if present
        2. apply preconditions settings (refresh via Payment History)
        3. wait for home page
        4. verify logo is present on amount screen
        5. click on back button
        6. verify logo is present on initial home screen (app validation)

    Generated by: test_generator.md, action_registry.yaml
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # ══════════════════════════════════════════════════════════════
        # SETUP
        # ══════════════════════════════════════════════════════════════
        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        # ── Preconditions ─────────────────────────────────────────────────
        logger.info(f"Starting Precondition setup for the test case: {testcase_id}")

        api_details = DBProcessor.get_api_details('org_settings_update', request_body={
            "username": portal_username,
            "password": portal_password,
            "entityName": "org",
            "settingForOrgCode": org_code,
        })
        settings = api_details["RequestBody"]["settings"]
        settings["autoLoginByTokenEnabled"] = "true"
        settings["enableDemandDraftDD"] = "true"
        settings["preAuthOption"] = "1"
        settings["cardPaymentEnabled"] = "true"
        settings["enableWebAppRevamp"] = "true"
        settings["p2pEnabled"] = "true"
        settings["mqttEnabled"] = "true"
        settings["cashPaymentEnabled"] = "true"
        settings["addlAuthReqdForCash"] = "false"
        settings["orderNumberInputEnabled"] = "true"
        settings["customerAuthDataCaptureEnabled"] = "true"
        settings["chequePaymentEnabled"] = "true"
        settings["amountCutOffForCustomerAuth"] = "10000"
        settings["eSignatureForNonCardEnabled"] = "true"
        settings["brandingInfo"] = HDFC_BRANDING_INFO
        logger.debug(f"Precondition API details: {api_details}")
        response = APIProcessor.send_request(api_details=api_details)
        logger.debug(f"Precondition response: {response}")

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed Precondition setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=True, portalLog=False, cnpwareLog=False,
            middlewareLog=True, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # ══════════════════════════════════════════════════════════════
        # EXECUTION
        # ══════════════════════════════════════════════════════════════
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            # Step 1: Launch ReArch app and login if present
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login flow handled")

            # Step 2: Navigate to home, then refresh settings via Payment History
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_collect_payment()
            home_page.wait_for_home_page_load()

            # Settings refresh
            home_page.click_txn_history()
            txn_history_page = ReArchTxnHistoryPage(app_driver)
            txn_history_page.wait_for_txn_list()
            home_page.wait_for_element(TxnHistoryLocators.btn_my_dashboard, time=10)
            home_page.go_back()
            home_page.wait_for_home_page_load()
            logger.debug("Settings refreshed via Payment History navigation")

            # Step 4: Verify branding logo on amount screen
            logo_on_amount_screen = str(
                home_page.is_element_visible(HomeAmountLocators.img_branding_logo, time=10)
            )
            logger.info(f"Branding logo on amount screen: {logo_on_amount_screen}")

            # Step 5: Click back button → initial home screen
            home_page.go_back()
            home_page.wait_for_initial_home_screen()
            logger.debug("Navigated back to initial home screen")

            # Step 6: Verify branding logo on initial home screen (captured for app validation)
            logo_on_home_screen = str(
                home_page.is_element_visible(HomeAmountLocators.img_branding_logo, time=10)
            )
            logger.info(f"Branding logo on initial home screen: {logo_on_home_screen}")

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # ══════════════════════════════════════════════════════════════
        # VALIDATION
        # ══════════════════════════════════════════════════════════════
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # ── App Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                expected_app_values = {
                    "logo_on_amount_screen": "True",
                    "logo_on_home_screen":   "True",
                }
                actual_app_values = {
                    "logo_on_amount_screen": logo_on_amount_screen,
                    "logo_on_home_screen":   logo_on_home_screen,
                }
                logger.debug(f"expected_app_values: {expected_app_values}")
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        # Revert brandingInfo to empty
        try:
            revert_api_details = DBProcessor.get_api_details('org_settings_update', request_body={
                "username": portal_username,
                "password": portal_password,
                "entityName": "org",
                "settingForOrgCode": org_code,
            })
            revert_api_details["RequestBody"]["settings"]["brandingInfo"] = ""
            APIProcessor.send_request(api_details=revert_api_details)
            logger.info("Reverted brandingInfo to empty")
        except Exception:
            logger.warning("Failed to revert brandingInfo — manual cleanup may be needed")
        Configuration.executeFinallyBlock(testcase_id)
