import sys

import pytest

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_tip_page import ReArchTipPage
from PageFactory.ReArch.rearch_txn_history_page import ReArchTxnHistoryPage
from PageFactory.ReArch.rearch_native_locators import TxnHistoryLocators
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
    Validator,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.appVal
def test_common_rearch_0032():
    """
    Sub Feature Code: UI_ReArch_Home_Verify_TipPercentage_HDFC
    Sub Feature Description:
        Launch ReArch app, handle login if required, apply preconditions
        (with settings refresh via Payment History), enter amount 515,
        tap Add Tip, and verify that 6% and 11% tip percentage buttons
        are displayed on the tip details screen.

    NL Source Steps:
      Preconditions:
        1. update org_settings with multiple keys (see preconditions block)
        NOTE: only tipPercentage and multiTipPercentage are reverted

      Test Steps:
        1. launch rearch app and login if present
        2. apply preconditions settings (refresh via Payment History)
        3. wait for home page
        4. enter amount as 515
        5. click on Add Tip button
        6. verify 6% and 11% tip percentages are present

    Generated by: test_generator.md
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # -- Setup --
        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        # -- PreConditions --
        logger.info(f"Starting Precondition setup for the test case: {testcase_id}")

        api_details = DBProcessor.get_api_details('org_settings_update', request_body={
            "username": portal_username,
            "password": portal_password,
            "entityName": "org",
            "settingForOrgCode": org_code,
        })
        settings = api_details["RequestBody"]["settings"]
        settings["autoLoginByTokenEnabled"] = "true"
        settings["enableDemandDraftDD"] = "true"
        settings["preAuthOption"] = "1"
        settings["cardPaymentEnabled"] = "true"
        settings["enableWebAppRevamp"] = "true"
        settings["p2pEnabled"] = "true"
        settings["mqttEnabled"] = "true"
        settings["cashPaymentEnabled"] = "true"
        settings["addlAuthReqdForCash"] = "false"
        settings["orderNumberInputEnabled"] = "true"
        settings["customerAuthDataCaptureEnabled"] = "true"
        settings["chequePaymentEnabled"] = "true"
        settings["amountCutOffForCustomerAuth"] = "10000"
        settings["eSignatureForNonCardEnabled"] = "false"
        settings["brandingInfo"] = ""
        settings["tipPercentage"] = "15"
        settings["multiTipPercentage"] = "6, 11, 16"
        logger.debug(f"Precondition API details: {api_details}")
        response = APIProcessor.send_request(api_details=api_details)
        logger.debug(f"Precondition response: {response}")

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed Precondition setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=True, portalLog=False, cnpwareLog=False,
            middlewareLog=True, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # -- Test Execution --
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            # Step 1: Launch ReArch app and handle login if required
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login flow handled")

            # Step 2: Navigate to home, then refresh settings via Payment History
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_collect_payment()
            home_page.wait_for_home_page_load()

            # Refresh settings: navigate to Payment History, wait for Dashboard, then back
            home_page.click_txn_history()
            txn_history_page = ReArchTxnHistoryPage(app_driver)
            txn_history_page.wait_for_txn_list()
            home_page.go_back()
            logger.debug("Settings refreshed via Payment History navigation")

            # Step 3: Wait for home page after returning from Payment History
            home_page.wait_for_home_page_load()
            logger.debug("Home page ready after settings refresh")

            # Step 4: Enter amount 515
            home_page.enter_amount("515")
            logger.debug("Amount 515 entered")

            # Step 5: Click Add Tip
            home_page.click_add_tip()
            logger.debug("Add Tip tapped")

            # Wait for tip screen to load
            tip_page = ReArchTipPage(app_driver)
            tip_page.wait_for_tip_screen()

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # -- Validation --
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # -- App Validation --
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                # Step 6: Verify 6% and 11% tip percentages are present
                expected_app_values = {
                    "tip_6_percent": "₹31 6%",
                    "tip_11_percent": "₹57 11%",
                }
                logger.debug(f"expected_app_values: {expected_app_values}")

                tip_6_visible = str(tip_page.is_6_percent_displayed())
                tip_11_visible = str(tip_page.is_11_percent_displayed())

                actual_app_values = {
                    "tip_6_percent": "₹31 6%" if tip_6_visible == "True" else "NOT DISPLAYED",
                    "tip_11_percent": "₹57 11%" if tip_11_visible == "True" else "NOT DISPLAYED",
                }
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        # Revert only tipPercentage and multiTipPercentage
        try:
            revert_api_details = DBProcessor.get_api_details('org_settings_update', request_body={
                "username": portal_username,
                "password": portal_password,
                "entityName": "org",
                "settingForOrgCode": org_code,
            })
            revert_settings = revert_api_details["RequestBody"]["settings"]
            revert_settings["tipPercentage"] = ""
            revert_settings["multiTipPercentage"] = ""
            APIProcessor.send_request(api_details=revert_api_details)
            logger.info("Reverted tipPercentage and multiTipPercentage to empty")
        except Exception as e:
            logger.error(f"Failed to revert tip settings: {e}")

        Configuration.executeFinallyBlock(testcase_id)
