import sys
import random
import time

import pytest
import allure
from datetime import datetime

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_order_details_page import ReArchOrderDetailsPage
from PageFactory.ReArch.rearch_payment_method_page import ReArchPaymentMethodPage
from PageFactory.ReArch.rearch_cash_confirm_page import ReArchCashConfirmPage
from PageFactory.ReArch.rearch_complete_page import ReArchCompletePage
from PageFactory.ReArch.rearch_txn_history_page import ReArchTxnHistoryPage
from PageFactory.ReArch.rearch_txn_detail_page import ReArchTxnDetailPage
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
    Validator, date_time_converter, receipt_validator,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.apiVal
@pytest.mark.appVal
@pytest.mark.chargeSlipVal
def test_common_rearch_0005():
    """
    Sub Feature Code: UI_ReArch_PM_Cash_Success_HDFC
    Sub Feature Description:
        Launch ReArch app (already logged in), enter a random amount (100-500),
        navigate via ⋯ → Order Details → Proceed → Payment Methods overlay → Cash →
        Cash Confirm screen → Confirm Payment → verify Payment Successful screen,
        then validate via App (TxnHistory → TxnDetail), API, and Charge Slip.
    TC naming code description:
        100: Payment Method, 106: Cash, 001: TC001

    NL Source Steps:
      Preconditions:
        1. update org_settings: cashEnabled = true

      Test Steps:
        1.  wait for initial home screen
        2.  click collect payment
        3.  wait for home page
        4.  enter amount <random 100-500>
        5.  click more payment options
        6.  wait for order details
        7.  click proceed on order details
        8.  wait for payment methods
        9.  select cash from payment methods
        10. wait for cash confirm screen
        11. click confirm payment
        12. verify payment success
        13. click accept more payments

      App Validation:
        14. go to transaction history
        15. wait for transaction list
        16. click first transaction
        17. wait for transaction detail
        18. validate payment id is not empty
        19. validate txn status
        20. validate amount matches
        21. validate date time is not empty

      API Validation:
        pmt_status=AUTHORIZED, txn_amt, pmt_mode=CASH, acquirer_code=HDFC, org_code, date

      Charge Slip Validation:
        PAID BY=CASH, BASE AMOUNT=amount, date, time

    Generated by: test_generator.md, action_registry.yaml
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # ── Reset Settings to default ──────────────────────────────────────────
        logger.info(f"Reverting back all the settings that were done as preconditions: {testcase_id}")

        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        logger.info(f"Reverted back all the settings that were done as preconditions: {testcase_id}")

        # ── PreConditions ──────────────────────────────────────────────────────
        logger.info(f"Starting Precondition setup for the test case: {testcase_id}")

        api_details = DBProcessor.get_api_details('org_settings_update', request_body={
            "username": portal_username,
            "password": portal_password,
            "entityName": "org",
            "settingForOrgCode": org_code,
        })
        api_details["RequestBody"]["settings"]["cashEnabled"] = "true"
        logger.debug(f"Precondition API details: {api_details}")
        response = APIProcessor.send_request(api_details=api_details)
        logger.debug(f"Precondition response: {response}")

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed Precondition setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=True, portalLog=False, cnpwareLog=False,
            middlewareLog=True, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # ── Test Execution ─────────────────────────────────────────────────────
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            amount = str(random.randint(100, 500))
            display_amount = f"{int(amount):,}.00"
            logger.debug(f"amount={amount}")

            # Steps 1-2: Wait for initial home screen and tap Collect Payment
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_collect_payment()
            logger.debug("Collect Payment tapped")

            # Steps 3-4: Wait for amount screen and enter amount
            home_page.wait_for_home_page_load()
            home_page.enter_amount(amount)
            logger.debug(f"Amount {amount} entered")

            # Step 5: Tap ⋯ (More Payment Options)
            home_page.click_more_payment_options()
            logger.debug("More Payment Options (⋯) tapped")

            # Steps 6-7: Wait for Order Details overlay → click Proceed
            order_details_page = ReArchOrderDetailsPage(app_driver)
            order_details_page.wait_for_order_details_screen()
            order_details_page.click_proceed()
            logger.debug("Order Details: clicked Proceed")

            # Steps 8-9: Wait for Payment Method overlay → select Cash
            payment_method_page = ReArchPaymentMethodPage(app_driver)
            payment_method_page.wait_for_payment_methods()
            payment_method_page.click_cash()
            logger.debug("Cash selected from payment methods")

            # Steps 10-11: Wait for Cash Confirm screen → Confirm Payment
            cash_confirm_page = ReArchCashConfirmPage(app_driver)
            cash_confirm_page.wait_for_cash_confirm_screen()
            cash_confirm_page.click_confirm_payment()
            logger.debug("Cash payment confirmed")

            # Step 12: Verify payment success screen
            complete_page = ReArchCompletePage(app_driver)
            complete_page.wait_for_success_screen()
            logger.info("Payment Successful screen confirmed")

            # Step 13: Accept more payments → back to home screen
            complete_page.click_proceed_to_home()
            logger.debug("Clicked Accept More Payments")

            # Resolve txn from DB
            query = (
                f"select id, created_time, posting_date "
                f"from txn "
                f"where org_code='{org_code}' AND username='{app_username}' "
                f"AND payment_mode='CASH' "
                f"order by created_time desc limit 1;"
            )
            logger.debug(f"Query to resolve txn_id: {query}")
            result = DBProcessor.getValueFromDB(query)
            txn_id       = result["id"].values[0]
            created_time = result["created_time"].values[0]
            posting_date = result["posting_date"].values[0]
            logger.debug(
                f"Resolved txn_id={txn_id}, created_time={created_time}, "
                f"posting_date={posting_date}"
            )

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in try block of testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # ── Validation ─────────────────────────────────────────────────────────
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # ── App Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                date_and_time = date_time_converter.to_app_format(created_time)
                expected_app_values = {
                    "txn_status": "Payment Settled",  # TODO: verify exact label for Cash on first run
                    "txn_id":     txn_id,
                    "date":       date_and_time,
                    "amount":     display_amount,
                }
                logger.debug(f"expected_app_values: {expected_app_values}")

                # Navigate to TxnDetail
                home_page.wait_for_home_page_load()
                home_page.click_txn_history()

                txn_history_page = ReArchTxnHistoryPage(app_driver)
                txn_history_page.wait_for_txn_list()
                txn_history_page.click_on_transaction_by_txn_id(txn_id=txn_id)

                txn_detail_page = ReArchTxnDetailPage(app_driver)


                # Fetch and assert transaction fields
                time.sleep(2)
                app_txn_id     = txn_detail_page.fetch_payment_id()
                app_txn_status = txn_detail_page.fetch_status(display_amount)
                app_date_time  = txn_detail_page.fetch_date_time()
                app_amount     = txn_detail_page.fetch_amount(display_amount)
                logger.info(
                    f"App txn_id={app_txn_id}, date_time={app_date_time}, "
                    f"app_txn_status={app_txn_status}, app_amount={app_amount}"
                )

                actual_app_values = {
                    "txn_status": app_txn_status,
                    "txn_id":     app_txn_id,
                    "date":       app_date_time,
                    "amount":     app_amount,
                }
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

                assert app_txn_id, "Payment ID should not be empty"
                assert app_date_time, "Date & Time should not be empty"

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        # ── API Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "api_validation") == "True":
            logger.info(f"Started API validation for the test case: {testcase_id}")
            try:
                date = date_time_converter.db_datetime(created_time)
                expected_api_values = {
                    "pmt_status":    "AUTHORIZED",
                    "txn_amt":       float(amount),
                    "pmt_mode":      "CASH",
                    "txn_type":      "CHARGE",
                    "acquirer_code": "NONE",
                    "org_code":      org_code,
                    "date":          date,
                }
                logger.debug(f"expected_api_values: {expected_api_values}")

                api_details = DBProcessor.get_api_details(
                    "txnlist",
                    request_body={"username": app_username, "password": app_password},
                )
                response = APIProcessor.send_request(api_details)
                logger.debug("txnlist API response received")

                txn_data = next(
                    (x for x in response["txns"] if x["txnId"] == txn_id), None
                )
                if txn_data is None:
                    raise ValueError(f"txn_id '{txn_id}' not found in txnlist API response")
                logger.debug(f"Filtered txn entry from txnlist: {txn_data}")

                actual_api_values = {
                    "pmt_status":    txn_data["status"],
                    "txn_amt":       float(txn_data["amount"]),
                    "pmt_mode":      txn_data["paymentMode"],
                    "txn_type":      txn_data["txnType"],
                    "acquirer_code": txn_data["acquirerCode"],
                    "org_code":      txn_data["orgCode"],
                    "date":          date_time_converter.from_api_to_datetime_format(
                                         txn_data["createdTime"]
                                     ),
                }
                logger.debug(f"actual_api_values: {actual_api_values}")
                Validator.validationAgainstAPI(
                    expectedAPI=expected_api_values, actualAPI=actual_api_values
                )

            except Exception as e:
                Configuration.perform_api_val_exception(testcase_id, e)
            logger.info(f"Completed API validation for the test case: {testcase_id}")

        # ── Charge Slip Validation ────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "charge_slip_validation") == "True":
            logger.info(f"Started ChargeSlip validation for the test case: {testcase_id}")
            try:
                txn_date, txn_time = date_time_converter.to_chargeslip_format(posting_date_db=posting_date)
                expected_charge_slip_values = {
                    "PAID BY:":     "CASH",
                    "BASE AMOUNT:": f"Rs.{int(amount):,}.00",
                    "date":         txn_date,
                    "time":         txn_time,
                }
                logger.debug(f"expected_charge_slip_values: {expected_charge_slip_values}")
                receipt_validator.perform_charge_slip_validations(
                    txn_id=txn_id,
                    credentials={"username": app_username, "password": app_password},
                    expected_details=expected_charge_slip_values,
                )

            except Exception as e:
                Configuration.perform_charge_slip_val_exception(testcase_id, e)
            logger.info(f"Completed ChargeSlip validation for the test case: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        Configuration.executeFinallyBlock(testcase_id)