import sys
import random

import pytest

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_order_details_page import ReArchOrderDetailsPage
from PageFactory.ReArch.rearch_payment_method_page import ReArchPaymentMethodPage
from PageFactory.ReArch.rearch_cheque_page import ReArchChequePage
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
    Validator,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.appVal
def test_common_rearch_0030():
    """
    Sub Feature Code: UI_ReArch_PM_Cheque_Validation_HDFC
    Sub Feature Description:
        Launch ReArch app, handle login if required, enter a random amount (500-600),
        navigate via More Payment Options -> Order Details -> Proceed -> Payment Methods
        overlay -> scroll down -> Cheque -> click Confirm Payment without filling any
        fields -> verify all validation error messages are displayed:
        "Cheque number should be 6 digits", "Please select a bank",
        "Please select Cheque Date", scroll down and verify "Invalid Bank IFSC Code".

    NL Source Steps:
      Preconditions:
        1. update org_settings with multiple keys (see preconditions block)
        NOTE: preconditions are NOT reverted in the finally block

      Test Steps:
        1. launch rearch app and login if present
        2. click on collect payment
        3. enter any amount between 500 to 600
        4. click on overlay button (More Payment Options)
        5. click on proceed button on order details screen
        6. scroll down and click on Cheque button
        7. click on Confirm Payment
        8. verify error messages: "Cheque number should be 6 digits",
           "Please select a bank", "Please select Cheque Date",
           scroll down and verify "Invalid Bank IFSC Code"

    Generated by: test_generator.md
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # -- Setup --
        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        # -- PreConditions --
        logger.info(f"Starting Precondition setup for the test case: {testcase_id}")

        api_details = DBProcessor.get_api_details('org_settings_update', request_body={
            "username": portal_username,
            "password": portal_password,
            "entityName": "org",
            "settingForOrgCode": org_code,
        })
        settings = api_details["RequestBody"]["settings"]
        settings["autoLoginByTokenEnabled"] = "true"
        settings["preAuthOption"] = "1"
        settings["cardPaymentEnabled"] = "true"
        settings["enableWebAppRevamp"] = "true"
        settings["p2pEnabled"] = "true"
        settings["mqttEnabled"] = "true"
        settings["cashPaymentEnabled"] = "true"
        settings["addlAuthReqdForCash"] = "false"
        settings["orderNumberInputEnabled"] = "true"
        settings["customerAuthDataCaptureEnabled"] = "true"
        settings["chequePaymentEnabled"] = "true"
        settings["amountCutOffForCustomerAuth"] = "10000"
        settings["eSignatureForNonCardEnabled"] = "false"
        settings["brandingInfo"] = ""
        logger.debug(f"Precondition API details: {api_details}")
        response = APIProcessor.send_request(api_details=api_details)
        logger.debug(f"Precondition response: {response}")

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed Precondition setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=True, portalLog=False, cnpwareLog=False,
            middlewareLog=True, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # -- Test Execution --
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            amount = str(random.randint(500, 600))
            logger.debug(f"amount={amount}")

            # Step 1: Launch ReArch app and handle login if required
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login flow handled")

            # Step 2: Wait for initial home screen and tap Collect Payment
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_collect_payment()
            logger.debug("Collect Payment tapped")

            # Step 3: Wait for amount screen and enter amount
            home_page.wait_for_home_page_load()
            home_page.enter_amount(amount)
            logger.debug(f"Amount {amount} entered")

            # Step 4: Tap More Payment Options
            home_page.click_more_payment_options()
            logger.debug("More Payment Options tapped")

            # Step 5: Wait for Order Details overlay -> click Proceed
            order_details_page = ReArchOrderDetailsPage(app_driver)
            order_details_page.wait_for_order_details_screen()
            order_details_page.click_proceed()
            logger.debug("Order Details: clicked Proceed")

            # Step 6: Wait for Payment Method overlay -> scroll down -> click Cheque
            payment_method_page = ReArchPaymentMethodPage(app_driver)
            payment_method_page.wait_for_payment_methods()
            payment_method_page.scroll_to_text("Cheque")
            payment_method_page.click_cheque()
            logger.debug("Cheque selected from payment methods")

            # Step 7: Click Confirm Payment without filling any cheque details
            cheque_page = ReArchChequePage(app_driver)
            cheque_page.wait_for_cheque_form()
            cheque_page.click_confirm_payment()
            logger.debug("Clicked Confirm Payment on empty cheque form")

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # -- Validation --
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # -- App Validation --
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                # Step 8: Verify error messages
                expected_app_values = {
                    "cheque_number_error": "Cheque number should be 6 digits",
                    "select_bank_error": "Please select a bank",
                    "cheque_date_error": "Please select Cheque Date",
                    "ifsc_code_error": "Invalid Bank IFSC Code",
                }
                logger.debug(f"expected_app_values: {expected_app_values}")

                cheque_number_error = str(cheque_page.is_error_cheque_number_displayed())
                select_bank_error = str(cheque_page.is_error_select_bank_displayed())
                cheque_date_error = str(cheque_page.is_error_cheque_date_displayed())

                # Scroll down to verify IFSC error
                cheque_page.swipe_up()
                ifsc_code_error = str(cheque_page.is_error_invalid_ifsc_displayed())

                actual_app_values = {
                    "cheque_number_error": "Cheque number should be 6 digits" if cheque_number_error == "True" else "NOT DISPLAYED",
                    "select_bank_error": "Please select a bank" if select_bank_error == "True" else "NOT DISPLAYED",
                    "cheque_date_error": "Please select Cheque Date" if cheque_date_error == "True" else "NOT DISPLAYED",
                    "ifsc_code_error": "Invalid Bank IFSC Code" if ifsc_code_error == "True" else "NOT DISPLAYED",
                }
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        # NOTE: Preconditions are intentionally NOT reverted here
        Configuration.executeFinallyBlock(testcase_id)
