import sys
import pytest

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_txn_history_page import ReArchTxnHistoryPage
from PageFactory.ReArch.rearch_native_locators import TxnHistoryLocators, TxnSearchLocators
from Utilities import ConfigReader, ResourceAssigner, Validator
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.appVal
def test_common_rearch_0015():
    """
    Sub Feature Code: UI_ReArch_Home_Verify_PaymentHistoryButtons_HDFC
    Sub Feature Description:
        Launch ReArch app, handle login if Select Environment screen appears,
        tap Payment History (Transactions), wait for My Dashboard to load,
        then verify that Payment ID, RRN Number, Amount buttons are visible
        and Auth Code button is visible after a small horizontal scroll.

    NL Source Steps:
      Preconditions:
        None

      Test Steps:
        1. launch rearch app and login if present
        2. click on Payment history button
        3. wait until My Dashboard is present
        4. verify Payment ID, RRN Number, Amount button is present;
           scroll little horizontally and verify Auth Code button is present

    Generated by: test_generator.md
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # ── Setup ──────────────────────────────────────────────────────────────
        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=False, portalLog=False, cnpwareLog=False,
            middlewareLog=False, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # ── Test Execution ─────────────────────────────────────────────────────
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            # Step 1: Launch ReArch app and handle login if required
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login flow handled")

            # Step 2: Click on Payment History (Transactions) button
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_transactions()
            logger.debug("Navigated to Payment History")

            # Step 3: Wait until My Dashboard is present
            txn_history_page = ReArchTxnHistoryPage(app_driver)
            txn_history_page.wait_for_element(TxnHistoryLocators.btn_my_dashboard)
            logger.debug("My Dashboard button is present")

            # Scroll horizontally to make Auth Code visible (UI action)
            txn_history_page.swipe_left(duration_ms=500)
            logger.debug("Horizontal scroll performed")

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # ── Validation ─────────────────────────────────────────────────────────
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # ── App Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                # Step 4: Verify Payment ID, RRN Number, Amount, Auth Code buttons
                payment_id_visible = str(txn_history_page.is_element_visible(TxnSearchLocators.btn_payment_id, time=10))
                rrn_visible = str(txn_history_page.is_element_visible(TxnSearchLocators.btn_rrn_number, time=10))
                amount_visible = str(txn_history_page.is_element_visible(TxnSearchLocators.btn_amount, time=10))
                auth_code_visible = str(txn_history_page.is_element_visible(TxnSearchLocators.btn_auth_code, time=10))

                expected_app_values = {
                    "payment_id_button": "Payment ID",
                    "rrn_number_button": "RRN Number",
                    "amount_button": "Amount",
                    "auth_code_button": "Auth Code",
                }
                actual_app_values = {
                    "payment_id_button": "Payment ID" if payment_id_visible == "True" else "NOT DISPLAYED",
                    "rrn_number_button": "RRN Number" if rrn_visible == "True" else "NOT DISPLAYED",
                    "amount_button": "Amount" if amount_visible == "True" else "NOT DISPLAYED",
                    "auth_code_button": "Auth Code" if auth_code_visible == "True" else "NOT DISPLAYED",
                }
                logger.debug(f"expected_app_values: {expected_app_values}")
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        Configuration.executeFinallyBlock(testcase_id)
