import sys
import pytest

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_native_locators import HelpCenterLocators
from Utilities import ResourceAssigner
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.appVal
def test_common_rearch_0019():
    """
    Sub Feature Code: UI_ReArch_Home_Verify_HelpCenter_HDFC
    Sub Feature Description:
        Launch ReArch app, handle login only if the Select Environment screen
        appears (auto-login skips it), tap Help Center on the initial home
        screen, then verify that support numbers 1800 212 212 212 and
        1800 313 313 313 are displayed on the Help Center page.

    NL Source Steps:
      Preconditions:
        None

      Test Steps:
        1. launch rearch app and login if present
        2. click on Help Center
        3. verify current page displays text 1800 212 212 212 / 1800 313 313 313

    Generated by: test_generator.md
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # ── Setup ──────────────────────────────────────────────────────────────
        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=False, portalLog=False, cnpwareLog=False,
            middlewareLog=False, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # ── Test Execution ─────────────────────────────────────────────────────
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            # Step 1: Launch ReArch app and handle login if required
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login flow handled")

            # Step 2: Wait for initial home screen and tap Help Center
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_help()
            logger.debug("Help Center tapped")

            # Step 3: Verify support numbers are displayed
            support_visible = home_page.is_element_visible(HelpCenterLocators.lbl_support_numbers, time=10)
            logger.info(f"Support numbers (1800 212 212 212 / 1800 313 313 313) visible: {support_visible}")

            assert support_visible, "Support numbers 1800 212 212 212 / 1800 313 313 313 should be displayed on the Help Center page"

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

    finally:
        Configuration.executeFinallyBlock(testcase_id)
