import sys
import time
import pytest

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_txn_history_page import ReArchTxnHistoryPage
from PageFactory.ReArch.rearch_native_locators import TxnHistoryLocators
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
    Validator,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.appVal
def test_common_rearch_0050():
    """
    Sub Feature Code: UI_ReArch_Home_Verify_DateFilterClearAll_HDFC
    Sub Feature Description:
        Launch ReArch app, navigate to Payment History, apply Date → Today
        filter, then click Clear all and verify the clear all works as
        expected and My Dashboard is visible.

    NL Source Steps:
      Preconditions:
        1.  update org_settings: autoLoginByTokenEnabled = true
        2.  update org_settings: enableDemandDraftDD = true
        3.  update org_settings: cardPaymentEnabled = true
        4.  update org_settings: enableWebAppRevamp = true
        5.  update org_settings: p2pEnabled = true
        6.  update org_settings: mqttEnabled = true
        7.  update org_settings: cashPaymentEnabled = true
        8.  update org_settings: addlAuthReqdForCash = false
        9.  update org_settings: orderNumberInputEnabled = true
        10. update org_settings: customerAuthDataCaptureEnabled = true
        11. update org_settings: chequePaymentEnabled = true
        12. update org_settings: amountCutOffForCustomerAuth = 10000
        13. update org_settings: eSignatureForNonCardEnabled = false
        14. update org_settings: brandingInfo = ""
        15. update org_settings: businessDiscountEnabled = true
        16. update org_settings: boProductsEnabled = true
        17. update org_settings: boCashbackEnabled = true
        18. update org_settings: boInstantDiscountEnabled = true
        19. update org_settings: paymentPromotionEnabled = false

      Test Steps:
        1. launch rearch app and login if present
        2. click on Payment History
        3. click on Date filter
        4. click on Today
        5. click on Clear all
        6. verify clear all button is working and My Dashboard is visible

    Generated by: test_generator.md, action_registry.yaml
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # ── Setup ──────────────────────────────────────────────────────────────
        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        # ── PreConditions ──────────────────────────────────────────────────────
        logger.info(f"Starting Precondition setup for the test case: {testcase_id}")

        api_details = DBProcessor.get_api_details('org_settings_update', request_body={
            "username": portal_username,
            "password": portal_password,
            "entityName": "org",
            "settingForOrgCode": org_code,
        })
        settings = api_details["RequestBody"]["settings"]
        settings["autoLoginByTokenEnabled"] = "true"
        settings["enableDemandDraftDD"] = "true"
        settings["cardPaymentEnabled"] = "true"
        settings["enableWebAppRevamp"] = "true"
        settings["p2pEnabled"] = "true"
        settings["mqttEnabled"] = "true"
        settings["cashPaymentEnabled"] = "true"
        settings["addlAuthReqdForCash"] = "false"
        settings["orderNumberInputEnabled"] = "true"
        settings["customerAuthDataCaptureEnabled"] = "true"
        settings["chequePaymentEnabled"] = "true"
        settings["amountCutOffForCustomerAuth"] = "10000"
        settings["eSignatureForNonCardEnabled"] = "false"
        settings["brandingInfo"] = ""
        settings["businessDiscountEnabled"] = "true"
        settings["boProductsEnabled"] = "true"
        settings["boCashbackEnabled"] = "true"
        settings["boInstantDiscountEnabled"] = "true"
        settings["paymentPromotionEnabled"] = "false"
        logger.debug(f"Precondition API details: {api_details}")
        response = APIProcessor.send_request(api_details=api_details)
        logger.debug(f"Precondition response: {response}")

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed Precondition setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=True, portalLog=False, cnpwareLog=False,
            middlewareLog=True, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # ── Test Execution ─────────────────────────────────────────────────────
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            # Step 1: Launch ReArch app and login if required
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login flow handled")

            # Step 2: Wait for initial home screen then click Payment History
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            logger.debug("Initial home screen loaded")

            home_page.click_payments_history()
            logger.debug("Clicked Payments History")

            # Wait for transaction history to load
            txn_history_page = ReArchTxnHistoryPage(app_driver)
            txn_history_page.wait_for_txn_list()
            logger.debug("Transaction history list loaded")

            # Step 3: Click on Date filter
            txn_history_page.click_filter_date()
            logger.debug("Date filter tapped")

            # Step 4: Click on Today
            time.sleep(2)
            txn_history_page.click_today()
            logger.debug("Today selected in Date filter")

            # Step 5: Click on Clear all
            txn_history_page.click_clear_all()
            logger.debug("Clear all clicked")

            # Step 6: Verify clear all worked — My Dashboard should be visible
            time.sleep(1)  # brief wait for UI to settle
            my_dashboard_visible = txn_history_page.is_element_visible(
                TxnHistoryLocators.btn_my_dashboard, time=10
            )
            logger.debug(f"My Dashboard visible after Clear all: {my_dashboard_visible}")

            # Verify Date filter is back (no active date chip)
            date_filter_visible = txn_history_page.is_element_visible(
                TxnHistoryLocators.btn_filter_date, time=10
            )
            logger.debug(f"Date filter button visible after Clear all: {date_filter_visible}")

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # ── Validation ─────────────────────────────────────────────────────────
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # ── App Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                expected_app_values = {
                    "my_dashboard": "VISIBLE",
                    "date_filter": "VISIBLE",
                }
                actual_app_values = {
                    "my_dashboard": "VISIBLE" if my_dashboard_visible else "NOT DISPLAYED",
                    "date_filter": "VISIBLE" if date_filter_visible else "NOT DISPLAYED",
                }
                logger.debug(f"expected_app_values: {expected_app_values}")
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        Configuration.executeFinallyBlock(testcase_id)
