import sys
import pytest

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_native_locators import HomeAmountLocators
from Utilities import ConfigReader, ResourceAssigner, Validator
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.appVal
def test_common_rearch_0012():
    """
    Sub Feature Code: UI_ReArch_Home_Verify_PaymentButtons_HDFC
    Sub Feature Description:
        Launch ReArch app, handle login only if the Select Environment screen
        appears (auto-login skips it), tap Collect Payment, then verify that
        both UPI and Card buttons are displayed on the amount entry screen.

    NL Source Steps:
      Preconditions:
        None

      Test Steps:
        1. launch rearch app and login (only if Select Environment screen appears)
        2. click on collect payment
        3. verify that both UPI and Card buttons are displayed

    Generated by: test_generator.md
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # ── Setup ──────────────────────────────────────────────────────────────
        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=False, portalLog=False, cnpwareLog=False,
            middlewareLog=False, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # ── Test Execution ─────────────────────────────────────────────────────
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            # Step 1: Launch ReArch app and handle login if required
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login flow handled")

            # Step 2: Wait for initial home screen and tap Collect Payment
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_collect_payment()
            logger.debug("Collect Payment tapped")

            # Wait for amount page to load
            home_page.wait_for_home_page_load()

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # ── Validation ─────────────────────────────────────────────────────────
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # ── App Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                # Step 3: Verify UPI and Card buttons are displayed
                upi_visible = str(home_page.is_element_visible(HomeAmountLocators.btn_upi, time=10))
                card_visible = str(home_page.is_element_visible(HomeAmountLocators.btn_card, time=10))
                logger.info(f"UPI button visible: {upi_visible}, Card button visible: {card_visible}")

                expected_app_values = {
                    "upi_button": "UPI",
                    "card_button": "Card",
                }
                actual_app_values = {
                    "upi_button": "UPI" if upi_visible == "True" else "NOT DISPLAYED",
                    "card_button": "Card" if card_visible == "True" else "NOT DISPLAYED",
                }
                logger.debug(f"expected_app_values: {expected_app_values}")
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        Configuration.executeFinallyBlock(testcase_id)
