import sys
import time

import pytest
from datetime import datetime

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_tip_page import ReArchTipPage
from PageFactory.ReArch.rearch_order_details_page import ReArchOrderDetailsPage
from PageFactory.ReArch.rearch_payment_method_page import ReArchPaymentMethodPage
from PageFactory.ReArch.rearch_cash_confirm_page import ReArchCashConfirmPage
from PageFactory.ReArch.rearch_complete_page import ReArchCompletePage
from PageFactory.ReArch.rearch_txn_history_page import ReArchTxnHistoryPage
from PageFactory.ReArch.rearch_txn_detail_page import ReArchTxnDetailPage
from PageFactory.ReArch.rearch_native_locators import TxnHistoryLocators
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
    Validator, date_time_converter, receipt_validator,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.apiVal
@pytest.mark.appVal
@pytest.mark.chargeSlipVal
def test_common_rearch_0045():
    """
    Sub Feature Code: UI_ReArch_PM_Cash_Tip_Success_HDFC
    Sub Feature Description:
        Launch ReArch app, apply preconditions (tipPercentage=15,
        multiTipPercentage=6,11,16), enter amount 515, add tip (6% = 31,
        total = 546), proceed via Cash payment, verify success, then
        validate via App (amount=546), API, and Charge Slip.

    NL Source Steps:
      Preconditions:
        - Apply org_settings (tipPercentage, multiTipPercentage, etc.)
        - Revert tipPercentage and multiTipPercentage on cleanup

      Test Steps:
        1.  launch rearch app and login if present
        2.  apply preconditions settings (refresh via Payment History)
        3.  wait for home page
        4.  enter amount as 515
        5.  click on Add Tip button
        6.  click on Done button
        7.  click on Proceed button (Order Details)
        8.  click on cash
        9.  click on confirm payment
        9.  click on Accept more payment
        10. do app validation, amount should be 546
        11. do api and chargeslip validation

    Generated by: test_generator.md, action_registry.yaml
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # ══════════════════════════════════════════════════════════════
        # SETUP
        # ══════════════════════════════════════════════════════════════
        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        # ── Preconditions ─────────────────────────────────────────────────
        logger.info(f"Starting Precondition setup for the test case: {testcase_id}")

        api_details = DBProcessor.get_api_details('org_settings_update', request_body={
            "username": portal_username,
            "password": portal_password,
            "entityName": "org",
            "settingForOrgCode": org_code,
        })
        settings = api_details["RequestBody"]["settings"]
        settings["autoLoginByTokenEnabled"] = "true"
        settings["enableDemandDraftDD"] = "true"
        settings["preAuthOption"] = "1"
        settings["cardPaymentEnabled"] = "true"
        settings["enableWebAppRevamp"] = "true"
        settings["p2pEnabled"] = "true"
        settings["mqttEnabled"] = "true"
        settings["cashPaymentEnabled"] = "true"
        settings["addlAuthReqdForCash"] = "false"
        settings["orderNumberInputEnabled"] = "true"
        settings["customerAuthDataCaptureEnabled"] = "true"
        settings["chequePaymentEnabled"] = "true"
        settings["tipEnabled"] = "true"
        settings["amountCutOffForCustomerAuth"] = "10000"
        settings["eSignatureForNonCardEnabled"] = "false"
        settings["brandingInfo"] = ""
        settings["tipPercentage"] = "15"
        settings["multiTipPercentage"] = "6, 11, 16"
        logger.debug(f"Precondition API details: {api_details}")
        response = APIProcessor.send_request(api_details=api_details)
        logger.debug(f"Precondition response: {response}")

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed Precondition setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=True, portalLog=False, cnpwareLog=False,
            middlewareLog=True, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # ══════════════════════════════════════════════════════════════
        # EXECUTION
        # ══════════════════════════════════════════════════════════════
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            base_amount = "515"
            total_amount = "546"  # 515 + 31 (6% tip)
            display_total_amount = total_amount + ".00"

            # Step 1: Launch ReArch app and login if present
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login flow handled")

            # Step 2-3: Initial home screen → Collect Payment → amount screen
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_collect_payment()
            home_page.wait_for_home_page_load()

            # Settings refresh: navigate to Payment History, wait for Dashboard, then back
            home_page.click_txn_history()
            txn_history_page = ReArchTxnHistoryPage(app_driver)
            txn_history_page.wait_for_txn_list()
            assert home_page.is_element_visible(TxnHistoryLocators.btn_my_dashboard, time=10), \
                "My Dashboard button should be visible on Payment History"
            logger.debug("Payment History loaded with Dashboard visible — settings refreshed")
            home_page.go_back()
            home_page.wait_for_home_page_load()
            logger.debug("Navigated back from Payment History")

            # Step 4: Enter amount 515
            home_page.enter_amount(base_amount)
            logger.debug(f"Amount {base_amount} entered")

            # Step 5: Click Add Tip
            home_page.click_add_tip()
            logger.debug("Add Tip tapped")

            # Wait for tip screen
            tip_page = ReArchTipPage(app_driver)
            tip_page.wait_for_tip_screen()

            # Select 6% tip (₹31) → total = 515 + 31 = 546
            tip_page.click_6_percent()
            logger.debug("Selected 6% tip (₹31)")

            # Step 6: Click Done
            tip_page.click_done()
            logger.debug("Done on tip screen — tip applied, total = 546")

            # Navigate to Cash payment: ⋯ → Order Details → Proceed → Payment Methods → Cash
            # home_page.click_more_payment_options()
            logger.debug("More Payment Options (⋯) tapped")

            # Step 7: Click Proceed on Order Details overlay
            order_details_page = ReArchOrderDetailsPage(app_driver)
            # order_details_page.wait_for_order_details_screen()
            order_details_page.click_proceed()
            logger.debug("Order Details: clicked Proceed")

            # Step 8: Click Cash from Payment Methods
            payment_method_page = ReArchPaymentMethodPage(app_driver)
            # payment_method_page.wait_for_payment_methods()

            payment_method_page.click_cash()
            logger.debug("Cash selected from payment methods")

            # Step 9: Click Confirm Payment
            cash_confirm_page = ReArchCashConfirmPage(app_driver)
            cash_confirm_page.wait_for_cash_confirm_screen()
            cash_confirm_page.click_confirm_payment()
            logger.debug("Cash payment confirmed")

            # Verify payment success
            complete_page = ReArchCompletePage(app_driver)
            complete_page.wait_for_success_screen()
            logger.info("Payment Successful screen confirmed")

            # Resolve txn from DB
            query = (
                f"select id, created_time, posting_date "
                f"from txn "
                f"where org_code='{org_code}' AND username='{app_username}' "
                f"AND payment_mode='CASH' "
                f"order by created_time desc limit 1;"
            )
            logger.debug(f"Query to resolve txn_id: {query}")
            result = DBProcessor.getValueFromDB(query)
            txn_id       = result["id"].values[0]
            created_time = result["created_time"].values[0]
            posting_date = result["posting_date"].values[0]
            logger.debug(
                f"Resolved txn_id={txn_id}, created_time={created_time}, "
                f"posting_date={posting_date}"
            )

            # Click Accept more payments
            complete_page.click_proceed_to_home()
            logger.debug("Clicked Accept More Payments")

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in try block of testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # ══════════════════════════════════════════════════════════════
        # VALIDATION
        # ══════════════════════════════════════════════════════════════
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # ── App Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                date_and_time = date_time_converter.to_rearch_app_format(created_time)
                expected_app_values = {
                    "txn_status": "Payment Settled",  # TODO: verify exact text on first run
                    "txn_id":     txn_id,
                    "date":       date_and_time,
                    "amount":     display_total_amount,
                }
                logger.debug(f"expected_app_values: {expected_app_values}")

                # Navigate to TxnDetail
                home_page.wait_for_home_page_load()
                home_page.click_txn_history()
                txn_history_page.wait_for_txn_list()
                txn_history_page.click_on_transaction_by_txn_id(txn_id=txn_id)

                txn_detail_page = ReArchTxnDetailPage(app_driver)

                # Fetch and assert transaction fields
                time.sleep(2)
                app_txn_id     = txn_detail_page.fetch_payment_id()
                app_txn_status = txn_detail_page.fetch_status(display_total_amount)
                app_date_time  = txn_detail_page.fetch_date_time()
                app_amount     = txn_detail_page.fetch_amount(display_total_amount)
                logger.info(
                    f"App txn_id={app_txn_id}, date_time={app_date_time}, "
                    f"app_txn_status={app_txn_status}, app_amount={app_amount}"
                )

                actual_app_values = {
                    "txn_status": app_txn_status,
                    "txn_id":     app_txn_id,
                    "date":       app_date_time,
                    "amount":     app_amount,
                }
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

                assert app_txn_id, "Payment ID should not be empty"
                assert app_date_time, "Date & Time should not be empty"

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        # ── API Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "api_validation") == "True":
            logger.info(f"Started API validation for the test case: {testcase_id}")
            try:
                date = date_time_converter.db_datetime(created_time)
                expected_api_values = {
                    "pmt_status":    "AUTHORIZED",
                    "txn_amt":       float(total_amount),
                    "pmt_mode":      "CASH",
                    "txn_type":      "CHARGE",
                    "acquirer_code": "NONE",
                    "org_code":      org_code,
                    "date":          date,
                }
                logger.debug(f"expected_api_values: {expected_api_values}")

                api_details = DBProcessor.get_api_details(
                    "txnlist",
                    request_body={"username": app_username, "password": app_password},
                )
                response = APIProcessor.send_request(api_details)
                logger.debug("txnlist API response received")

                txn_data = next(
                    (x for x in response["txns"] if x["txnId"] == txn_id), None
                )
                if txn_data is None:
                    raise ValueError(f"txn_id '{txn_id}' not found in txnlist API response")
                logger.debug(f"Filtered txn entry from txnlist: {txn_data}")

                actual_api_values = {
                    "pmt_status":    txn_data["status"],
                    "txn_amt":       float(txn_data["amount"]),
                    "pmt_mode":      txn_data["paymentMode"],
                    "txn_type":      txn_data["txnType"],
                    "acquirer_code": txn_data["acquirerCode"],
                    "org_code":      txn_data["orgCode"],
                    "date":          date_time_converter.from_api_to_datetime_format(
                                         txn_data["createdTime"]
                                     ),
                }
                logger.debug(f"actual_api_values: {actual_api_values}")
                Validator.validationAgainstAPI(
                    expectedAPI=expected_api_values, actualAPI=actual_api_values
                )

            except Exception as e:
                Configuration.perform_api_val_exception(testcase_id, e)
            logger.info(f"Completed API validation for the test case: {testcase_id}")

        # ── Charge Slip Validation ────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "charge_slip_validation") == "True":
            logger.info(f"Started ChargeSlip validation for the test case: {testcase_id}")
            try:
                txn_date, txn_time = date_time_converter.to_chargeslip_format(posting_date_db=posting_date)
                expected_charge_slip_values = {
                    "PAID BY:":     "CASH",
                    "BASE AMOUNT:": "Rs." + total_amount + ".00",
                    "date":         txn_date,
                    "time":         txn_time,
                }
                logger.debug(f"expected_charge_slip_values: {expected_charge_slip_values}")
                receipt_validator.perform_charge_slip_validations(
                    txn_id=txn_id,
                    credentials={"username": app_username, "password": app_password},
                    expected_details=expected_charge_slip_values,
                )

            except Exception as e:
                Configuration.perform_charge_slip_val_exception(testcase_id, e)
            logger.info(f"Completed ChargeSlip validation for the test case: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        # Revert only tipPercentage and multiTipPercentage
        try:
            revert_api_details = DBProcessor.get_api_details('org_settings_update', request_body={
                "username": portal_username,
                "password": portal_password,
                "entityName": "org",
                "settingForOrgCode": org_code,
            })
            revert_settings = revert_api_details["RequestBody"]["settings"]
            revert_settings["tipPercentage"] = ""
            revert_settings["multiTipPercentage"] = ""
            APIProcessor.send_request(api_details=revert_api_details)
            logger.info("Reverted tipPercentage and multiTipPercentage to empty")
        except Exception as e:
            logger.error(f"Failed to revert tip settings: {e}")

        Configuration.executeFinallyBlock(testcase_id)
