import sys
import random
import time

import pytest
from datetime import datetime

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_order_details_page import ReArchOrderDetailsPage
from PageFactory.ReArch.rearch_card_type_page import ReArchCardTypePage
from PageFactory.ReArch.rearch_complete_page import ReArchCompletePage
from PageFactory.ReArch.rearch_txn_history_page import ReArchTxnHistoryPage
from PageFactory.ReArch.rearch_txn_detail_page import ReArchTxnDetailPage
from PageFactory.ReArch.rearch_native_locators import TxnHistoryLocators, VoidLocators
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
    Validator, date_time_converter, receipt_validator,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.apiVal
@pytest.mark.appVal
@pytest.mark.chargeSlipVal
def test_common_rearch_0042():
    """
    Sub Feature Code: UI_ReArch_PM_Card_Void_RuPay_Debit_EMV
    Sub Feature Description:
        Launch ReArch app, enter a random amount (90-150), select Card,
        proceed through Order Details, select RuPay Debit (EMV), verify success,
        navigate to txn details, perform Void Amount flow (enter password,
        continue, void payment, done), then search for same txn and validate
        via App, API, and Charge Slip.

    NL Source Steps:
      Preconditions:
        - Apply org_settings (autoLoginByTokenEnabled, cardPaymentEnabled, etc.)
        - Do NOT revert settings on cleanup

      Test Steps:
        1.  launch rearch app and login if present
        2.  apply preconditions settings (refresh via Payment History)
        3.  wait for home page
        4.  enter amount between 90 to 150
        5.  select card
        6.  click on proceed on the next screen (order details overlay)
        7.  select RuPay Debit (EMV)
        8.  navigate to txn details
        9.  click on button Void Amount
        10. enter app_password in Enter Password Screen
        11. click on continue button
        12. click on Void Payment button
        13. click on Done button
        14. click on search button and search for same txn and do app validation
        15. continue with api and chargeslip validation

    Generated by: test_generator.md, action_registry.yaml
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # ══════════════════════════════════════════════════════════════
        # SETUP
        # ══════════════════════════════════════════════════════════════
        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        # ── Preconditions (org_settings_update — DO NOT REVERT) ───────────
        logger.info(f"Starting Precondition setup for the test case: {testcase_id}")

        api_details = DBProcessor.get_api_details('org_settings_update', request_body={
            "username": portal_username,
            "password": portal_password,
            "entityName": "org",
            "settingForOrgCode": org_code,
        })
        settings = api_details["RequestBody"]["settings"]
        settings["autoLoginByTokenEnabled"] = "true"
        settings["enableDemandDraftDD"] = "true"
        settings["preAuthOption"] = "1"
        settings["cardPaymentEnabled"] = "true"
        settings["enableWebAppRevamp"] = "true"
        settings["p2pEnabled"] = "true"
        settings["mqttEnabled"] = "true"
        settings["cashPaymentEnabled"] = "true"
        settings["addlAuthReqdForCash"] = "false"
        settings["orderNumberInputEnabled"] = "true"
        settings["customerAuthDataCaptureEnabled"] = "true"
        settings["chequePaymentEnabled"] = "true"
        settings["amountCutOffForCustomerAuth"] = "10000"
        settings["eSignatureForNonCardEnabled"] = "false"
        settings["brandingInfo"] = ""
        settings["businessDiscountEnabled"] = "true"
        settings["boProductsEnabled"] = "true"
        settings["boCashbackEnabled"] = "true"
        settings["boInstantDiscountEnabled"] = "true"
        logger.debug(f"Precondition API details: {api_details}")
        response = APIProcessor.send_request(api_details=api_details)
        logger.debug(f"Precondition response: {response}")

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed Precondition setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=True, portalLog=False, cnpwareLog=False,
            middlewareLog=True, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # ══════════════════════════════════════════════════════════════
        # EXECUTION
        # ══════════════════════════════════════════════════════════════
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            amount = str(random.randint(90, 150))
            display_amount = amount + ".00"
            order_id = f"{datetime.now().strftime('%m%d%H%M%S')}{testcase_id[-4:]}"
            logger.debug(f"amount={amount}, display_amount={display_amount}, order_id={order_id}")

            # Step 1: Launch ReArch app and login if present
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login completed (auto-login path)")

            # Steps 2-3: Initial home screen → Collect Payment → amount screen
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            home_page.click_collect_payment()
            home_page.wait_for_home_page_load()

            # Settings refresh: navigate to Payment History, wait for Dashboard, then back
            # (auto-login bypasses fresh login, so preconditions aren't picked up without this)
            home_page.click_txn_history()
            txn_history_page = ReArchTxnHistoryPage(app_driver)
            txn_history_page.wait_for_txn_list()
            assert home_page.is_element_visible(TxnHistoryLocators.btn_my_dashboard, time=10), \
                "My Dashboard button should be visible on Payment History"
            logger.debug("Payment History loaded with Dashboard visible — settings refreshed")
            home_page.go_back()
            home_page.wait_for_home_page_load()
            logger.debug("Navigated back from Payment History")

            # Step 4: Enter amount between 90 to 150
            home_page.enter_amount(amount)
            logger.debug(f"Amount {amount} entered")

            # Step 5: Select Card
            home_page.click_pay_by_card()
            logger.debug("Card payment method selected")

            # Step 6: Click proceed on Order Details overlay
            order_details_page = ReArchOrderDetailsPage(app_driver)
            order_details_page.wait_for_order_details_screen()
            order_details_page.click_proceed()
            logger.debug("Order Details: clicked Proceed")

            # Step 7: Select Visa Debit (EMV)
            card_type_page = ReArchCardTypePage(app_driver)
            card_type_page.wait_for_card_type_screen()
            card_type_page.click_visa_debit_emv()
            logger.debug("Selected Visa Debit (EMV)")

            # Wait for payment success screen
            complete_page = ReArchCompletePage(app_driver)
            complete_page.wait_for_success_screen()
            logger.info("Payment Successful screen confirmed")

            # Resolve txn from DB (initial AUTHORIZED state)
            query = (
                f"select id, created_time, posting_date, rr_number, auth_code "
                f"from txn "
                f"where org_code='{org_code}' AND username='{app_username}' "
                f"AND payment_mode='CARD' "
                f"order by created_time desc limit 1;"
            )
            logger.debug(f"Query to resolve txn_id: {query}")
            result = DBProcessor.getValueFromDB(query)
            txn_id       = result["id"].values[0]
            created_time = result["created_time"].values[0]
            posting_date = result["posting_date"].values[0]
            rrn          = str(result["rr_number"].values[0])
            auth_code    = str(result["auth_code"].values[0])
            logger.debug(
                f"Resolved txn_id={txn_id}, created_time={created_time}, "
                f"posting_date={posting_date}, rrn={rrn}, auth_code={auth_code}"
            )

            # Step 8: Navigate to txn details (Accept more payments → Home → TxnHistory → TxnDetail)
            complete_page.click_proceed_to_home()
            home_page.wait_for_home_page_load()
            home_page.click_txn_history()
            txn_history_page.wait_for_txn_list()
            txn_history_page.click_on_transaction_by_txn_id(txn_id=txn_id)
            logger.debug("Navigated to txn detail page")

            # Step 9: Click Void Amount button
            txn_detail_page = ReArchTxnDetailPage(app_driver)
            txn_detail_page.click_void_amount()
            logger.debug("Clicked Void Amount button")

            # Step 10-11: Enter password in Enter Password Screen and click Continue
            txn_detail_page.wait_for_element(VoidLocators.lbl_enter_password)
            txn_detail_page.perform_sendkeys(VoidLocators.txt_password, app_password)
            txn_detail_page.perform_click(VoidLocators.btn_continue)
            logger.debug("Entered password and clicked Continue")

            # Step 12: Click Void Payment button
            txn_detail_page.perform_click(VoidLocators.btn_void_payment)
            logger.debug("Clicked Void Payment button")

            # Step 13: Click Done button
            txn_detail_page.perform_click(VoidLocators.btn_done)
            logger.debug("Clicked Done button — void completed")

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in try block of testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # ══════════════════════════════════════════════════════════════
        # VALIDATION
        # ══════════════════════════════════════════════════════════════
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # ── App Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                date_and_time = date_time_converter.to_rearch_app_format(created_time)
                expected_app_values = {
                    "txn_status": "Payment Voided",  # TODO: verify exact text on first run
                    "txn_id":     txn_id,
                    "date":       date_and_time,
                    "amount":     display_amount,
                }
                logger.debug(f"expected_app_values: {expected_app_values}")

                # Step 14: After void Done, navigate to txn history → search for same txn
                # home_page.wait_for_home_page_load()

                # home_page.click_txn_history()
                # txn_history_page.wait_for_txn_list()
                txn_history_page.click_on_transaction_by_txn_id(txn_id=txn_id)

                txn_detail_page = ReArchTxnDetailPage(app_driver)

                # Fetch and assert transaction fields
                app_txn_id     = txn_detail_page.fetch_payment_id()
                app_txn_status = txn_detail_page.fetch_status(display_amount)
                app_date_time  = txn_detail_page.fetch_date_time()
                app_amount     = txn_detail_page.fetch_amount(display_amount)
                logger.info(
                    f"App txn_id={app_txn_id}, date_time={app_date_time}, "
                    f"app_txn_status={app_txn_status}, app_amount={app_amount}"
                )

                actual_app_values = {
                    "txn_status": app_txn_status,
                    "txn_id":     app_txn_id,
                    "date":       app_date_time,
                    "amount":     app_amount,
                }
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

                assert app_txn_id, "Payment ID should not be empty"
                assert app_date_time, "Date & Time should not be empty"

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        # ── API Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "api_validation") == "True":
            logger.info(f"Started API validation for the test case: {testcase_id}")
            try:
                date = date_time_converter.db_datetime(created_time)
                expected_api_values = {
                    "pmt_status":    "VOIDED",
                    "txn_amt":       float(amount),
                    "pmt_mode":      "CARD",
                    "pmt_state":     "VOIDED",
                    "settle_status": "SETTLED",  # TODO: verify on first run — may differ for voided txns
                    "acquirer_code": "HDFC",     # TODO: verify acquirer for DUMMY RuPay
                    "issuer_code":   "HDFC",     # TODO: verify issuer for DUMMY RuPay
                    "txn_type":      "CHARGE",
                    "org_code":      org_code,
                    "rrn":           rrn,
                    "date":          date,
                    "pmt_card_brand": "VISA",
                    "pmt_card_type":  "DEBIT",
                    "card_txn_type":  "EMV",
                }
                logger.debug(f"expected_api_values: {expected_api_values}")

                api_details = DBProcessor.get_api_details(
                    "txnlist",
                    request_body={"username": app_username, "password": app_password},
                )
                response = APIProcessor.send_request(api_details)
                logger.debug("txnlist API response received")

                txn_data = next(
                    (x for x in response["txns"] if x["txnId"] == txn_id), None
                )
                if txn_data is None:
                    raise ValueError(f"txn_id '{txn_id}' not found in txnlist API response")
                logger.debug(f"Filtered txn entry from txnlist: {txn_data}")

                actual_api_values = {
                    "pmt_status":    txn_data["status"],
                    "txn_amt":       float(txn_data["amount"]),
                    "pmt_mode":      txn_data["paymentMode"],
                    "pmt_state":     txn_data["states"][0],
                    "settle_status": txn_data["settlementStatus"],
                    "acquirer_code": txn_data["acquirerCode"],
                    "issuer_code":   txn_data["issuerCode"],
                    "txn_type":      txn_data["txnType"],
                    "org_code":      txn_data["orgCode"],
                    "rrn":           str(txn_data["rrNumber"]),
                    "date":          date_time_converter.from_api_to_datetime_format(
                                         txn_data["createdTime"]
                                     ),
                    "pmt_card_brand": txn_data["paymentCardBrand"],
                    "pmt_card_type":  txn_data["paymentCardType"],
                    "card_txn_type":  txn_data["cardTxnTypeDesc"],
                }
                logger.debug(f"actual_api_values: {actual_api_values}")
                Validator.validationAgainstAPI(
                    expectedAPI=expected_api_values, actualAPI=actual_api_values
                )

            except Exception as e:
                Configuration.perform_api_val_exception(testcase_id, e)
            logger.info(f"Completed API validation for the test case: {testcase_id}")

        # ── Charge Slip Validation ────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "charge_slip_validation") == "True":
            logger.info(f"Started ChargeSlip validation for the test case: {testcase_id}")
            try:
                txn_date, txn_time = date_time_converter.to_chargeslip_format(posting_date_db=posting_date)
                expected_charge_slip_values = {
                    "RRN":            rrn,
                    "AUTH CODE":      auth_code,
                    "BASE AMOUNT:":   "Rs." + str(amount) + ".00",
                    "date":           txn_date,
                    "time":           txn_time,
                    "payment_option": "VOID SALE",  # TODO: verify on first run — may differ in ReArch
                }
                logger.debug(f"expected_charge_slip_values: {expected_charge_slip_values}")
                receipt_validator.perform_charge_slip_validations(
                    txn_id=txn_id,
                    credentials={"username": app_username, "password": app_password},
                    expected_details=expected_charge_slip_values,
                )

            except Exception as e:
                Configuration.perform_charge_slip_val_exception(testcase_id, e)
            logger.info(f"Completed ChargeSlip validation for the test case: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        # No settings revert — as per user instruction
        Configuration.executeFinallyBlock(testcase_id)
