import sys
import random
import time
import pytest
from datetime import datetime

from appium.webdriver.common.appiumby import AppiumBy

from Configuration import Configuration, TestSuiteSetup
from DataProvider import GlobalVariables
from PageFactory.ReArch.rearch_login_page import ReArchLoginPage
from PageFactory.ReArch.rearch_home_page import ReArchHomePage
from PageFactory.ReArch.rearch_order_details_page import ReArchOrderDetailsPage
from PageFactory.ReArch.rearch_payment_method_page import ReArchPaymentMethodPage
from PageFactory.ReArch.rearch_cash_confirm_page import ReArchCashConfirmPage
from PageFactory.ReArch.rearch_complete_page import ReArchCompletePage
from PageFactory.ReArch.rearch_txn_history_page import ReArchTxnHistoryPage
from PageFactory.ReArch.rearch_native_locators import TxnHistoryLocators
from Utilities import (
    APIProcessor, ConfigReader, DBProcessor, ResourceAssigner,
    Validator,
)
from Utilities.execution_log_processor import EzeAutoLogger

logger = EzeAutoLogger(__name__)


@pytest.mark.usefixtures("log_on_success", "method_setup")
@pytest.mark.appVal
def test_common_rearch_0040():
    """
    Sub Feature Code: UI_ReArch_Home_Verify_TxnHistoryFilter_HDFC
    Sub Feature Description:
        Launch ReArch app, verify Razorpay logo is present on the initial
        home screen, perform a cash payment (200-300), then navigate to
        transaction history and verify the Method filter (Cash) and Status
        filter (Settled) work correctly by checking that the filter text
        appears on the page after applying each filter.

    NL Source Steps:
      Preconditions:
        1. update org_settings: autoLoginByTokenEnabled = true
        2. update org_settings: enableDemandDraftDD = true
        3. update org_settings: preAuthOption = 1
        4. update org_settings: cardPaymentEnabled = true
        5. update org_settings: enableWebAppRevamp = true
        6. update org_settings: p2pEnabled = true
        7. update org_settings: mqttEnabled = true
        8. update org_settings: cashPaymentEnabled = true
        9. update org_settings: addlAuthReqdForCash = false
        10. update org_settings: orderNumberInputEnabled = true
        11. update org_settings: customerAuthDataCaptureEnabled = true
        12. update org_settings: chequePaymentEnabled = true
        13. update org_settings: amountCutOffForCustomerAuth = 10000
        14. update org_settings: eSignatureForNonCardEnabled = false
        15. update org_settings: brandingInfo = ""
        16. update org_settings: businessDiscountEnabled = true
        17. update org_settings: boProductsEnabled = true
        18. update org_settings: boCashbackEnabled = true
        19. update org_settings: boInstantDiscountEnabled = true
        20. update org_settings: paymentPromotionEnabled = false

      Test Steps:
        1.  launch rearch app and login if present
        2.  wait for collect payment page to load
        3.  verify default "Razorpay" logo is present
        4.  click on collect payment, enter amount between 200-300
        5.  click on overlay button
        6.  click on proceed button
        7.  click on cash
        8.  click on confirm payment
        9.  click on accept more payment
        10. navigate to txn history details screen
        11. click on method
        12. click on cash
        13. click on apply button
        14. verify in current page "Cash" text is present
        15. click on status
        16. click on Settled
        17. verify in current page "Settled" text is present

    Generated by: test_generator.md, action_registry.yaml
    """
    try:
        testcase_id = sys._getframe().f_code.co_name
        GlobalVariables.time_calc.setup.resume()
        logger.debug(f"Setup Timer resumed in testcase function: {testcase_id}")

        # ── Setup ──────────────────────────────────────────────────────────────
        logger.info(f"Reverting back all the settings that were done as preconditions: {testcase_id}")

        app_cred = ResourceAssigner.getAppUserCredentials(testcase_id)
        logger.debug(f"App credentials fetched: {app_cred}")
        app_username = app_cred["Username"]
        app_password = app_cred["Password"]

        portal_cred = ResourceAssigner.getPortalUserCredentials(testcase_id)
        logger.debug(f"Portal credentials fetched: {portal_cred}")
        portal_username = portal_cred["Username"]
        portal_password = portal_cred["Password"]

        query = f"select org_code from org_employee where username='{app_username}';"
        logger.debug(f"Query to fetch org_code: {query}")
        result = DBProcessor.getValueFromDB(query)
        org_code = result["org_code"].values[0]
        logger.debug(f"org_code: {org_code}")

        logger.info(f"Reverted back all the settings that were done as preconditions: {testcase_id}")

        # ── PreConditions ──────────────────────────────────────────────────────
        logger.info(f"Starting Precondition setup for the test case: {testcase_id}")

        api_details = DBProcessor.get_api_details('org_settings_update', request_body={
            "username": portal_username,
            "password": portal_password,
            "entityName": "org",
            "settingForOrgCode": org_code,
        })
        api_details["RequestBody"]["settings"]["autoLoginByTokenEnabled"] = "true"
        api_details["RequestBody"]["settings"]["enableDemandDraftDD"] = "true"
        api_details["RequestBody"]["settings"]["preAuthOption"] = "1"
        api_details["RequestBody"]["settings"]["cardPaymentEnabled"] = "true"
        api_details["RequestBody"]["settings"]["enableWebAppRevamp"] = "true"
        api_details["RequestBody"]["settings"]["p2pEnabled"] = "true"
        api_details["RequestBody"]["settings"]["mqttEnabled"] = "true"
        api_details["RequestBody"]["settings"]["cashPaymentEnabled"] = "true"
        api_details["RequestBody"]["settings"]["addlAuthReqdForCash"] = "false"
        api_details["RequestBody"]["settings"]["orderNumberInputEnabled"] = "true"
        api_details["RequestBody"]["settings"]["customerAuthDataCaptureEnabled"] = "true"
        api_details["RequestBody"]["settings"]["chequePaymentEnabled"] = "true"
        api_details["RequestBody"]["settings"]["amountCutOffForCustomerAuth"] = "10000"
        api_details["RequestBody"]["settings"]["eSignatureForNonCardEnabled"] = "false"
        api_details["RequestBody"]["settings"]["brandingInfo"] = ""
        api_details["RequestBody"]["settings"]["businessDiscountEnabled"] = "true"
        api_details["RequestBody"]["settings"]["boProductsEnabled"] = "true"
        api_details["RequestBody"]["settings"]["boCashbackEnabled"] = "true"
        api_details["RequestBody"]["settings"]["boInstantDiscountEnabled"] = "true"
        api_details["RequestBody"]["settings"]["paymentPromotionEnabled"] = "false"
        logger.debug(f"Precondition API details: {api_details}")
        response = APIProcessor.send_request(api_details=api_details)
        logger.debug(f"Precondition response: {response}")

        GlobalVariables.setupCompletedSuccessfully = True
        logger.info(f"Completed Precondition setup for the test case: {testcase_id}")

        Configuration.configureLogCaptureVariables(
            apiLog=True, portalLog=False, cnpwareLog=False,
            middlewareLog=True, config_log=False,
        )

        GlobalVariables.time_calc.setup.end()
        logger.debug(f"Setup Timer ended in testcase function: {testcase_id}")

        # ── Test Execution ─────────────────────────────────────────────────────
        try:
            logger.info(f"Starting execution for the test case: {testcase_id}")
            GlobalVariables.time_calc.execution.start()
            logger.debug(f"Execution Timer started in testcase function: {testcase_id}")

            amount = str(random.randint(200, 300))
            logger.debug(f"amount={amount}")

            # Step 1: Launch ReArch app and login if required
            app_driver = TestSuiteSetup.initialize_rearch_driver(testcase_id)
            login_page = ReArchLoginPage(app_driver)
            login_page.perform_login_if_required(app_username, app_password)
            logger.debug("Login flow handled")

            # Step 2: Wait for initial home screen (Collect Payment page)
            home_page = ReArchHomePage(app_driver)
            home_page.wait_for_initial_home_screen()
            logger.debug("Initial home screen loaded")

            # Step 3: Check Razorpay logo presence (store result for validation)
            razorpay_logo_visible = home_page.is_element_visible(
                (AppiumBy.XPATH, "//android.widget.Image[@text='e91cc2003e6491b7f659']"), time=10
            )
            logger.debug(f"Razorpay logo visible: {razorpay_logo_visible}")

            # Step 4: Click Collect Payment
            home_page.click_collect_payment()
            logger.debug("Collect Payment tapped")

            # Refresh settings: navigate to Payment History, wait for Dashboard, then back
            # (auto-login bypasses fresh login, so preconditions aren't picked up without this)
            home_page.wait_for_home_page_load()
            home_page.click_txn_history()
            txn_history_page = ReArchTxnHistoryPage(app_driver)
            txn_history_page.wait_for_txn_list()
            home_page.wait_for_element(TxnHistoryLocators.btn_my_dashboard, time=10)
            logger.debug("Payment History loaded with Dashboard visible — settings refreshed")
            home_page.go_back()
            logger.debug("Navigated back from Payment History")

            # Step 4 (cont): Enter amount (200–300)
            home_page.wait_for_home_page_load()
            home_page.enter_amount(amount)
            logger.debug(f"Amount {amount} entered")

            # Step 5: Tap overlay button (⋯ More Payment Options)
            home_page.click_more_payment_options()
            logger.debug("More Payment Options (⋯) tapped")

            # Step 6: Order Details overlay → click Proceed
            order_details_page = ReArchOrderDetailsPage(app_driver)
            order_details_page.wait_for_order_details_screen()
            order_details_page.click_proceed()
            logger.debug("Order Details: clicked Proceed")

            # Step 7: Click Cash from payment methods overlay
            payment_method_page = ReArchPaymentMethodPage(app_driver)
            payment_method_page.wait_for_payment_methods()
            payment_method_page.scroll_to_text("Cash")
            payment_method_page.click_cash()
            logger.debug("Cash selected from payment methods")

            # Step 8: Cash Confirm screen → Confirm Payment
            cash_confirm_page = ReArchCashConfirmPage(app_driver)
            cash_confirm_page.wait_for_cash_confirm_screen()
            cash_confirm_page.click_confirm_payment()
            logger.debug("Cash payment confirmed")

            # Verify payment success screen
            complete_page = ReArchCompletePage(app_driver)
            complete_page.wait_for_success_screen()
            logger.info("Payment Successful screen confirmed")

            # Step 9: Click Accept More Payments → back to home
            complete_page.click_proceed_to_home()
            logger.debug("Clicked Accept More Payments")

            # Step 10: Navigate to txn history details screen
            home_page.wait_for_initial_home_screen()
            home_page.click_transactions()
            logger.debug("Navigated to Transaction History")

            txn_history_page = ReArchTxnHistoryPage(app_driver)
            txn_history_page.wait_for_txn_list()
            logger.debug("Transaction history list loaded")

            # Step 11: Click on Method filter
            txn_history_page.click_filter_method()
            logger.debug("Method filter tapped")

            # Step 12: Click on Cash option
            txn_history_page.select_filter_option("Cash")
            logger.debug("Cash filter option selected")

            # Step 13: Click on Apply button
            txn_history_page.click_apply_filter()
            logger.debug("Apply filter clicked")

            # Store Cash filter verification result
            time.sleep(1)  # brief wait for filter to apply
            cash_filter_visible = txn_history_page.is_filter_text_displayed("Cash", timeout=10)
            logger.debug(f"Cash filter text visible: {cash_filter_visible}")

            # Step 15: Click on Status filter
            txn_history_page.click_filter_status()
            logger.debug("Status filter tapped")

            # Step 16: Click on Settled option
            txn_history_page.select_filter_option("Settled")
            logger.debug("Settled filter option selected")

            txn_history_page.click_apply_filter()
            logger.debug("Apply filter clicked")

            # Store Settled filter verification result
            time.sleep(1)  # brief wait for filter to apply
            settled_filter_visible = txn_history_page.is_filter_text_displayed("Settled", timeout=10)
            logger.debug(f"Settled filter text visible: {settled_filter_visible}")

            GlobalVariables.EXCEL_TC_Execution = "Pass"
            GlobalVariables.time_calc.execution.pause()
            logger.debug(f"Execution Timer paused in testcase function: {testcase_id}")
            logger.info(f"Execution is completed for the test case: {testcase_id}")

        except Exception as e:
            Configuration.perform_exe_exception(testcase_id)
            pytest.fail("Test case execution failed due to the exception - " + str(e))

        # ── Validation ─────────────────────────────────────────────────────────
        logger.info(f"Starting Validation for the test case: {testcase_id}")
        GlobalVariables.time_calc.validation.start()
        logger.debug(f"Validation Timer started in testcase function: {testcase_id}")

        # ── App Validation ────────────────────────────────────────────────────
        if ConfigReader.read_config("Validations", "app_validation") == "True":
            logger.info(f"Started APP validation for the test case: {testcase_id}")
            try:
                expected_app_values = {
                    "razorpay_logo": "Razorpay",
                    "cash_filter": "Cash",
                    "settled_filter": "Settled",
                }
                actual_app_values = {
                    "razorpay_logo": "Razorpay" if razorpay_logo_visible else "NOT DISPLAYED",
                    "cash_filter": "Cash" if cash_filter_visible else "NOT DISPLAYED",
                    "settled_filter": "Settled" if settled_filter_visible else "NOT DISPLAYED",
                }
                logger.debug(f"expected_app_values: {expected_app_values}")
                logger.debug(f"actual_app_values: {actual_app_values}")
                Validator.validateAgainstAPP(
                    expectedApp=expected_app_values, actualApp=actual_app_values
                )

            except Exception as e:
                Configuration.perform_app_val_exception(testcase_id, e)
            logger.info(f"Completed APP validation for the test case: {testcase_id}")

        GlobalVariables.time_calc.validation.end()
        logger.debug(f"Validation Timer ended in testcase function: {testcase_id}")
        logger.info(f"Completed Validation for the test case: {testcase_id}")

    finally:
        Configuration.executeFinallyBlock(testcase_id)
