EZETAP_LOGO_THRESHOLD: 0.39
BANK_LOGO_THRESHOLD: 0.8
BROWSER_HEADLESS_MODE: false
BROWSER_WIDTH: 400
BROWSER_HEIGHT: 500
LOWER_SECTION_LOGOS:
- ezetap
- fiserv.ezetap
COMPANY_LOGO_MAX_MSE: 2.0
BANK_LOGO_MAX_MSE: 0.0
