[System]
automation_suite_path =/home/ezetap-10182/Downloads/EzeAuto

[APIs]
env=DEV11
baseUrl=https://dev11.ezetap.com
login=/api/2.0/auth/login/
portalLogin=/portal/login/
cashPayment=/api/2.0/payment/cash
portalEditMerchant=/portal//merchants/AUTO_PYTHON_TRIAL/edit
txnList = /api/2.0/txn/list

[ExcelFiles]
FilePath_TestCasesDetail=/home/oem/PycharmProjects/EzeAuto_1/DataProvider/TestCasesDetail.xlsx
FilePath_testcases_surfaceUI = /home/oem/PycharmProjects/EzeAuto_1/DataProvider/TestCases_SurfaceUI.xlsx

[TestcaseDetails_ColumnNames]
colName_TestCaseID = Test Case ID
colName_FileName = File Name
colName_Execute = Execute
colName_TCexecution = TC Execution
colName_APIval = API Val
colName_DBval = DB Val
colName_Portalval = Portal Val
colName_Appval = App Val
colName_UIval = UI Val
colName_ExecutionTime = Execution Time (sec)
colName_ValidationTime = Validation Time (sec)
colName_LogCollTime = Log Coll Time (sec)
colName_TotalTime = Total Time (sec)


[Validations]
api_validation=True
db_validation=True
portal_validation=True
app_validation=True
ui_validation=True

rerun_at_the_end=True
rerun_immediately=False
rerun_count=1

api_rerun = True
db_rerun = True
portal_rerun = False
ui_rerun = False
app_rerun = True
exe_rerun = True


[logs]
;fetch_Logs=True

For_Passed_TCS_fetch_Logs=True
For_Failed_TCS_fetch_Logs=True

fetch_cnpware_Logs=True
fetch_middleware_Logs=True
fetch_api_Logs=True
fetch_portal_Logs=True

capturing_indivisually_Logs=False
capturing_allInOneFile_Logs=True

forEachRun_Capture_Logs=False
forLastRun_Capture_Logs=True

fetch_ss = True


[environment]
env=dev11
ip=192.168.3.81
username=vineethb
port=22
key_filename=/home/oem/.ssh/vineeth_ssh

[credentials]
#Branding--
username_AXIS = 7204644333
username_HDFC = 7204644666
username_EZETAP = 7204644777
#
username_dev11 = 1076810769
password_dev11 = A111111
username_portal = 9731545096
password_portal = A123456

#MultiLanguage
username_EngLang= 7204644777
username_HindiLang= 7204644999
username_langselection= 7204644000
#Common
Mobile_Number=9845698456
Email=manasav@gmail.com
Env="DEV11"
password = A123456
#APP Upgrade Username in demo1
username_demo1=9343706316
#cnp_user
username_cnptxn=7204644101
loginurl=https://dev11.ezetap.com/api/2.0/auth/login

[testdata]
org_code =VINEET_191036200
da_alert_message=Plese use any of the payments below all are working. Happy Shopping\n
promo_offer =Diwali Offers
transactions_by_date=13 April 2022

[path]
# For all the dev environments.
api_dev=/var/log/ezetap/api/api.log
portal_dev=/var/log/ezetap/portal/portal.log
middleware_dev=/var/log/ezetap/middleware/middleware.log
cnpware_dev=/home/ezetap/ezetap/microservers/cnpware/cnpware.log

# Except dev environment.
api=/var/log/ezetap1/demo1-api.log
portal=/var/log/ezetap1/portal/demo1-portal.log
middleware=/var/log/ezetap1/middleware/demo1-middleware.log
cnpware=/home/demo1/ezetap/microservers/cnpware/cnpware.log


[locators]
#Login Page
username_NAME=username
password_NAME=password
signIn_NAME=Submit

#Home Page or landing page
transactions_XPATH=//a[text()='Transactions ']
transactions_search_XPATH=//a[text()='Search']
users_XPATH=//a[@title='Users']
appkeysMenu_XPATH=//a[contains(text(),'App Keys')]
merchantsMenu_XPATH=//a[@title='Merchants']
btn_merchantName_XPATH=//button[text()='Clear Switch']/following-sibling::button[@class='filterToOrgCode btn btn-small btn-primary']
setupMenu_XPATH=//a[contains(text(),'Setup')]
merchantSearch_XPATH=//input[@placeholder='Search']
switchButton_XPATH=//a[contains(@href,'orgCode')]/..//button[contains(text(),'switch')]
orgSettings_XPATH=//img[@title='Org Settings' and @alt='Org Settings']
bulkUploads_XPATH=//a[contains(text(),'Bulk Uploads')]
bqrSettings_XPATH=//a[contains(text(),'Bharatqr Settings')]
upiSettings_XPATH=//a[contains(text(),'UPI Settings')]

#Search Transactions
type_XPATH=/html/body/div[1]/div[10]/div/div/div[4]/div[1]/div[1]/table/tbody/tr[1]/td[4]
status_XPATH=/html/body/div[1]/div[10]/div/div/div[4]/div[1]/div[1]/table/tbody/tr[1]/td[5]
amount_XPATH=/html/body/div[1]/div[10]/div/div/div[4]/div[1]/div[1]/table/tbody/tr[1]/td[6]
username_XPATH=/html/body/div[1]/div[10]/div/div/div[4]/div[1]/div[1]/table/tbody/tr[1]/td[7]
txnId_XPATH=/html/body/div[1]/div[10]/div/div/div[4]/div[1]/div[1]/table/tbody/tr[1]/td[9]



#Merchant Options
editMerchant_XPATH=//img[@title='Edit' and @alt='edit']


#User Options
editUser_XPATH=//a[@href='mobileNum/edit']

#Edit merchant page
radio_inactive_status_ID=status2
radio_active_status_ID=status1
btn_save_XPATH=//input[@type='submit']


#Edit User Page
txt_password_NAME=password
txt_confirmPassword_ID=confirmPassword
radio_user_inactive_status_ID=status2
radio_user_active_status_ID=status1
btn_next_ID=saveBtn



#Appkey page
btn_generate_appkey_XPATH=//button[contains(text(),'Generate App Key')]
dropdown_processCode_NAME=defaultProcessCode
txt_appkey_description_ID=add_description
txt_appkey_label_id=add_label
btn_add_appkey_XPATH=//div[@class='ui-dialog-buttonset']/button[text()='Generate App Key']

txt_editLabel_ID=edit_label
btn_saveChanges_XPATH=//button[text()='Save']



#Bulk uploads page under setup menu
btn_choose_file_user_creation_modification=//tr/td[text()='User Creation/Modification']/..//input[@name='file']


#BQR Settings page under setup menu
btn_create_bqr_acq_XPATH=//button[@class='btn btn-primary']
txt_visa_primary_id_NAME=visaMerchantIdPrimary
txt_master_primary_id_NAME=mastercardMerchantIdPrimary
txt_bqr_rupay_primary_id_NAME=npciMerchantIdPrimary
txt_bqr_ifsc_NAME=merchantIfsc
txt_bqr_acct_numb_NAME=merchantAccountNumber
txt_bqr_name_NAME=merchantName
txt_bqr_city_NAME=merchantCity
txt_bqr_pin_NAME=merchantPinCode
txt_bqr_category_code_NAME=merchantCategoryCode
txt_bqr_currency_code_NAME=currencyCode
txt_bqr_country_code_NAME=countryCode
drop_bqr_bankcode_NAME=bankCode
select_dummy_bankcode_XPATH=//a[contains(text(),'DUMMY')]
drop_bqr_status_NAME=status
select_active_status_XPATH=//a[contains(text(),'Active')]
btn_bqr_add_ID=addbtn

#UPI Settings page under setup menu
btn_new_upi_setting_XPATH=//button[@class='btn btn-primary']
txt_upi_vpa_NAME=vpa
txt_upi_mid_NAME=mid
txt_upi_tid_NAME=tid
txt_upi_gstIn_NAME=gstIn
txt_upi_merchant_id_NAME=pgMerchantId
txt_upi_app_key_NAME=upiAppKey
txt_upi_enc_key_NAME=encKey
btn_upi_add_ID=addbtn


#org settings page
number_of_txns_per_day_XPATH=//input[@id='maxTxnsPerDay']
minimum_amount_allowed_for_a_transaction_ID=minTxnAmount
enable_sign_for_cash_and_cheque_XPATH=//input[@id='eSignatureForNonCardEnabled1' and @type ='radio' and @value ='true']
max_refund_allowed_XPATH=//input[@id='maxRefund']
btn_save_button_XPATH=//input[@type='submit']

#Locators
tbl_txns_xpath = "//table[@id='table_txns']"
tbl_txnsHeader_xpath = "//table[@id='table_txns']/thead"
tbl_txnsBody_xpath = "//table[@id='table_txns']/tbody"
tbl_txnsRows_xpath = "//table[@id='table_txns']/tbody/tr"
tbl_txnsCols_xpath = "//table[@id='table_txns']/thead//th"
ddl_transaction_xpath = "//a[text()='Transactions ']"
mnu_transactionSearch_xpath = "//a[text()='Search']"