[APIs]
;env = DEV11
env = DEV16
;baseurl = https://dev11.ezetap.com/
baseurl = https://dev16.ezetap.com/
portallogin = merchantPortal/login

[SuperUserCredentials]
username = 9775822330
password = sandy@demo1

[Setup]
create_and_configure_merchants = False
create_and_configure_merchants_with_multi_account = False

[standalone_features]
setup_for_NonUI = False
setup_for_card = False

[Applications]
install_apps = False
mpos = MPOSX_10.1.95.apk
SA = SA_10.18.06.apk
pax_mpos = PAX_MPOSX_10.1.95.apk
pax_SA = PAX_SA_10.16.19.apk

[OtaUpdate]
mpos_version = 10.1.25
mpos_version_code = 525
sa_version = 10.16.26
sa_version_code = 1347

[ParallelExecution]
deviceOnly = False
NumberOfThreads = 1

[Ezewallet]
org = EZEWALLETMERCHANT
admin_user = 7777770001
admin_password = A123456
agent_user = 7777770002
agent_password = A123456

[selective_validation]
bool_enable_selective_validation = False
bool_validate_selected_values = True
lst_api_select_values = [__all__]
lst_db_select_values = [__all__]
lst_app_select_values = [__all__]
lst_portal_select_values = [__all__]
lst_chargeslip_select_values = [__all__]
lst_ui_select_values = [__all__]
; lst_app_ignore_values = [txn_amt,txn_amt_2,txn_amt_3,txn_amount,refund_txn_amt,pmt_amt,pmt_amt_2]
lst_app_ignore_values = []
lst_api_ignore_values = []
lst_db_ignore_values = []
lst_portal_ignore_values = []
lst_chargeslip_ignore_values = []
lst_ui_ignore_values = []

[Validations]
api_validation = True
db_validation = True
portal_validation = True
app_validation = True
ui_validation = False
charge_slip_validation = True
cs_logo_validation = False
bool_rerun_at_the_end = True
bool_rerun_at_the_end_parallel = False
bool_rerun_immediately = False
int_rerun_count = 3
bool_rerun_api_val = True
bool_rerun_db_val = True
bool_rerun_portal_val = True
bool_rerun_ui_val = False
bool_rerun_app_val = True
bool_rerun_exe_val = True
bool_rerun_chargeslip_val = True
bool_print_val_log_pass = True
bool_print_val_log_fail = True


[logs]
bool_capt_log_pass = False
bool_capt_log_fail = True
bool_capt_log_cnpware = True
bool_capt_log_middleware = True
bool_capt_log_api = True
bool_capt_log_portal = True
bool_capt_log_config = True
bool_capt_log_closedloop = True
bool_capt_log_q2 = True
bool_capt_log_commx = True
bool_capt_log_ezestore = True
# Either one should be enabled out of below two configs if logs needs to be captured
bool_capt_log_different_files = False
bool_capt_log_one_file = True
# Either one should be enabled out of below two configs if logs needs to be captured
bool_capt_log_each_run = False
bool_capt_log_last_run = True
bool_capt_log_khata = True
bool_capt_log_reward = False

[screenshots]
bool_capt_ss_pass = False
bool_capt_ss_fail = False


[environment]
str_exe_env=dev16
;str_exe_env=dev11
str_exe_env_ip=192.168.3.89
;str_exe_env_ip=192.168.3.81
str_ssh_username=avinashc
str_ssh_password=None
int_exe_env_port=22
str_ssh_key_filename=/home/ezetap/.ssh/Avinash_Choudhary
# 6389 for demo1, 6379 for dev envt
int_redis_port=6379

[path]
api = /var/log/ezetap/api/api.log
portal = /home/ezetap/ezetap/microservers/merchant-portal-api/merchant-portal.log
middleware = /var/log/ezetap/middleware/middleware.log
cnpware = /home/ezetap/ezetap/microservers/cnpware/cnpware.log
closedloop_logfile = /var/log/ezetap/closedloop/closedloop.log
config_apps_log_filepath_format = /home/ezetap/logs/{date_in_strfmt}_config_apps_server.log
q2_logfile = /home/ezetap/ezetap/microservers/middleware/log/q2.log
commx = /home/ezetap/ezetap/microservers/commx/logs/commx.log
# ezestore logs will be Available only in qa-rc env
ezestore = /home/demo/ezetap/microservers/ezestore/ezestore.log
khata = /var/log/ezetap/khata/khata.log
reward = /home/ezetap/ezetap/microservers/rewards/reward.log

[SSH]
ssh_private_key_password=
