[APIs]
;env = DEV17
;baseurl = https://dev17.ezetap.com/
;env = DEV11
;baseurl = https://dev11.ezetap.com/
env = DEV16
baseurl = https://dev16.ezetap.com/
;login = /api/2.0/auth/login/
portallogin = merchantPortal/login
;cashpayment = /api/2.0/payment/cash
;portaleditmerchant = /portal//merchants/AUTO_PYTHON_TRIAL/edit
;txnlist = /api/2.0/txn/list/home/ezetap

[SuperUserCredentials]
username = 9459860286
password = V1234567

[Setup]
create_and_configure_merchants = False
create_and_configure_merchants_with_multi_account = False

[standalone_features]
setup_for_NonUI = False
setup_for_card = False

[Applications]
install_apps = False
mpos = MPOSX_10.1.54.apk
SA = SA_10.17.34.apk

[ParallelExecution]
deviceOnly = False
NumberOfThreads = 1

[Ezewallet]
org = EZEWALLETMERCHANT
admin_user = 7777770001
admin_password = A123456
agent_user = 7777770002
agent_password = A123456

[selective_validation]
bool_enable_selective_validation = False
bool_validate_selected_values = True
lst_api_select_values = [__all__]
lst_db_select_values = [__all__]
lst_app_select_values = [__all__]
lst_portal_select_values = [__all__]
lst_chargeslip_select_values = [__all__]
lst_ui_select_values = [__all__]
; lst_app_ignore_values = [txn_amt,txn_amt_2,txn_amt_3,txn_amount,refund_txn_amt,pmt_amt,pmt_amt_2]
lst_app_ignore_values = []
lst_api_ignore_values = []
lst_db_ignore_values = []
lst_portal_ignore_values = []
lst_chargeslip_ignore_values = []
lst_ui_ignore_values = []

;[TestcaseDetails_ColumnNames]
;colname_testcaseid = Test Case ID
;colname_filename = File Name
;colname_execute = Execute
;colname_tcexecution = TC Execution
;colname_apival = API Val
;colname_dbval = DB Val
;colname_portalval = Portal Val
;colname_appval = App Val
;colname_uival = UI Val
;colname_executiontime = Execution Time (sec)
;colname_validationtime = Validation Time (sec)
;colname_logcolltime = Log Coll Time (sec)
;colname_totaltime = Total Time (sec)

[Validations]
api_validation = True
db_validation = True
portal_validation = False
app_validation = True
ui_validation = False
charge_slip_validation = True
cs_logo_validation = False
bool_rerun_at_the_end = False
bool_rerun_at_the_end_parallel = False
bool_rerun_immediately = False
int_rerun_count = 1
bool_rerun_api_val = True
bool_rerun_db_val = True
bool_rerun_portal_val = False
bool_rerun_ui_val = False
bool_rerun_app_val = True
bool_rerun_exe_val = True
bool_rerun_chargeslip_val = True
bool_print_val_log_pass = True
bool_print_val_log_fail = True


[logs]
bool_capt_log_pass = False
bool_capt_log_fail = False
bool_capt_log_cnpware = True
bool_capt_log_middleware = True
bool_capt_log_api = True
bool_capt_log_portal = True
bool_capt_log_config = True
bool_capt_log_closedloop = True
bool_capt_log_q2 = True
bool_capt_log_commx = True
bool_capt_log_ezestore = True
# Either one should be enabled out of below two configs if logs needs to be captured
bool_capt_log_different_files = False
bool_capt_log_one_file = True
# Either one should be enabled out of below two configs if logs needs to be captured
bool_capt_log_each_run = False
bool_capt_log_last_run = True

[screenshots]
bool_capt_ss_pass = False
bool_capt_ss_fail = False


[environment]
str_exe_env=dev16
str_exe_env_ip=192.168.3.89
;str_exe_env=dev17
;str_exe_env_ip=192.168.3.96
;str_exe_env=dev11
;str_exe_env_ip=192.168.3.81
str_ssh_username=vishrutsharma
str_ssh_password=None
int_exe_env_port=22
str_ssh_key_filename=/home/ezetap/.ssh/id_rsa
# 6389 for demo1, 6379 for dev envt
int_redis_port=6379

;[credentials]
;#Branding--
;username_AXIS = 7204644333
;#username_HDFC = 7204644666
;username_HDFC = 1076810767
;username_YES_ATOS = 5555123456
;username_EZETAP = 7204644777
;#
;username_dev11 = 1076810769
;password_dev11 = A111111
;#username_portal = 9731545096
;username_portal = 8891960880
;password_portal = A123456
;
;#MultiLanguage
;username_EngLang= 7204644777
;username_HindiLang= 7204644999
;username_langselection= 7204644000
;#Common
;Mobile_Number=9845698456
;Email=manasav@gmail.com
;Env="DEV11"
;password = A123456
;#APP Upgrade Username in demo1
;username_demo1=9343706316
;#cnp_user
;username_cnptxn=7204644101
;loginurl=https://dev11.ezetap.com/api/2.0/auth/login

;[testdata]
;org_code =VINEET_191036200
;org_code_yes_atos = EZEAUTO1_8174477
;#org_code_hdfc = AUTOHDFC_9225028
;org_code_hdfc = VINEET_191036200
;da_alert_message=Plese use any of the payments below all are working. Happy Shopping\n
;promo_offer =Diwali Offers
;transactions_by_date=10 May 2022

[path]
api = /var/log/ezetap/api/api.log
portal = /var/log/ezetap/portal/portal.log
middleware = /var/log/ezetap/middleware/middleware.log
cnpware = /home/ezetap/ezetap/microservers/cnpware/cnpware.log
closedloop_logfile = /var/log/ezetap/closedloop/closedloop.log
config_apps_log_filepath_format = /home/ezetap/logs/{date_in_strfmt}_config_apps_server.log
q2_logfile = /home/ezetap/ezetap/microservers/middleware/log/q2.log
commx = /home/ezetap/ezetap/microservers/commx/logs/commx.log
# ezestore logs will be Available only in qa-rc env
ezestore = /home/demo/ezetap/microservers/ezestore/ezestore.log

;[locators]
;username_name = username
;password_name = password
;signin_name = Submit
;transactions_xpath = //a[text()='Transactions ']
;transactions_search_xpath = //a[text()='Search']
;users_xpath = //a[@title='Users']
;appkeysmenu_xpath = //a[contains(text(),'App Keys')]
;merchantsmenu_xpath = //a[@title='Merchants']
;btn_merchantname_xpath = //button[text()='Clear Switch']/following-sibling::button[@class='filterToOrgCode btn btn-small btn-primary']
;setupmenu_xpath = //a[contains(text(),'Setup')]
;merchantsearch_xpath = //input[@placeholder='Search']
;switchbutton_xpath = //a[contains(@href,'orgCode')]/..//button[contains(text(),'switch')]
;orgsettings_xpath = //img[@title='Org Settings' and @alt='Org Settings']
;bulkuploads_xpath = //a[contains(text(),'Bulk Uploads')]
;bqrsettings_xpath = //a[contains(text(),'Bharatqr Settings')]
;upisettings_xpath = //a[contains(text(),'UPI Settings')]
;type_xpath = /html/body/div[1]/div[10]/div/div/div[4]/div[1]/div[1]/table/tbody/tr[1]/td[4]
;status_xpath = /html/body/div[1]/div[10]/div/div/div[4]/div[1]/div[1]/table/tbody/tr[1]/td[5]
;amount_xpath = /html/body/div[1]/div[10]/div/div/div[4]/div[1]/div[1]/table/tbody/tr[1]/td[6]
;username_xpath = /html/body/div[1]/div[10]/div/div/div[4]/div[1]/div[1]/table/tbody/tr[1]/td[7]
;txnid_xpath = /html/body/div[1]/div[10]/div/div/div[4]/div[1]/div[1]/table/tbody/tr[1]/td[9]
;editmerchant_xpath = //img[@title='Edit' and @alt='edit']
;edituser_xpath = //a[@href='mobileNum/edit']
;radio_inactive_status_id = status2
;radio_active_status_id = status1
;btn_save_xpath = //input[@type='submit']
;txt_password_name = password
;txt_confirmpassword_id = confirmPassword
;radio_user_inactive_status_id = status2
;radio_user_active_status_id = status1
;btn_next_id = saveBtn
;btn_generate_appkey_xpath = //button[contains(text(),'Generate App Key')]
;dropdown_processcode_name = defaultProcessCode
;txt_appkey_description_id = add_description
;txt_appkey_label_id = add_label
;btn_add_appkey_xpath = //div[@class='ui-dialog-buttonset']/button[text()='Generate App Key']
;txt_editlabel_id = edit_label
;btn_savechanges_xpath = //button[text()='Save']
;btn_choose_file_user_creation_modification = //tr/td[text()='User Creation/Modification']/..//input[@name='file']
;btn_create_bqr_acq_xpath = //button[@class='btn btn-primary']
;txt_visa_primary_id_name = visaMerchantIdPrimary
;txt_master_primary_id_name = mastercardMerchantIdPrimary
;txt_bqr_rupay_primary_id_name = npciMerchantIdPrimary
;txt_bqr_ifsc_name = merchantIfsc
;txt_bqr_acct_numb_name = merchantAccountNumber
;txt_bqr_name_name = merchantName
;txt_bqr_city_name = merchantCity
;txt_bqr_pin_name = merchantPinCode
;txt_bqr_category_code_name = merchantCategoryCode
;txt_bqr_currency_code_name = currencyCode
;txt_bqr_country_code_name = countryCode
;drop_bqr_bankcode_name = bankCode
;select_dummy_bankcode_xpath = //a[contains(text(),'DUMMY')]
;drop_bqr_status_name = status
;select_active_status_xpath = //a[contains(text(),'Active')]
;btn_bqr_add_id = addbtn
;btn_new_upi_setting_xpath = //button[@class='btn btn-primary']
;txt_upi_vpa_name = vpa
;txt_upi_mid_name = mid
;txt_upi_tid_name = tid
;txt_upi_gstin_name = gstIn
;txt_upi_merchant_id_name = pgMerchantId
;txt_upi_app_key_name = upiAppKey
;txt_upi_enc_key_name = encKey
;btn_upi_add_id = addbtn
;number_of_txns_per_day_xpath = //input[@id='maxTxnsPerDay']
;minimum_amount_allowed_for_a_transaction_id = minTxnAmount
;enable_sign_for_cash_and_cheque_xpath = //input[@id='eSignatureForNonCardEnabled1' and @type ='radio' and @value ='true']
;max_refund_allowed_xpath = //input[@id='maxRefund']
;btn_save_button_xpath = //input[@type='submit']
;tbl_txns_xpath = "//table[@id='table_txns']"
;tbl_txnsheader_xpath = "//table[@id='table_txns']/thead"
;tbl_txnsbody_xpath = "//table[@id='table_txns']/tbody"
;tbl_txnsrows_xpath = "//table[@id='table_txns']/tbody/tr"
;tbl_txnscols_xpath = "//table[@id='table_txns']/thead//th"
;ddl_transaction_xpath = "//a[text()='Transactions ']"
;mnu_transactionsearch_xpath = "//a[text()='Search']"

[SSH]
ssh_private_key_password=