[Stamp]
datestamp = 2022-05-10
timestamp = 17:22:00

[Reports]
excelreportpath = /home/ezetap/EzeAuto/Reports/ExecutionDate_2022-05-10/ExecutionTime_17:22:00/ExcelReport
allurereportpath = /home/ezetap/EzeAuto/Reports/ExecutionDate_2022-05-10/ExecutionTime_17:22:00/AllureReport
pdfreportpath = /home/ezetap/EzeAuto/Reports/ExecutionDate_2022-05-10/ExecutionTime_17:22:00/PDFReport

[Logs]
executionlogpath = /home/ezetap/EzeAuto/Logs/ExecutionDate_2022-05-10/ExecutionTime_17:22:00/ExecutionLog
serverlogpath = /home/ezetap/EzeAuto/Logs/ExecutionDate_2022-05-10/ExecutionTime_17:22:00/ServerLog

