[Stamp]
datestamp = 2022-05-17
timestamp = 16:16:18

[System]
automation_suite_path = /home/ezetap/EzeAuto

[ExcelFiles]
filepath_testcases_surfaceui = /home/ezetap/EzeAuto/DataProvider/TestCases_SurfaceUI.xlsx
filepath_testcasesdetail = /home/ezetap/EzeAuto/DataProvider/TestCasesDetail.xlsx

[Reports]
excelreportpath = /home/ezetap/EzeAuto/Reports/ExecutionDate_2022-05-17/ExecutionTime_16:16:18/ExcelReport
allurereportpath = /home/ezetap/EzeAuto/Reports/ExecutionDate_2022-05-17/ExecutionTime_16:16:18/AllureReport
pdfreportpath = /home/ezetap/EzeAuto/Reports/ExecutionDate_2022-05-17/ExecutionTime_16:16:18/PDFReport

[Logs]
executionlogpath = /home/ezetap/EzeAuto/Logs/ExecutionDate_2022-05-17/ExecutionTime_16:16:18/ExecutionLog
serverlogpath = /home/ezetap/EzeAuto/Logs/ExecutionDate_2022-05-17/ExecutionTime_16:16:18/ServerLog

