[Stamp]
datestamp = 2022-05-12
timestamp = 14:22:58

[System]
automation_suite_path = /home/oem/PycharmProjects/EzeAuto

[ExcelFiles]
filepath_testcases_surfaceui = /home/oem/PycharmProjects/EzeAuto/DataProvider/TestCases_SurfaceUI.xlsx
filepath_testcasesdetail = /home/oem/PycharmProjects/EzeAuto/DataProvider/TestCasesDetail.xlsx

[Reports]
excelreportpath = /home/oem/PycharmProjects/EzeAuto/Reports/ExecutionDate_2022-05-12/ExecutionTime_14:22:58/ExcelReport
allurereportpath = /home/oem/PycharmProjects/EzeAuto/Reports/ExecutionDate_2022-05-12/ExecutionTime_14:22:58/AllureReport
pdfreportpath = /home/oem/PycharmProjects/EzeAuto/Reports/ExecutionDate_2022-05-12/ExecutionTime_14:22:58/PDFReport

[Logs]
executionlogpath = /home/oem/PycharmProjects/EzeAuto/Logs/ExecutionDate_2022-05-12/ExecutionTime_14:22:58/ExecutionLog
serverlogpath = /home/oem/PycharmProjects/EzeAuto/Logs/ExecutionDate_2022-05-12/ExecutionTime_14:22:58/ServerLog

